### ISSUE TITLE
[Subtask] Hive Backend Engine - Support Multiple Hive releases

### ISSUE THREAD

**Issue by yaooqinn** [apache/kyuubi#2027]
default 2.3, up to 3.1

**Comment by pan3793** [comment]
It has been reported it engine does not work out-of-box w/ HDP Hive 3.1.3.1.0.6-1

**Comment by pan3793** [comment]
Postpone to 1.8, because this feature is not under rapid development, and it's not supposed to be accomplished in a short time.

**Comment by pan3793** [comment]
Apache Kyuubi 1.9.0 has verified on CDH Hive 2.1.1-cdh6.y.z, Apache Hive 2.3.9, Apache Hive 3.1.3
