### ISSUE TITLE
[Improvement] Add a job or step for shell script style in Github Action

### ISSUE THREAD

**Issue by yaooqinn** [apache/kyuubi#2062]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

shell script style consistency

### How should we improve?

Maybe adding https://github.com/marketplace/actions/shell-linter  in sytle.yaml is a good choice, or something else

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
cc @RishiKumarRay, can you help with this?

**Comment by RishiKumarRay** [comment]
@yaooqinn yeah i can try , can you elaborate what needs to be done ? Please, i am not able to understand completely

**Comment by yaooqinn** [comment]
It is a style checker for code written in shell

For example, Kyuubi is mainly written in scala and java, so we already have style checkers for them, see https://github.com/apache/incubator-kyuubi/blob/master/.github/workflows/style.yml#L49

We need to introduce a consistent style/format for the existing and coming shell scripts, like `bin/kyuubi`.

**Comment by RishiKumarRay** [comment]
@yaooqinn  ok, let me try this , assign me  also the path of the scripts that needs to be checked is  bin/kyuubi ? Or path where the scripts are present is different.

**Comment by yaooqinn** [comment]
You may check the repo yourself, this way is better for getting familiar with the codebase

**Comment by xiaoyuandajian** [comment]
hello,i want slove the problem.can i try?

**Comment by pan3793** [comment]
@xiaoyuandajian of course, free feel to send PR~

**Comment by xiaoyuandajian** [comment]
@pan3793 thanks

**Comment by xiaoyuandajian** [comment]
@pan3793 hello, this is my first pr, I try it in my fork project, I found there are something wrong, it's my problems or the shell script?
![image](https://user-images.githubusercontent.com/51512358/210036309-9ae6d2e8-3773-44c2-bdca-7d041973db8e.png)

**Comment by xiaoyuandajian** [comment]
this is the update script, I use shell-linter
![image](https://user-images.githubusercontent.com/51512358/210036400-de24f7fe-2c9d-4de3-8cbc-e56a8242b7da.png)

**Comment by xiaoyuandajian** [comment]
this is update script, I use shell-linter
![image](https://user-images.githubusercontent.com/51512358/210036454-0db44e60-9510-4cfa-9aab-314b7baa8b3b.png)

**Comment by xiaoyuandajian** [comment]
> this is update script, I use shell-linter
> ![image](https://user-images.githubusercontent.com/51512358/210036454-0db44e60-9510-4cfa-9aab-314b7baa8b3b.png)

it looks I need write some spellcheck disable in these files? should I?

**Comment by pan3793** [comment]
The [shell-linter's doc](https://github.com/marketplace/actions/shell-linter#severity) say:
> ### `severity`
> Optional. Specify minimum severity of errors to consider [style, info, warning, error]. Default: style

So it's expected to report some style issue since we never use any shell linter to check that.

**Comment by xiaoyuandajian** [comment]
ok, thanks
