### ISSUE TITLE
Docker Compose based one-click Kyuubi Playground

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#2365]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Provide a one-click setup Kyuubi playground.

### How should we improve?

We can leverage Docker Compose to implement this feature. And I already have a demo in https://github.com/housepower/spark-clickhouse-connector/pull/84

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by pan3793** [comment]
And we may need a BI service such as SuperSet and some prepared dataset and charts in the playground.

**Comment by yaooqinn** [comment]
https://github.com/apache/incubator-kyuubi/issues/1653

**Comment by yaooqinn** [comment]
cc @yanghua @turboFei , I am big + 1

**Comment by yaooqinn** [comment]
also cc @Yikun, I reminder you guys have free one line resources for building live demo

**Comment by yaooqinn** [comment]
Something like https://tryme.openlookeng.io/

**Comment by turboFei** [comment]
+1, cool

**Comment by Yikun** [comment]
> also cc @Yikun, I remember that you guys have free one line resources for building live demos

Yep, we can donate resource VM (openEuler Based VM with public IP) to help opensource community for application demo and ci validation.  : ) also cc @martin-g

**Comment by yanghua** [comment]
> cc @yanghua @turboFei , I am big + 1

+1 s.g.

**Comment by martin-g** [comment]
Hi,

I was able to run https://github.com/housepower/spark-clickhouse-connector/pull/84 on my openEuler ARM64 with the following changes! 

```diff
diff --git docker/compose.yml docker/compose.yml
index 04d43e7..47153d0 100644
--- docker/compose.yml
+++ docker/compose.yml
@@ -12,7 +12,7 @@
 
 services:
   minio:
-    image: bitnami/minio:latest
+    image: minio/minio:latest
     environment:
       MINIO_ROOT_USER: minio
       MINIO_ROOT_PASSWORD: minio_minio
@@ -23,7 +23,7 @@ services:
       - 9001:9001
 
   mysql:
-    image: mysql:${MYSQL_VERSION}
+    image: mariadb:latest
     environment:
       MYSQL_USER: mysql
       MYSQL_PASSWORD: mysql
```

I needed to change these two images because the original used ones didn't support arm64 architecture.
