### ISSUE TITLE
[Bug] 在SparkOperation、FlinkOperation、ExecuteStatement是否存在加锁问题？ 

### ISSUE THREAD

**Issue by shenbinglife** [apache/kyuubi#2689]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

在SparkOperation、FlinkOperation、ExecuteStatement等频繁用到了 state.synchronized {代码块}， 请问state是一个变量并且会在SQL执行过程中不断重新赋值， 怎么可以作为锁对象呢？ 

### Affects Version(s)

1.5.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by cxzl25** [comment]
Fixed by https://github.com/apache/incubator-kyuubi/issues/4739
