### ISSUE TITLE
[Bug]  kyuubi UI cann't show spark-scala-core statement running state

### ISSUE THREAD

**Issue by FishManHome** [apache/kyuubi#2886]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

**Thies is my test code:**
     ` execute(conn, st, "create or replace temporary view orders_view as select * from ods_pupu_main.orders where status <> 10;"); `
       ` execute(conn, st, "set kyuubi.operation.language=scala;");`
        `String core = "val df = spark.sql(\"select id, pay_type from orders_view\")  \n" +
                "df.filter(\"pay_type <> -1\").createOrReplaceTempView(\"res\") \n" +
                "df.count()  \n";
        execute(conn, st, core);`
        `execute(conn, st, "spark.conf.set(\"kyuubi.operation.language\", \"sql\")");`
        `execute(conn, st, "select * from res limit 3");`

**The kyuubi UI only show  sql-running-state no core-running-state.**

### Affects Version(s)

1.5.1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by FishManHome** [comment]
@pan3793

**Comment by yaooqinn** [comment]
thanks @FishManHome, looks good to support scala showing on kyuubi ui

**Comment by FishManHome** [comment]
> thanks @FishManHome, looks good to support scala showing on kyuubi ui

I aslo have one suggest.
In kyuubi UI , I cann't find someone sql  in  SQL Statistics  belong to whinch session id.
I hope kyuubi UI can add session-id field in SQL Statistics.
