### ISSUE TITLE
[Subtask] Connectors for Hive SQL Query Engine -> Flink Table Store 

### ISSUE THREAD

**Issue by a49a** [apache/kyuubi#3085]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the subtask

Hive of Flink Table Store doc

### Parent issue

https://github.com/apache/incubator-kyuubi/issues/3059

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by pan3793** [comment]
@a49a do you have the opportunity to complete it before 1.7?
