### ISSUE TITLE
[Umbrella] Support Scala 2.13

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#3163]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the proposal

Scala 2.13 has been adopted widely, e.g. Apache Spark, Apache Kafka, it's time to make Kyuubi support Scala 2.13.

We should make Kyuubi pass build Scala 2.13 first, and deliver scala 2.13 binary tarball in 1.8 or 1.9

### Task list

- #3194
- #5177
- #5178
- #5179
- #5180
- #5184
- #5183
- Introduce `change-scala-version.sh` 
- pass compile on scala-2.13 (maybe module by module)
  - #5188
  - spark authz plugin #5189
  - spark extension plugin #5191
  - spark lineage plugin #5192
  - spark hive connector plugin #5193
  - spark tpc-ds / tpc-h connector plugin #5195
- add CI in github action for scala-2.13 #5188 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by SergWh** [comment]
Anyone planning to take this one? If not, I can try to make PR later this week. In our company we managed to make working 2.13 distribution (only modules required to run with Spark) but code needs a little cleanup

**Comment by pan3793** [comment]
Thanks @SergWh, feel free to open PRs, we plan to make the whole project support scala 2.13 eventually.

**Comment by AdarshRawat1** [comment]
Requesting permission to contribute to this feature. . Can you please advise on how I can get involved? Thanks

**Comment by pan3793** [comment]
@AdarshRawat1 thanks for interesting in this project.

I suppose you have basic knowledge about Maven, Scala, and How to send GitHub PR. (correct me if not).

You can start w/ one module, say `kyuubi-common`, making it pass compiling w/ Scala 2.13.

**Comment by AdarshRawat1** [comment]
> @AdarshRawat1 thanks for interesting in this project.
> 
> I suppose you have basic knowledge about Maven, Scala, and How to send GitHub PR. (correct me if not).
> 
> You can start w/ one module, say `kyuubi-common`, making it pass compiling w/ Scala 2.13.

Yes, I have basic knowledge about Maven, Scala and sending GitHub PR. 
I'll start with `kyuubi-common`. Could you kindly provide me with additional resources and guidance, please?

**Comment by pan3793** [comment]
Basically, add a `scala-2.13` profile in root `pom.xml`

```
        <profile>
            <id>scala-2.13</id>
            <properties>
                <scala.version>2.13.10</scala.version>
                <scala.binary.version>2.13</scala.binary.version>
            </properties>
        </profile>
```

Change the `kyuubi-common/pom.xml`

```patch
-    <artifactId>kyuubi-common_2.12</artifactId>
+    <artifactId>kyuubi-common_${scala.binary.version}</artifactId>
```

And then, compile by `build/mvn clean package -pl kyuubi-common -am -Pscala-2.13`, there may some compiling or testing errors caused by breaking changes between scala 2.12 and 2.13, find and fix them until pass the building and compiling.

Also, better to update the GitHub workflow to check your change by CI

**Comment by chrisfw** [comment]
Hello, 

First, thank you for all of the great work on this project.  It has made exposing Iceberg functionality through JDBC much easier.  I just wanted to inquire about the status of completing the integration of Scala 2.13?  Some of the most recent iceberg functionality seems to require 2.13 in order to successfully utilize the latest iceberg spark sql extensions (org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions).  Attempting to use them in Spark with Scala 2.12 results in a class not found exception that is not an issue when using 2.13.  This extension is necessary to call Iceberg Spark procedures, e.g. 
```
CALL my_catalog.system.create_changelog_view(table => 'iceberg.mysample',
 identifier_columns => array('id'),
 compute_updates => true );
```
I am hoping to utilize this functionality through kyuubi hence my interest in this issue.

Regards,
Chris Whelan

**Comment by chrisfw** [comment]
@pan3793 , thanks for your quick response.  The error using occurs in the combo of iceberg + Spark 3.3.2 and is not a kyuubi error.  

I added these iceberg+s3 dependencies to the driver and executor extraClassPath in spark-defaults.conf:

```
annotations-2.20.7.jar
aws-java-sdk-bundle-1.11.563.jar
bundle-2.20.7.jar
eventstream-1.0.1.jar
hadoop-aws-3.3.0.jar
hamcrest-core-1.3.jar
http-client-spi-2.20.7.jar
iceberg-spark-runtime-3.3_2.13-1.2.1.jar
junit-4.11.jar
metrics-spi-2.20.7.jar
reactive-streams-1.0.3.jar
slf4j-api-1.7.30.jar
url-connection-client-2.20.7.jar
utils-2.20.7.jar
wildfly-openssl-1.0.7.Final.jar
```
I also added the iceberg catalog properties:

```
spark.sql.catalog.my_catalog=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.my_catalog.warehouse=s3a://warehouse
spark.sql.catalog.my_catalog.io-impl=org.apache.iceberg.aws.s3.S3FileIO
spark.sql.catalog.my_catalog.s3.endpoint=http://10.18.102.29:9000
spark.sql.catalog.my_catalog.catalog-impl=org.apache.iceberg.jdbc.JdbcCatalog
spark.sql.catalog.my_catalog.uri=jdbc:postgresql://10.18.102.29:5432/iceberg
spark.sql.catalog.my_catalog.jdbc.verifyServerCertificate=false
spark.sql.catalog.my_catalog.jdbc.user=spark
spark.sql.catalog.my_catalog.jdbc.useSSL=false
spark.sql.catalog.my_catalog.jdbc.password=spark
spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
```
The addition of the Iceberg SQL Extension appears to cause a class not found error:

```
[spark@demo-sds-server1 ~]$ spark-sql
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
23/05/24 14:05:06 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
23/05/24 14:05:09 WARN HiveConf: HiveConf of name hive.stats.jdbc.timeout does not exist
23/05/24 14:05:09 WARN HiveConf: HiveConf of name hive.stats.retries.wait does not exist
Spark master: local[*], Application Id: local-1684937107783
spark-sql> use my_catalog.iceberg;
23/05/24 14:05:37 ERROR SparkSQLDriver: Failed in [use my_catalog.iceberg]
java.lang.NoClassDefFoundError: scala/$less$colon$less
```
Googling the error, I found a [post](https://community.snowflake.com/s/question/0D53r0000BwiXlhCQE/getting-error-when-trying-to-use-snowflake-spark-connector-py4jprotocolpy4jjavaerror-an-error-occurred-while-calling-o43csv-javalangnoclassdeffounderror-scalalesscolonless) indicating the Scala version issue.  

When I updated my setup to Spark 3.3.2 with Scala 2.13, there was no class not found error and the Iceberg catalog, table, and spark procedure functionality all worked properly.
```
spark-sql> CALL my_catalog.system.create_changelog_view(table => 'iceberg.mysample');
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
`mysample_changes`
Time taken: 4.803 seconds, Fetched 1 row(s)
```
If there is a workaround/solution that enables me to utilize the latest Iceberg runtime in Spark 3.3.2 with Scala 2.12, that would be great.  Please let me know if you require any additional assistance.

Thanks,
Chris Whelan

**Comment by pan3793** [comment]
`iceberg-spark-runtime-3.3_2.13-1.2.1.jar`

This jar is built against scala 2.13, the typical scala jar name is compose of `{moudle.name}_{scala.binary.version}-{version}.jar`, in your case, you should use `iceberg-spark-runtime-3.3_2.12-1.2.1.jar` instead.

**Comment by pan3793** [comment]
You can get the jar from maven central

https://mvnrepository.com/artifact/org.apache.iceberg/iceberg-spark-runtime-3.3
<img width="1350" alt="image" src="https://github.com/apache/kyuubi/assets/26535726/8447090c-15db-4d09-bcad-0d630c3e797f">

**Comment by chrisfw** [comment]
@pan3793 , thank you very much!  It seems obvious in retrospect looking at the version number, but with a variety of packages at different versions I didn't realize the semantic significance of the iceberg versioning scheme.

**Comment by he-gupta** [comment]
can I contribute to this issue?

**Comment by pan3793** [comment]
@he-gupta of course, we appreciate contributions from everyone.

**Comment by hh-cn** [comment]
Does anyone know how is this going? Why is there still no binary tarball download for scala-2.13? When can we have that?

**Comment by pan3793** [comment]
@hh-cn it's completed.

> Why is there still no binary tarball download for scala-2.13?

As Kyuubi is a service, not a library, we don't want to provide multi Scala versions binary tarball. If you are looking for support for Spark Scala 2.13 runtime, the latest 1.9.3, which is already supported in the latest [v1.9.2](https://dlcdn.apache.org/kyuubi/kyuubi-1.9.2/apache-kyuubi-1.9.2-bin.tgz).

**Comment by hh-cn** [comment]
Our development team is currently transitioning to Scala 2.13, and we no longer want to maintain a 2.12 version. We have developed some Kyuubi/Spark plugins, and I originally planned to download and replace the Scala 2.13 related Kyuubi JARs from the Maven repository when building the Docker image. However, I found that while some, like kyuubi-common_2.12-1.9.2.jar, have Scala 2.13 versions, most, like kyuubi-ctl_2.12-1.9.2.jar and kyuubi-events_2.12-1.9.2.jar, do not. I want to know why this is and where I can find them.

@pan3793 can you help answer this? thank you

**Comment by pan3793** [comment]
We haven't published all components built with Scala 2.13 to Maven Central yet.

For your case, I think you can maintain a fork version of Kyuubi and modify `pom.xml` to switch to Scala 2.13 by default, then deploy the jars to your private Nexus.

**Comment by pan3793** [comment]
Fully Scala 2.13 migration in the Kyuubi project is likely to happen at the end of 2024 or early 2025,  at that time, Kyuubi will likely drop support for Java 8/11, Scala 2.12 and Spark 3, requires Java 17, Scala 2.13 and Spark 4.

**Comment by hh-cn** [comment]
Oh, I see. Thanks for your answer
