### ISSUE TITLE
[DOCS] Kyuubi RESTful API admin 

### ISSUE THREAD

**Issue by zwangsheng** [apache/kyuubi#3332]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Which parts of the documentation do you think need improvement?

We need doc about introducing kyuubi rest api `/admin` and examples here [RESTful APIs and Clients](https://kyuubi.readthedocs.io/en/latest/client/rest/index.html)

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by deadwind4** [comment]
I would like to take this.
