### ISSUE TITLE
[BUG] Command should not execute when plan only mode is set to PHYSICAL or EXECUTION

### ISSUE THREAD

**Issue by lsm1** [apache/kyuubi#3435]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

```scala
      case PhysicalMode =>
        val physical = spark.sql(statement).queryExecution.sparkPlan
        iter = new IterableFetchIterator(Seq(Row(physical.toString())))
      case ExecutionMode =>
        val executed = spark.sql(statement).queryExecution.executedPlan 
        iter = new IterableFetchIterator(Seq(Row(executed.toString())))
```
when `kyuubi.operation.plan.only.mode` is set to `PHYSICAL` or `EXECUTION`, we get plan from `queryExecution`, both `sparkPlan` and `executedPlan` will call `assertCommandExecuted()` ,  the  Command plan such as `DropTableCommand` will execute

### Affects Version(s)

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by cxzl25** [comment]
https://github.com/apache/kyuubi/issues/6574
