### ISSUE TITLE
[FEATURE] The planOnly mode of kyuubi spark engine support SQL lineage output

### ISSUE THREAD

**Issue by iodone** [apache/kyuubi#3444]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

 Executing sql with the `PlanOnly` mode will get the output of SQL's lineage

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by lianneli** [comment]
I'm so curious about the result with SQL's lineage~

**Comment by iodone** [comment]
> I'm so curious about the result with SQL's lineage~

You can refer to this pr https://github.com/apache/incubator-kyuubi/pull/3185
