### ISSUE TITLE
[Improvement] Separating the Hudi IT into an independent module

### ISSUE THREAD

**Issue by cfmcgrady** [apache/kyuubi#3528]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

https://github.com/apache/incubator-kyuubi/pull/3486#issuecomment-1246254923

Separating the Hudi IT into an independent module, then the classpath of server and spark engine modules will not be affected by Hudi bundle jar

### Are you willing to submit PR?

- [ ] Yes. I can submit a PR independently to improve.
- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
Close as we already removed Hudi tests https://github.com/apache/kyuubi/pull/4744
