### ISSUE TITLE
[FEATURE] Add Kyuubi Web UI

### ISSUE THREAD

**Issue by zhaohehuhu** [apache/kyuubi#3644]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

As a SQL gateway,  Kyuubi with Web UI will make tenants easier to learn the status and resource consumption of Kyuubi servers and engines. Besides, Web UI can be used to manage queries. 

- #3643
- #3645
- #3646
- #3647
- #3648
- #3649
- #3650
- #3651
- #3652
- #3653
- #3654
-  #3655
- #3656
- #3657

### Are you willing to submit PR?

- [ ] Yes. I can submit a PR independently to improve.
- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by waywtdcc** [comment]
hello, how is this now

**Comment by zwangsheng** [comment]
> hello, how is this now

Hi, you can find Kyuubi Web Process with this PR https://github.com/apache/kyuubi/pull/4460, we are breaking up this PR and moving forward step by step, so if there is interest, you can participate in contributing.
