### ISSUE TITLE
[Improvement][K8S] Bump Kubernetes Client Version to 6.1.1 

### ISSUE THREAD

**Issue by zwangsheng** [apache/kyuubi#3677]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Bump Kubernetes Client Version to 6.1.1.
To keep up with [spark's](https://github.com/apache/spark/pull/37990) dependence kubernetes client [changes](https://github.com/fabric8io/kubernetes-client/compare/v5.12.1...v6.1.1).

### How should we improve?

Bump Kubernetes Client Version to 6.1.1.

### Are you willing to submit PR?

- [ ] Yes. I can submit a PR independently to improve.
- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by zwangsheng** [comment]
I'm more than happy to do this upgrade kubernetes client with waiting for the PR #3663 merged to avoid merge modification issues.

**Comment by samochod23** [comment]
Class Class1
{
       
     void Fun()
 {
Int. j=0
Var cust=new Custom() :

NEWMethood(ref int j. ref
CustomStrut cust) :
} private static. Void NewMehood j. ref
CustomStust)
{
j +=. cust. Bump() //     Select this line.
}
}
If the"Don't put ref or out on custom stuct" option is checked, them the"Extract metod" features generators the following.
class Class1
{
void Fun1
{
Int j=0
van cust =   0
van cust
= New CustomStrust
cust}
{
just. Bump() : // Select this line.
  }
} _

**Comment by zwangsheng** [comment]
See more in #4453
