### ISSUE TITLE
[Umbrella] Add support for executing Python/PySpark scripts

### ISSUE THREAD

**Issue by cfmcgrady** [apache/kyuubi#3780]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the proposal

Add support for executing Python/PySpark code snippet

### Task list

- #3775
- #3782 
- #3797
- #3807 
- #3896 
- #3900 
- #3908 
- #4018 
- #4019 
- #4028 
- #4026 
- #4031 

### Are you willing to submit PR?

- [ ] Yes. I can submit a PR independently to improve.
- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by yaooqinn** [comment]
cc @pan3793 @cfmcgrady, shall we close this and target it to v1.7?

**Comment by cfmcgrady** [comment]
+1, SGTM

**Comment by pan3793** [comment]
+1, and thank @cfmcgrady for driving this.
