### ISSUE TITLE
[Improvement] Upgrading and migration script for Jdbc

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#3968]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Since 1.6.0, Kyuubi supports use JDBC to store metadata for Batch Job API, we need upgrading and migration script for that like HMS does. 

### How should we improve?

Providing upgrading and migration script like HMS does.

### Are you willing to submit PR?

- [ ] Yes. I can submit a PR independently to improve.
- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by lightning-L** [comment]
I'd like to look into this: https://github.com/apache/hive/tree/master/metastore/scripts

**Comment by pan3793** [comment]
Thanks @lightning-L
