### ISSUE TITLE
[FEATURE] Support Apache Phoenix Engine

### ISSUE THREAD

**Issue by 531651225** [apache/kyuubi#3999]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Support Apache Phoenix engine Base on JDBC Engin
Apache Phoenix enables OLTP and operational analytics in Hadoop for low latency applications .

### Are you willing to submit PR?

- [X] Yes. I can submit a PR independently to improve.
- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
Closed by #4000
