### ISSUE TITLE
Update NOTICE to mention 2023

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#4061]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

It's 2023 now, happy new year! We should update `NOTICE` and `NOTICE-binary` to mention that.

### How should we improve?

```patch
- Copyright 2021-2022 The Apache Software Foundation.
+ Copyright 2021-2023 The Apache Software Foundation.
```

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by AdithyaPadmashali** [comment]
Hi, can I be assigned to this? I'm willing to submit a PR
