### ISSUE TITLE
[DOCS] Documentation is not accessible

### ISSUE THREAD

**Issue by Salbinus** [apache/kyuubi#4142]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Which parts of the documentation do you think need improvement?

The [docs](https://kyuubi.apache.org/docs/latest/) are not available.

### Affects Version(s)

master/1.6.1

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
Hi @Salbinus, we recently update the website, please clear your web browser cache, and find the 
new docs link in the homepage https://kyuubi.apache.org/

**Comment by Salbinus** [comment]
Hi @pan3793 , works again, thanks! I guess you'd also like to apply the links in the [README.md](https://github.com/apache/kyuubi/blob/master/README.md)?

**Comment by yaooqinn** [comment]
@Salbinus can you send a PR to fix readme?
