### ISSUE TITLE
[Improvement]  GetTables is too slow

### ISSUE THREAD

**Issue by parisni** [apache/kyuubi#4171]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

The GetTables operation (triggered for eg by dbeaver when listing the tables) is slow when the number of tables is not small. The getTables process takes 1 minute for 200 tables/views, on various catalog (jdbc, hive...).

### How should we improve?

This operation might be batched

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
Do you have a test on Hive/Trino? What's their performance?

**Comment by parisni** [comment]
I didn't test trino, only hive and jdbc. Both are surprisingly slow as compared to catalog listing (show tables * desc table )
