### ISSUE TITLE
[Improvement] spark showProgress can briefly output info of the job

### ISSUE THREAD

**Issue by zzzzming95** [apache/kyuubi#4186]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

When kyuubi.session.engine.spark.showProgress setting true, the user executing the job will print information about the progress of the current Stage. like this:
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/13965087/213206998-e6c33962-5da4-4ee4-9c8a-c357649957da.png">

We can also briefly output the information of the job ,eg [job jobid ( completed stage / total stage )], like this :
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/13965087/213207484-9ffbc74c-ae92-4061-aadc-c96cc905efbf.png">

### How should we improve?
Add [job jobid ( completed stage / total stage )] in front.
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/13965087/213207503-078f2076-1386-48f3-a9da-b9c042c7ff49.png">

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by davidyuan1223** [comment]
i want improve this issue

**Comment by davidyuan1223** [comment]
@cxzl25 hello,i have some question about this issue, the stageInfo has not property about jobId,and i found a code block abount miss logs about logs in code

`  // For broadcast, Spark will introduce a new runId as SPARK_JOB_GROUP_ID, see:
  // https://github.com/apache/spark/pull/24595, So we will miss these logs.
  // TODO: Fix this until the below ticket resolved
  // https://issues.apache.org/jira/browse/SPARK-34064`
 
  if we want add job info in the log, we need add about [jobId,Seq[StageInfo]] map,when a stage is submitted, it will check the submitted stageInfo is in the Seq[StageInfo], is that right?
