### ISSUE TITLE
[DOCS] Fix typo in a title of the Flink FTS Connector

### ISSUE THREAD

**Issue by a49a** [apache/kyuubi#4197]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Affects Version(s)

1.6.1

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by bowenliang123** [comment]
Could you show which part of doc you're about to fix? Quoting in code blocks or screenshots.
