### ISSUE TITLE
[Improvement] Add CODEOWNERS file

### ISSUE THREAD

**Issue by jiwq** [apache/kyuubi#4211]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Improve the develop experience when developer opens a pull request, and quickly notify the related code owners.

### How should we improve?

Add CODEONWERS file in `.github` and assign the code owner.
- Code owners are automatically requested for review when someone opens a pull request that modifies code that they own. 
- Code owners are not automatically requested to review draft pull requests. 

> People with admin or owner permissions can set up a CODEOWNERS file in a repository.

More info [about code owners](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by jiwq** [comment]
cc @yaooqinn @pan3793 @turboFei @ulysses-you

**Comment by yaooqinn** [comment]
I am unsure whether it is better to cc someone automatically than ping directly and politely

**Comment by jiwq** [comment]
> I am unsure whether it is better to cc someone automatically than ping directly and politely
If someone contribute to one module, he/she should find the owner then trigger the ping action. But sometimes we can't find the right person to ensure this change is right, so that some fix can't quickly to be accepted.

**Comment by yaooqinn** [comment]
Can you provide some good practices for code owners? I did some online search with github but couldn't find any.

The geode project introduced it once, but it did not last long. FYI, https://github.com/apache/geode/pull/7820. 
I truly believe the reason why they decommissioned it

The beam project has an open issue for codeowner which gets no response
https://github.com/apache/beam/issues/19095
