### ISSUE TITLE
[Bug] Use the hive connector plugin to realize the federated query of multiple hive metastores, and found that the execution of the INSERT INTO statement reported an error

### ISSUE THREAD

**Issue by jiaoqingbo** [apache/kyuubi#4222]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Configure according to the following documents
https://kyuubi.readthedocs.io/en/master/connector/spark/hive.html#kyuubi-hive-conf

![image](https://user-images.githubusercontent.com/14961757/215996673-9cb819c1-b578-4038-b132-3fe22415ed1c.png)

execute select successfully

![image](https://user-images.githubusercontent.com/14961757/215997126-a216803d-b769-4680-99c5-28781e3b4312.png)
execute insert into，then report an error

![image](https://user-images.githubusercontent.com/14961757/215997276-e36f6808-5eaa-42c7-bc1c-1c5907411a6d.png)

![image](https://user-images.githubusercontent.com/14961757/215997370-4cd13552-e278-4bee-b558-b07789e8d4be.png)

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [X] No. I cannot submit a PR at this time.

**Comment by Yikf** [comment]
Thanks @jiaoqingbo for reporting this issue, will take a look. It looks like the `SessionCatalog` is unexpected.
