### ISSUE TITLE
Bump Arrow 11.0.0

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#4268]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Bump Arrow 11.0.0

https://www.mail-archive.com/dev@arrow.apache.org/msg28637.html

### How should we improve?

Bump Arrow 11.0.0

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by runzhliu** [comment]
I just made a [PR](https://github.com/apache/kyuubi/pull/4273/commits/5329a842ff862d648018a08f82100ad370a1f969) for that.

**Comment by bowenliang123** [comment]
Have changed the title and description of PR 4273 linked to this. @runzhliu
