### ISSUE TITLE
Bump JUnit to 4.13.2

### ISSUE THREAD

**Issue by bowenliang123** [apache/kyuubi#4298]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

- bump Junit4 from 4.13.1 to 4.13.2 , release note: https://github.com/junit-team/junit4/blob/HEAD/doc/ReleaseNotes4.13.2.md

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
Closed by #4310
