### ISSUE TITLE
[Bug] Backport HIVE-15820: comment at the head of beeline -e

### ISSUE THREAD

**Issue by cxzl25** [apache/kyuubi#4305]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

https://issues.apache.org/jira/browse/HIVE-15820

```bash
bin/beeline -u jdbc:hive2://X:10009 -e "
--1
select 123;
"
```
Actual:
Nothing

Expect: 
```
+------+
| 123  |
+------+
| 123  |
+------+
1 row selected (0.339 seconds)
```

### Affects Version(s)

all

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by lsm1** [comment]
I can try it.

**Comment by cxzl25** [comment]
> I can try it.

Thanks.
