### ISSUE TITLE
[Improvement][Lineage] Non-temporary views do not resolve to a specific real table

### ISSUE THREAD

**Issue by iodone** [apache/kyuubi#4330]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Reference: https://github.com/apache/kyuubi/pull/3326

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by bowenliang123** [comment]
A switch config should be provided to choose either way of treating Permanent views as or as not the source tables in the lineage plugin, unlike in Authz plugin.

**Comment by iodone** [comment]
> A switch config should be provided to choose either way of treating Permanent views as or as not the source tables in the lineage plugin, unlike in Authz plugin which ignores all the shadowed upstream tables.

Good idea, thanks.
