### ISSUE TITLE
[Bug] When using kyuubi to do data masking, an error is reported

### ISSUE THREAD

**Issue by Jackhjf** [apache/kyuubi#4341]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Configure the mask policy on the ranger, and when executing sql through Spark, an error is reported

<img width="1532" alt="image" src="https://user-images.githubusercontent.com/33471639/219309415-498c9451-cde7-4730-b6dd-41ecd97ff0c2.png">

### Affects Version(s)

master

### Kyuubi Server Log Output

```logtalk
spark-sql> select name from iceberg_spark.test_copy;
Error in query: Resolved attribute(s) name#6 missing from id#5,name#7 in operator !Project [name#6]. Attribute(s) with the same name appear in the operation: name. Please check if the right attribute(s) are used.;
!Project [name#6]
+- SubqueryAlias spark_catalog.iceberg_spark.test_copy
   +- Project [id#5, md5(cast(name#6 as binary)) AS name#7]
      +- RowFilterAndDataMaskingMarker
         +- RelationV2[id#5, name#6] spark_catalog.iceberg_spark.test_copy



### Kyuubi Engine Log Output

_No response_

### Kyuubi Server Configurations

_No response_

### Kyuubi Engine Configurations

```yaml
spark.sql.extensions org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,org.apache.kyuubi.plugin.spark.authz.ranger.RangerSparkExtension
```

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by bowenliang123** [comment]
Known issue applying column masking on DataSourceV2Relation as in https://github.com/apache/kyuubi/issues/4202. 
Suggested ut and fix in https://github.com/apache/kyuubi/pull/4304, but it's in pending status. More work is required to do.

**Comment by bowenliang123** [comment]
Fixed in https://github.com/apache/kyuubi/pull/4358. Please have a check.

**Comment by Jackhjf** [comment]
> Fixed in #4358. Please have a check. @Jackhjf

Thanks for your work, I can get the correct result with the following use case； @bowenliang123 @yaooqinn 


create table yhbi.test_copy(id string,name string) using iceberg ;
create table yhbi.test_copy1(id1 string,name1 string) using iceberg ;
create table yhbi.test1(id string,name string) using iceberg（**name** is the data masking field;
create table iceberg_spark.test_copy(id string,name string) using iceberg （**name** is the data masking field）;

 001 

insert into yhbi.test_copy select *from  iceberg_spark.test_copy

002 


insert into yhbi.test_copy1 select *from  iceberg_spark.test_copy

003 

insert overwrite yhbi.test_copy1 select id,name as name1 from  iceberg_spark.test_copy 

004 

insert overwrite yhbi.test_copy1 select id ,name as name1 from iceberg_spark.test_copy  a where a.id in ("111111","11111");


005


insert overwrite yhbi.test_copy1 select id ,name as name1 from iceberg_spark.test_copy order by id, name;

006 

select max(name) from iceberg_spark.test_copy;
select min(name) from iceberg_spark.test_copy;

007 

insert overwrite yhbi.test_copy1 select id ,count(name) from iceberg_spark.test_copy  group by id;
insert overwrite yhbi.test_copy1 select count(id) ,name from iceberg_spark.test_copy  group by name;


008 

insert overwrite yhbi.test_copy1 select b.id,b.name from iceberg_spark.test_copy a join  iceberg_spark.test1 b on a.id=b.id;

009 
insert overwrite yhbi.test_copy1  select id,name as name1 from iceberg_spark.test_copy union select *from  (select a.id ,a.name from iceberg_spark.test1 a  join iceberg_spark.test_copy b on a.id=b.id) c;

**Comment by yaooqinn** [comment]
thanks @Jackhjf for the validation

**Comment by Jackhjf** [comment]
> thanks @Jackhjf for the validation
now i found a problem，if I excute this sql：
select id ,name as name1 from iceberg_spark.test_copy  a where a.name like "中%"; 
I will get an empty result

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/33471639/223753849-a01805f9-c1c9-4a51-9046-d2a39258a183.png">

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/33471639/223753943-408a4612-6bb8-4f3c-8a50-c26f3bf87ac2.png">



@yaooqinn

**Comment by yaooqinn** [comment]
You have a mask rule on the column - name -, which will be masked during scan operation, so the operations that follow will only get the masked data.

I know it's a bit counterintuitive. But it is correct. Supposing we don't mask ahead and change your test case to `select id ,name from iceberg_spark.test_copy a where a.name ='Jackhjf'`. Users get the result `md5('Jackhjf')`, but everyone knows the datasource contains records for `Jackhjf`. In such a case, the data is not secured, right?

**Comment by Jackhjf** [comment]
> You have a mask rule on the column - name -, which will be masked during scan operation, so the operations that follow will only get the masked data.
> 
> I know it's a bit counterintuitive. But it is correct. Supposing we don't mask ahead and change your test case to `select id ,name from iceberg_spark.test_copy a where a.name ='Jackhjf'`. Users get the result `md5('Jackhjf')`, but everyone knows the datasource contains records for `Jackhjf`. In such a case, the data is not secured, right?

From this point of view, the data is really not safe.thanks
