### ISSUE TITLE
Bump Jersey from 2.38 to 2.39 and remove the unnecessary dependency exclusion for Junit

### ISSUE THREAD

**Issue by bowenliang123** [apache/kyuubi#4357]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

- Jersey 2.39 release note (https://github.com/eclipse-ee4j/jersey/releases/tag/2.39)
- remove the unnecessary dependency exclusion for `org.junit.jupiter:junit-jupiter` from `jersey-media-multipart`, as  fixed in https://github.com/eclipse-ee4j/jersey/pull/5229

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by bowenliang123** [comment]
Wait for its publishment on the mirror repo ( https://maven-central-asia.storage-download.googleapis.com/maven2/) first, or it fails to build.

**Comment by a49a** [comment]
I throw an error.

> [ERROR] Rule 0: org.apache.maven.plugins.enforcer.EnforceBytecodeVersion failed with message:
IOException while reading /Users/ada/.m2/repository/org/glassfish/jersey/core/jersey-common/2.39/jersey-common-2.39.jar

**Comment by pan3793** [comment]
Looks like your local cache is corrupt, it suppose to encounter this when you use the aliyun mirror, please clear your local cache and re-download.

**Comment by a49a** [comment]
Yes, you are right. After I deleted my local cache, it works.
