### ISSUE TITLE
[Improvement] Drop flink 1.14 version

### ISSUE THREAD

**Issue by a49a** [apache/kyuubi#4387]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

After the Flink 1.17 release, we can drop the support of the 1.14 version.

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
As per discussion, Kyuubi suppose to support the latest 3 feature versions of Flink, let's do it when the support for Flink 1.17 is ready (at least the PR in a good shape)

**Comment by pan3793** [comment]
I think it's time to drop Flink 1.14 in master, @a49a do you have time to send PR?
