### ISSUE TITLE
[Improvement] Render the batchInfo in `kyuubi-ctl`

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#4438]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

`kyuubi-ctl` should support to render `batchInfo` filed which is added in https://github.com/apache/kyuubi/pull/4390

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by lightning-L** [comment]
I'd like to submit a PR for this
