### ISSUE TITLE
[Bug] Flink insert statements block connections until the job finished

### ISSUE THREAD

**Issue by link3280** [apache/kyuubi#4446]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Flink engine is supposed to return affected rows as a result immediately after an insert operation is submitted. In Flink 1.14, the result is available when there are some data, but in Flink 1.15, the result would not be available until the job finishes.

We could fix this by not waiting the table results for inserts.

### Affects Version(s)

1.6.1

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by waywtdcc** [comment]
I think the flink engine completely uses the asynchronous mode, and it is wrong for the insert statement to return the jobid. In the offline scenario, it is still hoped that the block will end. I think it is possible to set both asynchronous and synchronous modes.

**Comment by weaksloth** [comment]
@waywtdcc I agree with you. In fact, although now @link3280  has removed `jobResult.await()`, I complied the latest version and found that the insert opeation block still existed.I tried flink1.14~flink1.16

**Comment by pan3793** [comment]
Emm... I have some questions

- what's the behavior of Flink SQL Client, and using Flink SQL Gateway?
- are you prefer to introduce a dedicated configuration(or reuse a flink configuration) to switch asynchronous and synchronous modes, or just bind them to streaming/batch mode?

**Comment by link3280** [comment]
I've noticed the problem is not completely fixed. The result iterator would still prevent Kyuubi from accessing the results until the job finishes. Thus I plan to refactor the result set to return job ids or static affected rows to avoid the problem.

However, if we want to keep the sync mode, we may need to introduce a new configuration option or reuse Flink's `table.dml-sync`.

**Comment by link3280** [comment]
> * what's the behavior of Flink SQL Client, and using Beeline connect to Flink SQL Gateway?

Actually, Flink SQL client doesn't use the affected rows and prints the job id via side output.

<img width="630" alt="截屏2023-03-20 17 01 33" src="https://user-images.githubusercontent.com/13482005/226292708-0e64c6f5-915f-4426-b437-228bd887340c.png">

**Comment by weaksloth** [comment]
Should we do what flink sql client does ?

**Comment by weaksloth** [comment]
@link3280 I did something ugly like this, and it worked for me.
```java
  private def runOperation(operation: Operation): Unit = {
    // FLINK-24461 executeOperation method changes the return type
    // from TableResult to TableResultInternal
    val executeOperation = DynMethods.builder("executeOperation")
      .impl(executor.getClass, classOf[String], classOf[Operation])
      .build(executor)
    val result = executeOperation.invoke[TableResult](sessionId, operation)
    jobId = result.getJobClient.asScala.map(_.getJobID)

    // return jobId when submit success and table.dml-sync is false
    if (operation.getClass == classOf[SinkModifyOperation]) {
      resultSet = ResultSet.builder
        .resultKind(ResultKind.SUCCESS_WITH_CONTENT)
        .columns(Column.physical("jobId", DataTypes.STRING()))
        .data(Array(Row.of(jobId.map(_.toHexString).getOrElse("null"))))
        .build
    } else {
      resultSet = ResultSet.fromTableResult(result)
    }
  }
```
After that, as you say, if I don't set `table.dml-sync` to `true`, the insert operation returns:
```shell
+-----------------------------------+
|               jobId               |
+-----------------------------------+
| e99e0bd310911fcd7a34842d7aca3e31  |
+-----------------------------------+
1 row selected (0.056 seconds)
```
And if I use `set table.dml-sync=true;` in client, the insert operation will be blocked.
