### ISSUE TITLE
[Bug] Restarting NodeManager Where Spark Driver Runs When Executing Statement Cause Beeline Hang 

### ISSUE THREAD

**Issue by risyomei** [apache/kyuubi#4457]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

When executing a statement using Spark on YARN Cluster mode, if you restart the NodeManger when a Statement is executing, the beeline will hang.

It's similar to the issue [#647 Kill yarn app when executing statement cause beeline hang](https://github.com/apache/kyuubi/issues/647), but different in the way that:
- Restarting a NodeManager that runs Spark Driver (SparkSQLEngine) does NOT throw any exception.

And the `KyuubiSyncThriftClient` will then just hang and wait forever.
https://github.com/apache/kyuubi/blob/43309b86f1997b028e8fde5cb4e6449d818f4f73/kyuubi-server/src/main/scala/org/apache/kyuubi/operation/ExecuteStatement.scala#L104

Possible Workaround:
This issue can be alleviated by enabling `kyuubi.session.engine.request.timeout`.
When enabling it, the `KyuubiSyncThriftClient` will throw a `java.net.SocketTimeoutException: Read timed out`, and the exception can be handled properly by [[KYUUBI #647] Capture exceptions in async ExecuteStatement](https://github.com/apache/kyuubi/pull/646).

However, the `kyuubi.session.engine.request.timeout` was deleted by https://github.com/apache/kyuubi/pull/2948, and this is not possible anymore after 1.6.0

Possible Solutions:
1. Let Alive Probe deregister the Engine.
3. After step 1 is completed. Let the client handle the Engine deregister event.

What do you think?

### Affects Version(s)

master, 1.6.1-incubating

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by yaooqinn** [comment]
> Let Alive Probe deregister the Engine.

Does itself work fine in such a case

**Comment by turboFei** [comment]
> > Let Alive Probe deregister the Engine.
> 
> Does itself work fine in such a case

For alive probe session, there is socket timeout.

**Comment by risyomei** [comment]
@yaooqinn @turboFei 
Thank you for your comment.

> For alive probe session, there is socket timeout.

Yes, exactly, the timeout is the same with `kyuubi.session.engine.alive.probe.interval`
https://github.com/apache/kyuubi/blob/cc4ec5a5d5c9ec5e9699acf8d6c0e195e439b7b6/kyuubi-server/src/main/scala/org/apache/kyuubi/client/KyuubiSyncThriftClient.scala#L466-L471

**Comment by risyomei** [comment]
@turboFei @yaooqinn 
Do you think it's reasonable to add something like `protocol.getTransport().close()` after the `shutdownAsyncRequestExecutor()` in `startEngineAliveProbe()`.

https://github.com/apache/kyuubi/blob/3d65f2711faa5dc9173130557e2d33adab04b5c7/kyuubi-
server/src/main/scala/org/apache/kyuubi/client/KyuubiSyncThriftClient.scala#L110-L112

After adding this thrift client connection can be closed. It should be okay because the engine is dead anyway.
What do you think?

**Comment by turboFei** [comment]
> @turboFei @yaooqinn Do you think it's reasonable to add something like `protocol.getTransport().close()` after the `shutdownAsyncRequestExecutor()` in `startEngineAliveProbe()`.
> 
> https://github.com/apache/kyuubi/blob/3d65f2711faa5dc9173130557e2d33adab04b5c7/kyuubi-server/src/main/scala/org/apache/kyuubi/client/KyuubiSyncThriftClient.scala#L110-L112
> 
> After adding this thrift client connection can be closed. It should be okay because the engine is dead anyway. What do you think?

Thanks @risyomei 
It sounds good if the `kyuubi.session.engine.alive.timeout` is reasonable.

**Comment by risyomei** [comment]
@turboFei 
Thank you for your comment!
I will implement a PR based on this logic.

**Comment by risyomei** [comment]
Closing this issue as #4480 resolved it.
