### ISSUE TITLE
[Improvement] In the SparkBatchProcessBuilder, call super.clusterManager() when batchConf does not have spark.master

### ISSUE THREAD

**Issue by minyk** [apache/kyuubi#4496]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

currently, if batchConf does not have `spark.master`, find master conf from `defaultMaster`: 
https://github.com/apache/kyuubi/blob/f420238f4f171bab9a04860c5cf7f6b2181621ec/kyuubi-server/src/main/scala/org/apache/kyuubi/engine/spark/SparkBatchProcessBuilder.scala#L80

But `defaultMaster` finds config from the file directly, it passes spark configurations from the `kyuubi-defaults.conf`. 

### How should we improve?

if we just call `super.clusterManager()` instead of `defaultMaster`, we can search it from current session config and then if missing, find master from the `spark-defaults.conf` file.

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
Look reasonable, please go ahead to send PR to fix it.
