### ISSUE TITLE
[Bug] [Kyuubi-hive-beeline] Using Beeline with -i run sql faild

### ISSUE THREAD

**Issue by thomasg19930417** [apache/kyuubi#4508]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

when using beeline  with -i , Enter will trigger the execution of sql.
I added some logs to the code and found that the content read in the handleMultiLineCmd is empty at this time. According to the context code, I suspect that the consoleReader refers to FileInputStream when the - i parameter is used. Therefore, I added the following changes here and found that it can solve the current problem

```patch
+ if(beeLine.getOpts().getInitFiles() !=  null) {
+   beeLine.setConsoleReader(
+     new ConsoleReader(beeLine.getInputStream(), beeLine.getErrorStream()));
+ }
```
![image](https://user-images.githubusercontent.com/20243868/224956881-9e7f891f-078a-45fd-ab88-482aef48c3e5.png)

### Affects Version(s)

1.7.0 以及以下版本

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
@thomasg19930417 in this case, better to send PR directly, so that reviewers can see your changes and the CI will check if your change breaks something.

**Comment by thomasg19930417** [comment]
> @thomasg19930417 in this case, better to send PR directly, so that reviewers can see your changes and the CI will check if your change breaks something.

Ok, I will submit PR later
