### ISSUE TITLE
[Improvement] Support to limit some user to make connection

### ISSUE THREAD

**Issue by turboFei** [apache/kyuubi#4540]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

It is helpful, sometimes we need to add some user into blacklist.

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by lordk911** [comment]
Sometimes make sure some user can only connect to kyuubi from special hosts is also helpful, just like mysql. e.g. a BI system user may have a lot of select privilege, this kind of user should only active on the BI system host machines.

**Comment by turboFei** [comment]
Yes，would you like to help on this？
@lordk911

**Comment by goldwater2019** [comment]
Hi, I'd like to. @turboFei Please assign this to me. By the way, is it feasible or prefered to setup blocklist in kyuubi-defaults.conf?

**Comment by turboFei** [comment]
Sure @goldwater2019

**Comment by turboFei** [comment]
https://github.com/apache/kyuubi/pull/4360
Fyi，you can reload the conf.

**Comment by 666fishsun** [comment]
@turboFei hello~ may I have the chance to be assigned this issue? It seems @goldwater2019 no response.

**Comment by turboFei** [comment]
thanks @666fishsun , assigned

**Comment by zhuyaogai** [comment]
@turboFei @pan3793 hi, I'm new to kyuubi, but I really want to be involved, could you assign this issue for me? I will submit the PR as soon as possible. And it seems @666fishsun no response.

**Comment by turboFei** [comment]
sure, thanks @zhuyaogai
