### ISSUE TITLE
[Bug]Run Kyuubi Server in local IDE, will create `metrics` dir which should be add to gitignore

### ISSUE THREAD

**Issue by zwangsheng** [apache/kyuubi#4546]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

When run kyuubi server in local IDE, kyuubi server will create `metrics` for store kyuubi server's metrics.

Run `git status` show 
```log
未跟踪的文件:
  （使用 "git add <文件>..." 以包含要提交的内容）
        metrics/
```

Found in `.gitignore`
```
metrics/report.json
metrics/.report.json.crc
```

### Affects Version(s)

master

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by Z1Wu** [comment]
This modification will result in all folder whose name is `metrics` being ignored.

```
# for example, a normal metrics package  for spark-engine will be ignored due to this change
externals/kyuubi-spark-sql-engine/src/main/scala/org/apache/spark/kyuubi/metrics/
```

if we want to ignore `$repo_root/metrics` created by local IDE, maybe we could change gitignore like this :

```
# gitignore after
/metrics/

# gitignore before 
metrics/
```

**Comment by pan3793** [comment]
the metrics created in working dir by default, what will happen if run test in IDEA?

**Comment by zwangsheng** [comment]
Hi @Z1Wu , i try test in my local with following command:
1. modify class under `org.apache.kyuubi.metrics`
2. run `git status`

And output look fine to our expection.

![截屏2024-01-23 12 01 29](https://github.com/apache/kyuubi/assets/52876270/9c3bebe4-01ec-4138-989f-bb3a4b6d245f)

**Comment by pan3793** [comment]
@zwangsheng all changes will be identified if you touch a git-tracked file, I suppose creating a new file under the `metrics` folder will be ignored, and `git add -f <new_file>` must be used then

**Comment by zwangsheng** [comment]
Yes, i tried touch a file under metrics package, seems it has not been tracked. @Z1Wu Thanks for catching this. Would you like to raise a PR to fix this?
