### ISSUE TITLE
[Bug]  The source sql file causes the session to exit directly. When the last line of the sql file is empty

### ISSUE THREAD

**Issue by thomasg19930417** [apache/kyuubi#4550]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

The source sql file causes the session to exit directly. When the last line of the sql file is empty
![image](https://user-images.githubusercontent.com/20243868/225867817-35f1bca5-a663-43d1-b16c-c1ce36345dfb.png)

![image](https://user-images.githubusercontent.com/20243868/225868575-b8001ae7-f494-4087-b6fb-1f267611a8c5.png)

### Affects Version(s)

1.7.0

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by Kiss736921** [comment]
Hi, I'd like to solve this problem. @pan3793 Please assign this to me. Thanks.

**Comment by thomasg19930417** [comment]
@Kiss736921  Hi , Do you probably know where the problem is now, I haven't had time to find the problem here
