### ISSUE TITLE
[Bug] Spark lineage event did not post to JsonLoggingEventHandler

### ISSUE THREAD

**Issue by lordk911** [apache/kyuubi#4551]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

env: spark3.2.3、kyuubi1.7.0、kyuubi-spark-lineage_2.12-1.8.0-SNAPSHOT(buid from master)

I've follow the doc https://kyuubi.readthedocs.io/en/v1.7.0/extensions/engines/spark/lineage.html to config queryExecutionListeners、kyuubi.engine.event.loggers

after execute a sql statment: `create table test.table2 select * from test.table1` which is a CreateDataSourceTableAsSelectCommand
I can see engine、session、spark_operation dir under the default location of json log but there is no operation_lineage dir

Also I've try to remote debug , when the sql statment begin and finsh , the code can go to JsonLoggingEventHandler’s apply method and the event log will write to logfile under /tmp/kyuubi/events/spark_operation/day=20230317 . The code also can go to SparkOperationLineageQueryExecutionListener's onSuccess method , but after that code not go to JsonLoggingEventHandler’s apply method.

Is this because queryExecutionListener will not regist to SparkContext LiveListenerBus by default?

https://github.com/apache/kyuubi/blob/f1eb449c42b820b8ad3f4d388bb6320acf70bb1b/extensions/spark/kyuubi-spark-lineage/src/main/scala/org/apache/spark/kyuubi/lineage/SparkContextHelper.scala#L32

### Affects Version(s)

master

### Kyuubi Server Configurations

```yaml
kyuubi-defaults.conf:
kyuubi.zookeeper.embedded.port 2189
kyuubi.zookeeper.embedded.client.port 2189
kyuubi.engine.event.loggers JSON
```

### Kyuubi Engine Configurations

```yaml
spark-defaults.conf: 
spark.sql.queryExecutionListeners org.apache.kyuubi.plugin.lineage.SparkOperationLineageQueryExecutionListener
```

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by thomasg19930417** [comment]
@lordk911 
Can you see if this PR can be resolved? It seems that this PR has not been merged
https://github.com/apache/kyuubi/pull/3919/files#diff -4443b863a4ef04cc463082b2947ef050870b5e4bbd4e0d273cafbbc7e7bca019

**Comment by lordk911** [comment]
@pan3793 will you take a look at this issue please?

**Comment by pan3793** [comment]
@thomasg19930417 is right, it requires #3919

**Comment by lordk911** [comment]
> @thomasg19930417 is right, it requires #3919

close due to [#3919](https://github.com/apache/kyuubi/pull/3919)
