### ISSUE TITLE
[Improvement] Multi Arch build for ARM Support in Docker Hub

### ISSUE THREAD

**Issue by phyyou** [apache/kyuubi#4576]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Sorry, I'm late for busy.

Based on This [Discussion](https://github.com/apache/kyuubi/discussions/4487)

> Hi, I would like to request a new feature that provides support for ARM-based images Apache Kyuubi.
Currently, in the [Docker Hub](https://hub.docker.com/r/apache/kyuubi/tags) only provides images for x86-based architectures.

> Have you any plan of ARM architecture Image support?

ARM support at docker hub

### How should we improve?

Update [.github/workflows/publish-snapshot-docker.yml](https://github.com/apache/kyuubi/blob/824aba60708c0973ee638eeb97d296e2f8dc737e/.github/workflows/publish-snapshot-docker.yml)

I'm already have commit that implements.
https://github.com/phyyou/kyuubi/tree/feat/buildx-at-docker-hub-snapshot

https://github.com/apache/kyuubi/pull/4577

However, I think need change https://github.com/apache/kyuubi-docker this repo also for fully improve and support arm image at docker hub

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by yaooqinn** [comment]
Well done! 👍
