### ISSUE TITLE
[FEATURE] Support limit maximum scan file size

### ISSUE THREAD

**Issue by wForget** [apache/kyuubi#4641]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

I want to reject large queries by limiting the size of scanned files.

### Motivation

When using a shared engine, large queries take up more resources and block other queries.

### Describe the solution

Refer to the implementation of `maxPartitions` in watchdog

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by bowenliang123** [comment]
Nice work on this rule for maximum scanned file size.
Is it possible to promote this feature for limiting the total size of the data which is about to be written? @wForget
