### ISSUE TITLE
[Improvement] LogDivertAppender supports reading RollingFileAppender pattern

### ISSUE THREAD

**Issue by cxzl25** [apache/kyuubi#4650]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Now `Log4j12DivertAppender` and `Log4j2DivertAppender` will use the default pattern if there is no `ConsoleAppender` configured in the root logger.
We can support `RollingFileAppender`, and the user log format is consistent with server or engine.

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [X] No. I cannot submit a PR at this time.

**Comment by cxzl25** [comment]
Can you help fix this? @lsm1

**Comment by lsm1** [comment]
Sure, please assign to me
