### ISSUE TITLE
:arrow_up: Upgrade Apache Ranger from 2.3.0 to 2.4.0

### ISSUE THREAD

**Issue by yaooqinn** [apache/kyuubi#4651]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Why do we need to upgrade this artifact?

Regular Updates

### Artifact Name

https://mvnrepository.com/search?q=ranger-plugins-common

### Target Version

2.4.0

### Notable Changes

https://cwiki.apache.org/confluence/display/RANGER/Apache+Ranger+2.4.0+-+Release+Notes

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [X] No. I cannot submit a PR at this time.

**Comment by bowenliang123** [comment]
Bumping Ranger to 2.4.0 solely fails 20 of all tests.
```
  org.apache.kyuubi.plugin.spark.authz.AccessControlException: Permission denied: user [bob] does not have [select] privilege on [default/src/key]
```

Please consider reopening #4585 to solve conflicts in overlapping IDs and resources in the policy file. All tests pass with new generated policy file in #4585 as it merges duplicate policies.

**Comment by pan3793** [comment]
Closed via https://github.com/apache/kyuubi/pull/4675

**Comment by bowenliang123** [comment]
Thanks for closing this issue for me.
