### ISSUE TITLE
:arrow_up: Upgrade Hadoop from 3.3.4 to 3.3.5

### ISSUE THREAD

**Issue by yaooqinn** [apache/kyuubi#4652]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Why do we need to upgrade this artifact?

Bugfixes

### Artifact Name

https://mvnrepository.com/search?q=hadoop-client-api

### Target Version

3.3.5

### Notable Changes

https://hadoop.apache.org/docs/r3.3.5/hadoop-project-dist/hadoop-common/release/3.3.5/RELEASENOTES.3.3.5.html

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [X] No. I cannot submit a PR at this time.

**Comment by huapan123456** [comment]
@yaooqinn hello~, I  want to do this, can you asign it to me ? and which branch I will merge ?

**Comment by pan3793** [comment]
@huapan123456 please send PR directly, and target to `master`
