### ISSUE TITLE
Upgrade Spark from 3.2.3 to 3.2.4

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#4712]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Why do we need to upgrade this artifact?

Regular Updates

### Target Version

3.2.4

### Notable Changes

https://spark.apache.org/news/spark-3-2-4-released.html

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by anurag-rajawat** [comment]
Hi @pan3793
Do we need to upgrade spark version in this profile?
https://github.com/apache/kyuubi/blob/db46b5b320ffc3e58f84a0c3bb0d113783b9612b/pom.xml#L2333-L2334

**Comment by pan3793** [comment]
@anurag-rajawat please refer to this PR https://github.com/apache/kyuubi/pull/3825

**Comment by anurag-rajawat** [comment]
@pan3793 I got it. 
May I work on this one?

**Comment by pan3793** [comment]
@anurag-rajawat of course, please send PR directly
