### ISSUE TITLE
[Bug] PartialGroupNameException when don't set username.

### ISSUE THREAD

**Issue by felixzh2020** [apache/kyuubi#4736]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

run cmd:
 ./beeline -u 'jdbc:hive2://felixzh:2181,felixzh1:2181,felixzh2:2181/default;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=kyuubi;#flink.yarn.application.id=application_1679471682027_0006'

shell exception: 
![image](https://user-images.githubusercontent.com/16359007/233248341-3d910f4b-5fcc-4927-9ba0-9fde39cfbe01.png)

### Affects Version(s)

1.7.0

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
it's known issue, got fixed in https://github.com/apache/kyuubi/pull/4527

**Comment by felixzh2020** [comment]
ok
