### ISSUE TITLE
Create EngineSpace Root Directory ahead

### ISSUE THREAD

**Issue by yaooqinn** [apache/kyuubi#474]
### 1. Describe the feature

When the ServerSpace is specified with `kyuubi_server`, the corresponding EngineSpace Roots will be `kyuubi_server_USER`, `kyuubi_server_CONNECTION` and `kyuubi_server_SERVER`, and these EngineSpace Roots should be preset with proper ACLs for all engine to write their data

### 2. Motivation

If these  EngineSpace Roots  exist with improper ACLs, it's too late to detect them at engine side

**Comment by pan3793** [comment]
postpone to 1.8 since it's not a critical issue and has not been started yet.
