### ISSUE TITLE
[Improvement] KyuubiConf.unset should not log deprecation warning

### ISSUE THREAD

**Issue by cxzl25** [apache/kyuubi#4752]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

https://github.com/apache/kyuubi/blob/06dd7d3754ee210f7744e46030965a6f5df1953b/kyuubi-common/src/main/scala/org/apache/kyuubi/config/KyuubiConf.scala#L104-L109

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [X] No. I cannot submit a PR at this time.

**Comment by cxzl25** [comment]
Can you help solve this problem? @lsm1

**Comment by lsm1** [comment]
Sure, please assign to me
