### ISSUE TITLE
[Bug] Compilation fails with `AdminResourceSuite` on branch 1.7

### ISSUE THREAD

**Issue by HaoYang670** [apache/kyuubi#4770]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

https://github.com/apache/kyuubi/pull/4740#issuecomment-1521342224

### Affects Version(s)

1.7

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [X] No. I cannot submit a PR at this time.

**Comment by bowenliang123** [comment]
Closing this issue as PR https://github.com/apache/kyuubi/pull/4771 merged.
