### ISSUE TITLE
[Bug] High CPU Usage When Concurrency is High

### ISSUE THREAD

**Issue by risyomei** [apache/kyuubi#4825]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

I am trying to replace the HiveServer2 with Kyuubi for my production environment with more than 3500 NodeManagers running.

During the busiest periods, the HiveServer2 has to handle roughly 400 new connections.
```
$ ls hadoop-cmf-hive_on_tez-HIVESERVER2-<hostname>.log.out* | xargs -I{}  bash -c "grep 'Session opened, SessionHandle' {} |  cut -b-16 | uniq -c" |  sort -n | tail -n10
    169 2022-10-26 16:38
    174 2022-10-26 13:52
    215 2022-10-26 13:49
    218 2022-10-26 13:48
    227 2022-10-26 13:47
    227 2022-10-26 13:51
    228 2022-10-26 13:50
    283 2022-10-26 16:37
    301 2022-10-26 13:46
    379 2022-10-26 13:45
```
While I am running scalability test for KyuubiServer, I found that the CPU loadaverage is quite high even with much lower concurrency.

E.g. this the loadaverage with 20 connections / min. By the way, the HiveServer2 with exactly the same hardware can handle 300+ connections/min with no significant CPU usage. According to our calculation, we need 60+ Kyuubi servers to handle the workload which can be easily handled by 4 HiveServers
```
top - 16:41:41 up 23 days, 59 min,  3 users,  load average: 27.49, 26.43, 22.72
Tasks: 178 total,   1 running, 177 sleeping,   0 stopped,   0 zombie                                                          %Cpu(s): 75.1 us,  4.7 sy,  0.0 ni, 19.9 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 st
KiB Mem : 32779588 total, 18658312 free, 11246896 used,  2874380 buff/cache                                                   KiB Swap:  4194300 total,  4088680 free,   105620 used. 21308144 avail Mem

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 46732 kyuubi    20   0   12.3g 624740  53860 S  59.5  1.9   0:13.21 java                                                      46762 kyuubi    20   0   12.1g 472876  53864 S  54.8  1.4   0:13.00 java
 46886 kyuubi    20   0   12.0g 545456  53872 S  48.8  1.7   0:13.56 java                                                      47177 kyuubi    20   0   12.3g 492448  53872 S  45.2  1.5   0:12.88 java
 47077 kyuubi    20   0   12.2g 498132  53868 S  40.5  1.5   0:12.49 java                                                      47637 kyuubi    20   0   11.4g 541136  53860 S  38.9  1.7   0:10.22 java
 46979 kyuubi    20   0   12.3g 621928  53864 S  38.5  1.9   0:11.84 java                                                      47513 kyuubi    20   0   12.1g 467256  53864 S  37.9  1.4   0:11.56 java
 46918 kyuubi    20   0   12.0g 480620  53864 S  37.5  1.5   0:12.18 java
 47766 kyuubi    20   0   12.0g 495616  53844 S  31.6  1.5   0:10.80 java
 47606 kyuubi    20   0   12.0g 441112  53860 S  30.9  1.3   0:10.10 java                                                      46843 kyuubi    20   0   12.2g 491684  53860 S  21.3  1.5   0:11.38 java
 47244 kyuubi    20   0   11.9g 410096  53864 S  21.3  1.3   0:10.75 java                                                      27799 root      20   0  115860   3904   1104 S  18.9  0.0 403:14.08 bash
 47359 kyuubi    20   0   12.1g 414828  53864 S  16.6  1.3   0:10.50 java                                                      47317 kyuubi    20   0   12.1g 446280  53860 S  16.3  1.4   0:10.62 java
 47432 kyuubi    20   0   12.0g 432704  53856 S  15.6  1.3   0:10.86 java                                                      47131 kyuubi    20   0   11.8g 510692  53860 S  14.6  1.6   0:10.84 java
 47280 kyuubi    20   0   11.8g 445524  53856 S  13.3  1.4   0:10.23 java 
```
One of the largest reason is that the Kyuubi will need to use ProcessBuilder to trigger spark-submit command, and this procedure is very time and CPU consuming. Just my two cents, we may be able to use YARN REST-API, Spark Connect, or other way to reduce the CPU usage.

I am wondering If there is anything that we can change to improve this situation? 
Or, do you have any idea on how to configure the KyuubiServer to support such amount of traffic?

### Affects Version(s)

master/1.7.0/1.7.1

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
Combine using `spark.submit.deployMode=cluster` and `kyuubi.session.engine.startup.waitCompletion=false` should significantly reduce the load.

**Comment by risyomei** [comment]
@pan3793 
Thank you very much for your fast response, these configurations are already set.
Moreover, we have uploaded all the jars to the HDFS and set `spark.yarn.archive` to minimize the cost of spark-submit.

**Comment by yaooqinn** [comment]
Thanks @risyomei for the useful verification.


To be honest, this test case hits the worst part of Kyuubi's design.

There are two types of kyuubi connections, one is heavy and another is lightweight. https://kyuubi.readthedocs.io/en/master/overview/architecture.html#architecture-overview

The lightweight one will reuse the backend engine with no spark-submit and it's the same as HiveServer2 connections.

The only heavyweight case is when there is no backend engine in the user’s shared domain, which usually happens when the user is connecting for the first time or has not connected for a long time. And this is just a one-time cost.


Thoughts for heavyweight connections are always welcome

**Comment by risyomei** [comment]
@pan3793 
Thank you very much for your suggestion. 
Unfortunately, disabling JIT seems to be getting things worse.
The loadaverage increased from 20 to 60.

I have done so by setting the following config in the `spark-env.sh`. Maybe I am disabling the JIT with a wrong way.
```
SPARK_SUBMIT_OPTS="$SPARK_SUBMIT_OPTS -Djava.compiler=NONE"
```

**Comment by risyomei** [comment]
@yaooqinn 
Thank you very much for your comment. 
We are aware of the lightweight connection but we may not able to take advantage of that because our main workload is ETL and we needed the seperate Spark driver for resource segregation.

> Thoughts for heavyweight connections are always welcome
Our team will be testing some approaches and get back to you here.

**Comment by yaooqinn** [comment]
@risyomei, thanks for the information and efforts.

BTW, did you identify where the hotspots occurred? How much did you gain when using remote spark archives?

**Comment by pan3793** [comment]
> Unfortunately, disabling JIT seems to be getting things worse.
> The loadaverage increased from 20 to 60.

How long will your `spark-submit` process live? The suggestion suppose `spark-submit` lives in a short time (usually < 30s)

**Comment by risyomei** [comment]
@yaooqinn 
Thank you for the follow up.
I am not sure how to identify the hotspots, please allow me some time to investigate it.

> How much did you gain when using remote spark archives?

This will decrease roughly 5 seconds from the spark-submit time. However, it doesn't seems to contribute to lower the CPU loadaverage significantly as we don't see obvious change in loadaverage

@pan3793 
The `spark-submit` process lives for roughly 37 seconds (wall time) by default, and that value increase to 44 seconds when JIT is disabled.

By the way, the CPU time were 12 and 20 seconds respectively. These value can be gathered from `cpuacct.usage`.
The result shows when JIT is disabled, the spark-submit process seems to be using more CPU resources.

**Comment by risyomei** [comment]
Hi, forks
Before modifying the Kyuubi code, I have tried two implementations with `SparkLauncher` and `InProcessLauncher` for submitting spark application.

Here, I have just tried executing 20 SparkPi jobs with `ExecutorService`, but I guess it will show the same tendency when submitting the SparkSQLEngine.

I have compared CPU time of these implementation with the `ProcessBuilder`, which is used in Kyuubi.
 
|| `ProcessBuilder` | `SparkLauncher` | `InProcessLauncher` |
|- | - | - | - |
| Code Snippet | [MyProcessBuilder.java](https://github.com/risyomei/java-spark-submit/blob/main/src/main/java/com/jpz3032/MyProcessBuilder.java) | [MySparkLauncher.java](https://github.com/risyomei/java-spark-submit/blob/main/src/main/java/com/jpz3032/MySparkLauncher.java) | [MyInProcessLauncher.java](https://github.com/risyomei/java-spark-submit/blob/main/src/main/java/com/jpz3032/MyInProcessLauncher.java) |
|CPU time in Sec<br/>(3 runs) |  547.04 <br/>(549.40, 558.06, 551.50) | 569.41 <br/>(569.35, 563.49, 575.38) | 86.42 <br/>(86.49, 85.90, 86.87) |
| Notes | - `spark-submit` are started as new processes.<br/>- The closet implementation with the current Kyuubi code | - `spark-submit` are started as new processes. <br/> - Consumes more CPU than `ProcessBuilder`<br/>  | - `spark-submit` are started within the same process as the caller.<br/>- Consumes much less `<br/>- Not suitable for client mode<br/>- Worse separation |

What's your opinion about the `InProcessLauncher`-based approach? Do you think this can be implemented as an option for heavyweight connection under client mode?

**Comment by yaooqinn** [comment]
The Spark community has been less supportive of InProcessLauncher and SparkLauncher than `spark-submit`, which results in more bugs in this area. `spark-submit` is the only official PUBLIC API for launching Spark apps so far. And as you said, it cannot work with client mode. Also, including `spark-launcher` kyuubi server's classpath also complicates things, which may lead to dependencies from other engines being mixed in.

I suggest that we make our ProcessBuilder an SPI for building custom engine launchers.

**Comment by risyomei** [comment]
Hi, @yaooqinn 
Thank you very much for your comment.

I agree with the facts you stated and I think it's reasonable to keep using ProcessBuilder for now.

However, we still plan to implement an internal patch that will use of `InProcessLauncher` when the backend engine is SPARK_SQL and the deploy mode is set to cluster. 

For the time being, I will close this ticket. However, if you or anyone else is interested, I would be happy to share further details, including the code and evaluation results, in this thread.
