### ISSUE TITLE
:memo: Fix key features section of high availability page

### ISSUE THREAD

**Issue by mans2singh** [apache/kyuubi#4863]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What type of changes will we make to the documentation?

Typo, layout, grammar, spelling, punctuation errors, etc.

### Affects Version(s)

master

### Improving the documentation

The [high availability guide](https://kyuubi.readthedocs.io/en/master/deployment/high_availability_guide.html#key-benefits) states <code>Kyuubi server supports **stop** gracefully.</code> can be rephrased to <code>Kyuubi server supports **stopping** gracefully.</code> 

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by mans2singh** [comment]
PR submitted - https://github.com/apache/kyuubi/pull/4864

**Comment by pan3793** [comment]
Fixed in https://github.com/apache/kyuubi/pull/4864

**Comment by mans2singh** [comment]
Thanks @pan3793 for your review.
