### ISSUE TITLE
[Improvement] Create `kyuubi-util` and `kyuubi-util-scala` modules

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#4870]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Some modules do not depend on `kyuubi-common` since they are designed to be independent w/ Kyuubi server/engine, this cause some code duplication in whole codebase.

### How should we improve?

Create the following  modules

- `kyuubi-util` only depends on JDK and `slf4j-api`
- `kyuubi-util-scala` only depends on `kyuubi-util` and `scala-library`

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by bowenliang123** [comment]
+1
