### ISSUE TITLE
[TEST] Flaky test BackendServiceMetricSuite

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#4876]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What kind of test improve?

- [X] Fix flaky tests.
- [ ] Fix bug in tests.
- [ ] Increase test coverage.
- [ ] Other kinds of test improve.

### Describe the issues of the existing tests or improvements for new tests

```
BackendServiceMetricSuite:
- backend service metric test *** FAILED ***
  The code passed to eventually never returned normally. Attempted 70 times over 1.0013718745666667 minutes. Last failure message: 0 was not greater than 0. (BackendServiceMetricSuite.scala:66)
```

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [X] No. I cannot submit a PR at this time.

**Comment by lightning-L** [comment]
The test failed at:
```
assert(timer.get(BS_OPEN_SESSION).get("min").asInt() > 0)
```
It seems that the value is 0. So test failed with message: `0 was not greater than 0`.

Kyuubi server uses `io.dropwizard.metrics` to implement its metrics system. And in the test, we are getting values from `org.apache.kyuubi.metrics.JsonReporterService`.

The timer data is updated as Nano seconds. (`org.apache.kyuubi.metrics.MetricsSystem`)
```
  def timerTracing[T](name: String)(f: => T): T = {
    val startTime = System.nanoTime()
    try {
      f
    } finally {
      tracing(_.updateTimer(name, System.nanoTime() - startTime, TimeUnit.NANOSECONDS))
    }
  }
```

There is such code in `JsonReporterService`, so we know that the unit in the json metrics report is Milli seconds.
```
private val jsonMapper = new ObjectMapper().registerModule(
    new MetricsModule(TimeUnit.SECONDS, TimeUnit.MILLISECONDS, false))
```

So there must be a conversion logic to convert the duration from nano seconds to milli seconds. 
After debugging into MetricsModule, I think I have found the root cause for the flaky test.

Below is the logic for the time unit conversion:
<img width="902" alt="image" src="https://github.com/apache/kyuubi/assets/21362040/5ce1d251-5d7c-4875-b488-82ea2024f4ad">
```
json.writeNumberField("min", (double)snapshot.getMin() * this.durationFactor);
```
First, it will get the original value, which is nano seconds.
Then it will multiply a duration factor. For milli seconds, it will be `1/1000000`.
<img width="761" alt="image" src="https://github.com/apache/kyuubi/assets/21362040/d95c8019-74e1-496d-843d-86316c48717b">

For example, if the original time is 54788598(nano seconds), it will be converted to 54.
I have tested in my local environment, the time for opening session varies, usually takes about 50,000,000 ~ 200,000,000 nano seconds.
But there is possibility that it takes less than 1,000,000 nano seconds.
Let's say the value is 500,000 nano seconds, so it will be converted to 0.5 in the metrics json.
and `timer.get(BS_OPEN_SESSION).get("min").asInt()` will evaluates to 0.
so `assert(timer.get(BS_OPEN_SESSION).get("min").asInt() > 0)` failes.

**Comment by lightning-L** [comment]
so my suggestion is to change from:
```
assert(timer.get(BS_OPEN_SESSION).get("min").asInt() > 0)
```
to
```
assert(timer.get(BS_OPEN_SESSION).get("min").asDouble() > 0)
```

<img width="825" alt="image" src="https://github.com/apache/kyuubi/assets/21362040/6f92ba88-f76e-46f0-b097-9a5da3e7cfff">

**Comment by huangzhir** [comment]
I have a question. Opening a Spark session is a very time-consuming process, taking several tens of seconds on my local machine. Why would there be values greater than 0 and less than 1 in this context?

**Comment by lightning-L** [comment]
> I have a question. Opening a Spark session is a very time-consuming process, taking several tens of seconds on my local machine. Why would there be values greater than 0 and less than 1 in this context?

for this test case (BackendServiceMetricSuite), it is opening KyuubiSession, not SparkSession.

**Comment by lightning-L** [comment]
@pan3793

**Comment by huangzhir** [comment]
> for this test case (BackendServiceMetricSuite), it is opening KyuubiSession, not SparkSession.

When KyuubiSession is first opened and if Spark Engine is being used, it will have to wait for the Spark Engine to be launched.  In the BackendServiceMetricSuite, the Spark Engine is used and the session is only opened once, so it will wait for the Spark Engine to be launched.

see
https://github.com/apache/kyuubi/blob/02b1a7d44f03a1ea7c2eaef5be463d622b85c004/kyuubi-server/src/main/scala/org/apache/kyuubi/session/KyuubiSessionImpl.scala#L116
https://github.com/apache/kyuubi/blob/02b1a7d44f03a1ea7c2eaef5be463d622b85c004/kyuubi-server/src/main/scala/org/apache/kyuubi/session/KyuubiSessionImpl.scala#L201

**Comment by lightning-L** [comment]
> > for this test case (BackendServiceMetricSuite), it is opening KyuubiSession, not SparkSession.
> 
> When KyuubiSession is first opened and if Spark Engine is being used, it will have to wait for the Spark Engine to be launched. In the BackendServiceMetricSuite, the Spark Engine is used and the session is only opened once, so it will wait for the Spark Engine to be launched.
> 
> see
> 
> https://github.com/apache/kyuubi/blob/02b1a7d44f03a1ea7c2eaef5be463d622b85c004/kyuubi-server/src/main/scala/org/apache/kyuubi/session/KyuubiSessionImpl.scala#L116
> 
> 
> https://github.com/apache/kyuubi/blob/02b1a7d44f03a1ea7c2eaef5be463d622b85c004/kyuubi-server/src/main/scala/org/apache/kyuubi/session/KyuubiSessionImpl.scala#L201

yes, you are right.
Let me dig deeper..

**Comment by lightning-L** [comment]
@huangzhir 
I checked the code again.
https://github.com/apache/kyuubi/blob/master/kyuubi-server/src/main/scala/org/apache/kyuubi/session/KyuubiSessionImpl.scala#L199
The `waitForEngineLaunched()` is executed when operation is not LaunchEngine.

And LaunchEngine is running asynchronously by default.
https://github.com/apache/kyuubi/blob/master/kyuubi-server/src/main/scala/org/apache/kyuubi/operation/LaunchEngine.scala#L65

And this is the unit-test.log from my local, see `======test:` key word I have added locally for debugging:
```
22:14:52.670 ScalaTest-run INFO BackendServiceMetricSuite: ======test: server started
22:14:52.702 ScalaTest-run-running-BackendServiceMetricSuite INFO BackendServiceMetricSuite:

===== TEST OUTPUT FOR o.a.k.server.BackendServiceMetricSuite: 'backend service metric test' =====

22:14:53.020 KyuubiTBinaryFrontendHandler-Pool: Thread-45 INFO KyuubiTBinaryFrontendService: Client protocol version: HIVE_CLI_SERVICE_PROTOCOL_V10
22:14:53.029 KyuubiTBinaryFrontendHandler-Pool: Thread-45 INFO KyuubiSessionManager: Opening session for tiliao@192.168.0.103
22:14:53.090 KyuubiTBinaryFrontendHandler-Pool: Thread-45 INFO OperationLog: Creating operation log file /Users/tiliao/Documents/Code/incubator-kyuubi/server_operation_logs/47af9c1f-e720-4c93-8531-b8cd1006fde6/b48c7bbe-04f4-443b-b8ba-0e5a3cb9d5e8
22:14:53.093 KyuubiTBinaryFrontendHandler-Pool: Thread-45 INFO KyuubiSessionManager: tiliao's session with SessionHandle [47af9c1f-e720-4c93-8531-b8cd1006fde6] is opened, current opening sessions 1
22:14:53.093 KyuubiSessionManager-exec-pool: Thread-46 INFO LaunchEngine: Processing tiliao's query[b48c7bbe-04f4-443b-b8ba-0e5a3cb9d5e8]: PENDING_STATE -> RUNNING_STATE, statement:
LaunchEngine
22:14:53.094 KyuubiTBinaryFrontendHandler-Pool: Thread-45 INFO MetricsSystem: =====test: update timer, key: kyuubi.backend_service.open_session, duration: 64872263, unit: NANOSECONDS
22:14:53.112 KyuubiSessionManager-exec-pool: Thread-46 INFO CuratorFrameworkImpl: Starting
22:14:53.112 KyuubiSessionManager-exec-pool: Thread-46 INFO ZooKeeper: Initiating client connection, connectString=192.168.0.103:60669 sessionTimeout=60000 watcher=org.apache.kyuubi.shaded.curator.ConnectionState@7a8912ab
22:14:53.115 KyuubiSessionManager-exec-pool: Thread-46-SendThread(192.168.0.103:60669) INFO ClientCnxn: Opening socket connection to server 192.168.0.103/192.168.0.103:60669. Will not attempt to authenticate using SASL (unknown error)
22:14:53.118 KyuubiSessionManager-exec-pool: Thread-46-SendThread(192.168.0.103:60669) INFO ClientCnxn: Socket connection established to 192.168.0.103/192.168.0.103:60669, initiating session
22:14:53.118 NIOServerCxn.Factory:/192.168.0.103:0 INFO NIOServerCnxnFactory: Accepted socket connection from /192.168.0.103:60739
22:14:53.119 NIOServerCxn.Factory:/192.168.0.103:0 INFO ZooKeeperServer: Client attempting to establish new session at /192.168.0.103:60739
22:14:53.124 ScalaTest-run-running-BackendServiceMetricSuite INFO KyuubiConnection: Starting to get launch engine log.
22:14:53.130 KyuubiSessionManager-exec-pool: Thread-46 INFO HadoopCredentialsManager: Scheduling renewal in 0 ms.
...
...
22:14:53.429 KyuubiSessionManager-exec-pool: Thread-46 INFO EngineRef: Launching engine:
/Users/tiliao/Documents/Software/spark-3.2.1-bin-hadoop2.7/bin/spark-submit \
        --class org.apache.kyuubi.engine.spark.SparkSQLEngine \
        --conf spark.hive.server2.thrift.resultset.default.fetch.size=1000 \
        --conf spark.kyuubi.client.ipAddress=127.0.0.1 \
        --conf spark.kyuubi.client.version=1.8.0-SNAPSHOT \
        --conf spark.kyuubi.engine.credentials=SERUUwAAAA== \
        --conf spark.kyuubi.engine.submit.time=1685888093401 \
        --conf spark.kyuubi.frontend.protocols=THRIFT_BINARY \
        --conf spark.kyuubi.ha.addresses=192.168.0.103:60669 \
        --conf spark.kyuubi.ha.engine.ref.id=47af9c1f-e720-4c93-8531-b8cd1006fde6 \
        --conf spark.kyuubi.ha.namespace=/kyuubi_1.8.0-SNAPSHOT_USER_SPARK_SQL/tiliao/default \
        --conf spark.kyuubi.ha.zookeeper.auth.type=NONE \
        --conf spark.kyuubi.ha.zookeeper.connection.retry.policy=ONE_TIME \
        --conf spark.kyuubi.metrics.json.interval=PT0.1S \
        --conf spark.kyuubi.metrics.json.location=/var/folders/hk/7j9sqdtn55j3cq_gv5qvp5pm39d49n/T/kyuubi-3969fed7-fa68-4fc3-b5ad-10c612223064 \
        --conf spark.kyuubi.metrics.reporters=JSON \
        --conf spark.kyuubi.server.ipAddress=192.168.0.103 \
        --conf spark.kyuubi.session.connection.url=192.168.0.103:60727 \
        --conf spark.kyuubi.session.engine.check.interval=PT1S \
        --conf spark.kyuubi.session.engine.idle.timeout=PT5S \
        --conf spark.kyuubi.session.real.user=tiliao \
        --conf spark.kyuubi.zookeeper.embedded.client.port=0 \
        --conf spark.kyuubi.zookeeper.embedded.data.dir=/var/folders/hk/7j9sqdtn55j3cq_gv5qvp5pm39d49n/T/kyuubi-308cd5b3-9142-4978-be3f-a4a4bdba10a1 \
        --conf spark.app.name=kyuubi_USER_SPARK_SQL_tiliao_default_47af9c1f-e720-4c93-8531-b8cd1006fde6 \
        --conf spark.kubernetes.driver.label.kyuubi-unique-tag=47af9c1f-e720-4c93-8531-b8cd1006fde6 \
        --conf spark.sql.catalogImplementation=in-memory \
        --conf spark.ui.enabled=false \
        --conf spark.yarn.tags=KYUUBI,47af9c1f-e720-4c93-8531-b8cd1006fde6 \
        --proxy-user tiliao /Users/tiliao/Documents/Code/incubator-kyuubi/externals/kyuubi-spark-sql-engine/target/kyuubi-spark-sql-engine_2.12-1.8.0-SNAPSHOT.jar
22:14:53.436 KyuubiSessionManager-exec-pool: Thread-46 INFO ProcBuilder: Logging to /var/folders/hk/7j9sqdtn55j3cq_gv5qvp5pm39d49n/T/tiliao-32142424-39a5-493c-8392-ef6705daa3b4/kyuubi-spark-sql-engine.log.0
22:14:58.163 KyuubiTBinaryFrontendHandler-Pool: Thread-45 INFO MetricsSystem: =====test: update timer, key: kyuubi.backend_service.get_operation_status, duration: 5002672658, unit: NANOSECONDS
22:14:58.242 KyuubiTBinaryFrontendHandler-Pool: Thread-45 INFO MetricsSystem: =====test: update timer, key: kyuubi.backend_service.fetch_results, duration: 29478618, unit: NANOSECONDS
```

**Comment by huangzhir** [comment]
> And LaunchEngine is running asynchronously by default.
> https://github.com/apache/kyuubi/blob/master/kyuubi-server/src/main/scala/org/apache/kyuubi/operation/LaunchEngine.scala#L65

LaunchEngine is running asynchronously by default, but op.getBackgroundHandle.get() is synchronous
https://github.com/apache/kyuubi/blob/cb689b66b1ed745a5e38dea37a2b0f1d9e7f1aca/kyuubi-server/src/main/scala/org/apache/kyuubi/session/KyuubiSessionImpl.scala#L220

**Comment by lightning-L** [comment]
> > And LaunchEngine is running asynchronously by default.
> > https://github.com/apache/kyuubi/blob/master/kyuubi-server/src/main/scala/org/apache/kyuubi/operation/LaunchEngine.scala#L65
> 
> LaunchEngine is running asynchronously by default, but op.getBackgroundHandle.get() is synchronous
> 
> https://github.com/apache/kyuubi/blob/cb689b66b1ed745a5e38dea37a2b0f1d9e7f1aca/kyuubi-server/src/main/scala/org/apache/kyuubi/session/KyuubiSessionImpl.scala#L220

during the execution of opening kyuubi session, `waitForEngineLaunched()` will not be executed.
