### ISSUE TITLE
[Improvement] Add a maven profile 'remote-debug' to ease unit test remote debugging

### ISSUE THREAD

**Issue by zhouyifan279** [apache/kyuubi#4906]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Add a maven profile 'debug' to ease unit test remote debugging

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
Close as completed
