### ISSUE TITLE
[Bug] [AUTHZ] Table owner undefied in Iceberg 1.3.0 on Spark 3.4

### ISSUE THREAD

**Issue by bowenliang123** [apache/kyuubi#4917]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Test Authz plugin with Iceberg 1.3.0 on Spark 3.4,
`mvn clean install -pl :kyuubi-spark-authz_2.12 -Pspark-3.4 -Dmaven.plugin.scalatest.exclude.tags=`

```
IcebergCatalogPrivilegesBuilderSuite:

- DropTable *** FAILED ***
  po.owner.isDefined was false (PrivilegesBuilderSuite.scala:77)
```

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [X] No. I cannot submit a PR at this time.

**Comment by bowenliang123** [comment]
cc @zhouyifan279

**Comment by zhouyifan279** [comment]
I will work on it.
