### ISSUE TITLE
Implement Kyuubi UDF in Flink engine

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#4938]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Kyuubi implemented several UDFs in Spark engine

- `kyuubi_version`
- `engine_name`
- `engine_id`
- `system_user`
- `session_user`

To make consistent, we should implement them in other engines as well

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [X] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
cc @link3280

**Comment by link3280** [comment]
LGTM. A minor issue I see is that these UDFs are all about metadata and thus could be executed locally in the engine, but as for Flink, we have to submit a job to execute them, which is less efficient.

**Comment by cxzl25** [comment]
```
current_database
current_catalog
```

org.apache.kyuubi.jdbc.hive.KyuubiConnection#getSchema
https://github.com/apache/kyuubi/blob/b10a8ef27d0d9256eddd17d1e8eba3464ea19f31/kyuubi-hive-jdbc/src/main/java/org/apache/kyuubi/jdbc/hive/KyuubiConnection.java#L1075-L1080

**Comment by link3280** [comment]
@pan3793 since `system_user` and `session_user` are reserved keywords in Flink, the functions are prefixed with `kyuubi_` to avoid conflicts.

**Comment by pan3793** [comment]
Does Flink support functions `system_user` and `session_user` natively?

**Comment by link3280** [comment]
No, but they're reserved for future usage :(
