### ISSUE TITLE
[Bug] Operation logs are unavailable with reload4j slf4j binding

### ISSUE THREAD

**Issue by touchida** [apache/kyuubi#4951]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Currently, operation logging supports the slf4j bindings of log4j 1 and log4j 2.
- https://github.com/apache/kyuubi/blob/06dd7d3/kyuubi-common/src/main/scala/org/apache/kyuubi/operation/log/LogDivertAppender.scala#L27-L34

In https://issues.apache.org/jira/browse/HADOOP-18088, Hadoop replaced log4j 1 with reload4j.
When a Spark SQL engine uses the reload4j slf4j binding from Hadoop, operation logs on the engine are not shown to a client, since `LogDivertAppender` is not initialized, as the following engine log indicates:
```
23/06/11 16:28:39 WARN log.LogDivertAppender: Unsupported SLF4J binding org.slf4j.impl.Reload4jLoggerFactory
```

In more details, we confirmed this issue happened when
- we used Spark SQL engine in YARN cluster deploy mode;
- we built Hadoop-free Spark 3.2.4, and provided the classpath of Hadoop in YARN cluster, whose version used reload4j, with `SPARK_DIST_CLASSPATH`.

Note
- We also confirmed this issue did not happen for Spark 3.2.4 built with Hadoop, since then the Spark jars contained the log4j 1 slf4j binding.
- We did not test, but it would not happen for Spark 3.3 and later, since Spark used log4j 2 (https://issues.apache.org/jira/browse/SPARK-37814).

### Affects Version(s)

master

### Kyuubi Engine Log Output

```logtalk
23/06/11 16:28:39 WARN log.LogDivertAppender: Unsupported SLF4J binding org.slf4j.impl.Reload4jLoggerFactory
```

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
@touchida Thanks for reporting this issue, seems we can simply treat reload4j as log4j12, right?

```patch
object Logging {
  ...
  private[kyuubi] def isLog4j12: Boolean = {
    // This distinguishes the log4j 1.2 binding, currently
    // org.slf4j.impl.Log4jLoggerFactory, from the log4j 2.0 binding, currently
    // org.apache.logging.slf4j.Log4jLoggerFactory
    "org.slf4j.impl.Log4jLoggerFactory"
-     .equals(LoggerFactory.getILoggerFactory.getClass.getName)
+     .equals(LoggerFactory.getILoggerFactory.getClass.getName) ||
+   "org.slf4j.impl.Reload4jLoggerFactory"
+     .equals(LoggerFactory.getILoggerFactory.getClass.getName)
  }
  ...
}
```

**Comment by touchida** [comment]
@pan3793 
Thanks for your comment!
Exactly, you're right.
We've confirmed that clients showed operation logs successfully after the patch was applied.

Let me send a PR today.

**Comment by pan3793** [comment]
@touchida glad to know it works, looking forward to your contribution :)
