### ISSUE TITLE
[Bug] Backport HIVE-19048: Initscript errors are ignored

### ISSUE THREAD

**Issue by turboFei** [apache/kyuubi#4961]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Backport HIVE-19048: Initscript errors are ignored

see https://issues.apache.org/jira/browse/HIVE-19048

https://github.com/apache/hive/commit/006bf8a1a49aabf9930744c977fb0b9c91a5ef6c 

### Affects Version(s)

1.7.1

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
Closed via https://github.com/apache/kyuubi/commit/01320c4c2f52ca7183e44e7803b8356df11baf00
