### ISSUE TITLE
[Bug] Engine with CONNECTION share level should be closed when KyuubiServer restart.

### ISSUE THREAD

**Issue by risyomei** [apache/kyuubi#4997]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

#### Overview
1. When a connection is established from a beeline to KyuubiServer, a Spark Application (specifically, `org.apache.kyuubi.engine.spark.SparkSQLEngine`) is submitted.

1. After the `SparkSQLEngine` is ready, the KyuubiServer will connect to the engine with KyuubiSyncThriftClient#createClient.

#### Issue
The problem arises when you restart or stop the KyuubiServer while:

1. the `SparkSQLEngine` is already accepted as YARN application (as verified from ResourceManager), and
2. The KyuubiServer is not connected to the Engine yet,

In such  scenario, the `SparkSQLEngine` will keep running until it hits the `kyuubi.session.engine.idle.timeout`

It's worth mentioning that it might not be an issue when the engine share level is USER, as other client connections could still use the Engine.

However, it will be a waste of resource when the engine share level is CONNECTION.
That's because all existing client connections will be disconnected once the KyuubiServer is shut down, 
and the engine is not reachable by any client at that point.

#### Question
Is it an expected behavior to rely on the timeout to terminate the Engine under the CONNECTION sharing level?
In my opinion, a more efficient method could be taking adavantage of `kyuubi.session.engine.alive.probe.enabled` or implement a similar mechanism where if an engine didn't receive any probe in a given timeframe, it kill itself.

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by risyomei** [comment]
I have done my research but couldn't find an existing ticket discussing the exact same topic.
The following tickets seems to be similar at first glance but there are on different topics:

- https://github.com/apache/kyuubi/issues/304: Not applicable to current code base as it's a very old ticket and lots have changed already.
- https://github.com/apache/kyuubi/issues/2104: Using YARN API instead of bin/stop-application.sh to stop application
- https://github.com/apache/kyuubi/issues/2645: Looks similar, but this bug report is focused on the time point when Engine is recognized in YARN, but not connected by `KyuubiSyncThriftClient#createClient`
- https://github.com/apache/kyuubi/issues/4591: The reported issue seems to be related with reporter's environment.

**Comment by pan3793** [comment]
@turboFei IIRC you had an idea about recovering session, could you share more details?

**Comment by pan3793** [comment]
> The KyuubiServer is not connected to the Engine yet

@risyomei I roughly remember there was a discussion about this case. The engine should quickly exit when no connections come in after bootstrap. Not sure if it was implemented.

**Comment by risyomei** [comment]
@pan3793 @turboFei 
Thank you very much for your input!
> we can add a timeout, if there is no connection established since the engine initialization, the engine should exit itself.

This approach sounds very reasonable and I will implement a patch based on that.

**Comment by risyomei** [comment]
Closing this as #5002 is merged.
