### ISSUE TITLE
[Bug] Remove default settings `spark.sql.execution.topKSortFallbackThreshold`

### ISSUE THREAD

**Issue by cxzl25** [apache/kyuubi#5005]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

The query results may be inaccurate.

Setting the topKSortFallbackThreshold value may lead to inaccurate results
https://issues.apache.org/jira/browse/SPARK-44240

https://github.com/apache/kyuubi/issues/1018

### Affects Version(s)

master/1.7/1.6/1.5

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by QianyongY** [comment]
please assgin to me
