### ISSUE TITLE
[FEATURE] Support query id in Spark engine

### ISSUE THREAD

**Issue by cxzl25** [apache/kyuubi#5030]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

The `SQLOperationListener` can get the `spark.sql.execution.id` when the sql execution starts.

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by lsm1** [comment]
please assign to me
