### ISSUE TITLE
[Bug] Spark operation CLOSED state should update `completedTime`

### ISSUE THREAD

**Issue by cxzl25** [apache/kyuubi#5036]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Now `SparkOperation#close` sets the status to `CLOSED`, but does not update the `completedTime`, resulting in the page showing that the SQL never completed.

https://github.com/apache/kyuubi/blob/e36d5d3fc96569eee8e6f8092b6a2ca4974bb2ab/externals/kyuubi-spark-sql-engine/src/main/scala/org/apache/kyuubi/engine/spark/operation/SparkOperation.scala#L216-L217

https://github.com/apache/kyuubi/blob/e36d5d3fc96569eee8e6f8092b6a2ca4974bb2ab/kyuubi-common/src/main/scala/org/apache/kyuubi/operation/AbstractOperation.scala#L118-L122

https://github.com/apache/kyuubi/blob/e36d5d3fc96569eee8e6f8092b6a2ca4974bb2ab/externals/kyuubi-spark-sql-engine/src/main/scala/org/apache/kyuubi/engine/spark/events/SparkOperationEvent.scala#L67-L73

### Affects Version(s)

all

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by CavemanIV** [comment]
We faced the same problem, I can help fix it
