### ISSUE TITLE
[Improvement] Add KDF engine_url

### ISSUE THREAD

**Issue by cxzl25** [apache/kyuubi#5076]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Register a custom UDF to get the engine's tracking url.

https://github.com/apache/kyuubi/blob/dbbcf4f4cd680954d33ade6b20087b7f42a0062a/externals/kyuubi-spark-sql-engine/src/main/scala/org/apache/kyuubi/engine/spark/KyuubiSparkUtil.scala#L57-L59

https://github.com/apache/kyuubi/blob/dbbcf4f4cd680954d33ade6b20087b7f42a0062a/externals/kyuubi-spark-sql-engine/src/main/scala/org/apache/kyuubi/engine/spark/udf/KDFRegistry.scala#L30

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by lsm1** [comment]
Please assigne to me
