### ISSUE TITLE
[TEST] BatchesResourceSuite - expose the metrics with operation type and current state *** FAILED ***

### ISSUE THREAD

**Issue by cxzl25** [apache/kyuubi#5104]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What kind of test improve?

- [X] Fix flaky tests.
- [ ] Fix bug in tests.
- [ ] Increase test coverage.
- [ ] Other kinds of test improve.

### Describe the issues of the existing tests or improvements for new tests

BatchesV2ResourceSuite

- expose the metrics with operation type and current state *** FAILED ***
  The code passed to eventually never returned normally. Attempted 665 times over 10.000385185 seconds. Last failure message: 1 did not equal 0. (BatchesResourceSuite.scala:769)

https://github.com/apache/kyuubi/actions/runs/6480461956/job/17596063538?pr=5400#step:8:1877

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by cxzl25** [comment]
It looks like UT occasionally fails because we submit a batch job, but perform a kill before we start running.


https://github.com/apache/kyuubi/blob/74e52f6924b8bd6a106925673c215383c0d50cf7/kyuubi-server/src/test/scala/org/apache/kyuubi/server/api/v1/BatchesResourceSuite.scala#L748-L773


```
11:57:22.284 KyuubiRestFrontendService-8213 WARN BatchesResource: duplicated submission: e70b16a6-f77b-4554-823e-edb4c9c38739, ignore and return the existing batch.

11:57:22.318 kyuubi-batch-submitter: Thread-8204 INFO KyuubiBatchService: e70b16a6-f77b-4554-823e-edb4c9c38739 is picked for submission.


11:57:22.322 KyuubiRestFrontendService-8213 WARN BatchesResource: Something wrong on deleting batch[e70b16a6-f77b-4554-823e-edb4c9c38739], try forcibly killing application

11:57:22.569 KyuubiSessionManager-exec-pool: Thread-8938 INFO ProcBuilder: Logging to /home/runner/work/kyuubi/kyuubi/kyuubi-server/target/work/anonymous/kyuubi-spark-batch-submit.log.8
11:57:22.569 KyuubiSessionManager-exec-pool: Thread-8938 INFO BatchJobSubmission: Submitting SPARK batch[e70b16a6-f77b-4554-823e-edb4c9c38739] job:
/home/runner/work/kyuubi/kyuubi/externals/kyuubi-download/target/spark-3.3.3-bin-hadoop3/bin/spark-submit \
	--class org.apache.spark.examples.SparkPi \
	--conf spark.kyuubi.batch.id=e70b16a6-f77b-4554-823e-edb4c9c38739 \
	--conf spark.kyuubi.batch.resource.uploaded=false \
	--conf spark.kyuubi.client.ipAddress=127.0.0.1 \
	--conf spark.kyuubi.engine.engineLog.path=/home/runner/work/kyuubi/kyuubi/kyuubi-server/target/work/anonymous/kyuubi-spark-batch-submit.log.8 \
	--conf spark.kyuubi.server.ipAddress=localhost \
	--conf spark.kyuubi.session.connection.url=localhost:39727 \
	--conf spark.kyuubi.session.real.user=anonymous \
	--conf spark.app.name=Spark Pi \
	--conf spark.kubernetes.driver.label.kyuubi-unique-tag=e70b16a6-f77b-4554-823e-edb4c9c38739 \
	--conf spark.master=local \
	--conf spark.yarn.tags=KYUUBI,e70b16a6-f77b-4554-823e-edb4c9c38739 \
	--proxy-user anonymous /home/runner/work/kyuubi/kyuubi/externals/kyuubi-download/target/spark-3.3.3-bin-hadoop3/examples/jars/spark-examples_2.12-3.3.3.jar

11:57:22.579 KyuubiRestFrontendService-8213 INFO BatchesResource: Mark batch[e70b16a6-f77b-4554-823e-edb4c9c38739] closed by localhost:39727

11:57:22.855 KyuubiSessionManager-exec-pool: Thread-8938 INFO BatchJobSubmission: Processing anonymous's query[7ebaf82c-8ce1-411d-af64-46d7316c69c7]: PENDING_STATE -> RUNNING_STATE, statement:
BatchJobSubmission
```

**Comment by pan3793** [comment]
A workaround approach to address this issue: maintain a Cache to represent the killed batches, performing a check before doing `spark-submit`.

cc @zwangsheng, would like to take a look?
