### ISSUE TITLE
[Bug]  `getColumns` gets duplicate column names when Spark integrates with Iceberg

### ISSUE THREAD

**Issue by cxzl25** [apache/kyuubi#5105]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

https://github.com/apache/kyuubi/discussions/4794#discussioncomment-5824988

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by lsm1** [comment]
I will try it, please assign to me
