### ISSUE TITLE
[DOC] Flink KDF usage

### ISSUE THREAD

**Issue by cxzl25** [apache/kyuubi#5118]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What type of changes will we make to the documentation?

Usage of New Feature

### Affects Version(s)

master

### Improving the documentation

https://github.com/apache/kyuubi/issues/4938

Spark KDF usage

https://github.com/apache/kyuubi/blob/master/docs/extensions/engines/spark/functions.md?plain=1

https://kyuubi.readthedocs.io/en/master/extensions/engines/spark/functions.html

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by link3280** [comment]
I could take care of this. Assigned myself if no other volunteers.
