### ISSUE TITLE
[Bug] Cancel operation will cause the log file node to leak

### ISSUE THREAD

**Issue by ASiegeLion** [apache/kyuubi#5210]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Execute sql, then cancel, use the lsof command to find the log file node leak,
![image](https://github.com/apache/kyuubi/assets/30170267/188e8151-e7c7-40c9-bdb9-d8daf3a0946a)
![image](https://github.com/apache/kyuubi/assets/30170267/3c2f9ea2-fc3c-420f-ac70-cf23236f10de)

The KyuubiOperation class found that there is a lack of code to close the log file in the case of cancle, causing the log file node to leak
![image](https://github.com/apache/kyuubi/assets/30170267/e685df16-cb1b-4a52-ae81-9c212095a2af)

### Affects Version(s)

master/1.7.1

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by ulysses-you** [comment]
Seems we should close operation log for canceled state.

**Comment by ASiegeLion** [comment]
> 看来我们应该关闭已取消状态的操作日志。



> Seems we should close operation log for canceled state.

There is no operation to delete the operation log in the cancel method, so where is the operation log finally deleted?

**Comment by ASiegeLion** [comment]
> Seems we should close operation log for canceled state.

There is no operation to delete the operation log in the cancel method, so where is the operation log finally deleted?

**Comment by ulysses-you** [comment]
in `close` method, we should close operation log for canceled state.
