### ISSUE TITLE
[Bug] kyuubi not support UTC+8 spark.sql.session.timeZone format

### ISSUE THREAD

**Issue by user-GitHub-user** [apache/kyuubi#5219]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

kyuubi version: 1.7.1
spark version: 3.2.1
I configure `spark.sql.session.timeZone=UTC+8`  in spark-default.conf under the spark conf directory  to specify the time zone
In this case, the data queried by kyuubi is 8 hours less than the data queried by Spark-SQL.
If I change the configuration to `spark.sql.session.timeZone=+08:00` , the data queried on both sides is the same.
I guess kyuubi doesn't support the UTC+8 time zone description format

### Affects Version(s)

1.7.0，1.7.1

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [X] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
cc @cxzl25 @cfmcgrady

**Comment by pan3793** [comment]
https://spark.apache.org/docs/latest/configuration.html

> The ID of session local timezone in the format of either region-based zone IDs or zone offsets. Region IDs must have the form 'area/city', such as 'America/Los_Angeles'. Zone offsets must be in the format '(+|-)HH', '(+|-)HH:mm' or '(+|-)HH:mm:ss', e.g '-08', '+01:00' or '-13:33:33'. Also 'UTC' and 'Z' are supported as aliases of '+00:00'. Other short names are not recommended to use because they can be ambiguous.

Seems by design, does `Aisa/Shanghai` work expected?

**Comment by user-GitHub-user** [comment]
Aisa/Shanghai is no problem

Using UTC+8 is to avoid Daylight Saving Time: DST issues

It seems that this problem can be solved by changing it to+08:00
