### ISSUE TITLE
[Improvement] `kyuubi.ha.zookeeper.publish.configs` not working properly when configuring multiple authentication modes

### ISSUE THREAD

**Issue by cxzl25** [apache/kyuubi#5226]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Because Kyuubi supports the configuration of multiple authentication methods, we can enable both KERBEROS or LDAP.
```properties
kyuubi.authentication KERBEROS,LDAP
kyuubi.ha.zookeeper.publish.configs true
```

After turning on `kyuubi.ha.zookeeper.publish.configs`, all authentication methods will be published to znode.

https://github.com/apache/kyuubi/blob/a01d7092eaacbbf1dbb11d421ba3746073b5b586/kyuubi-ha/src/main/scala/org/apache/kyuubi/ha/client/zookeeper/ZookeeperDiscoveryClient.scala#L330-L331

```bash
[zk: localhost:2181(CONNECTED) 0] get /kyuubi/serviceUri=127.0.0.1:10009;version=1.7.1;sequence=0000000000
```

```
hive.server2.thrift.sasl.qop=auth;hive.server2.thrift.bind.host=127.0.0.1;hive.server2.transport.mode=binary;hive.server2.authentication=KERBEROS,LDAP;hive.server2.thrift.port=10009
```

However, if you use Hive JDBC or Kyuubi JDBC neither of them support resolving multiple authentication methods from znode.

https://github.com/apache/kyuubi/blob/a01d7092eaacbbf1dbb11d421ba3746073b5b586/kyuubi-hive-jdbc/src/main/java/org/apache/kyuubi/jdbc/hive/ZooKeeperHiveClientHelper.java#L197-L216

https://github.com/apache/hive/blob/156905fcd588c99f596eb96a0932068df5007000/jdbc/src/java/org/apache/hive/jdbc/ZooKeeperHiveClientHelper.java#L351-L368

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
This may introduce another issue on the client side, if no `principal` is provided and 
```
kyuubi.authentication KERBEROS,LDAP
kyuubi.ha.zookeeper.publish.configs true
```

- current behavior, use SASL/plain
- after behavior, use SASL/GSSAPI

It's a breaking change for users who are using BeeLine with LDAP authentication.

**Comment by pan3793** [comment]
it's an expected behavior, close then
