### ISSUE TITLE
[Improvement] In SparkOperation#cleanup always calls cancelJobGroup even though it's in the completed state

### ISSUE THREAD

**Issue by cxzl25** [apache/kyuubi#5232]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

When the client submits a query, because the left table is empty, the query returns quickly, but because table b is relatively large, the job is still executing.

```
(select  * from empty_table) a left join (select  * from big_table ) b on a.key=b.key
```

https://github.com/apache/spark/blob/fd7acd32895ed79094ff75aef8ff133966627ee4/sql/hive-thriftserver/src/main/scala/org/apache/spark/sql/hive/thriftserver/SparkExecuteStatementOperation.scala#L306-L308

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by XorSum** [comment]
I want to implement it.
Please assign me.
