### ISSUE TITLE
Upgrade Jetty from 9.4.51.v20230217 to 9.4.52.v20230823

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#5234]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Why do we need to upgrade this artifact?

Common Vulnerabilities and Exposures (CVE)

### Artifact Name

https://mvnrepository.com/search?q=jetty

### Target Version

9.4.52.v20230823

### Notable Changes

https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.52.v20230823

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by sidhant-nagpal** [comment]
@pan3793 created a PR  : )
