### ISSUE TITLE
[Improvement] Make `engineAliveMaxFailCount` configurable

### ISSUE THREAD

**Issue by cxzl25** [apache/kyuubi#5244]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

https://github.com/apache/kyuubi/blob/8f8db09cee92bf1602cd2f5f2a84669b58ed330e/kyuubi-server/src/main/scala/org/apache/kyuubi/session/KyuubiSessionImpl.scala#L292

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by lsm1** [comment]
Please assigne to me
