### ISSUE TITLE
Web UI supports Swagger pages

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#5259]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

The new Web UI should support Swagger page like the existing one does

<img width="1747" alt="image" src="https://github.com/apache/kyuubi/assets/26535726/5946ab6a-e291-42d1-9fe9-72cfeb0ca4c2">

### Motivation

Align capabilities so that we can remove the legacy UI framework in next release

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
cc @zwangsheng

**Comment by zwangsheng** [comment]
@pan3793 Thanks for mentioning me, i'd like to take this.
