### ISSUE TITLE
[Bug] Dupllicated AnalyzesTablesCommand in kyuubi authz

### ISSUE THREAD

**Issue by AngersZhuuuu** [apache/kyuubi#5269]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

https://github.com/apache/kyuubi/blob/1a69772356f9eccc25d31aa51d4c9b7c6adafe44/extensions/spark/kyuubi-spark-authz/src/main/scala/org/apache/kyuubi/plugin/spark/authz/PrivilegesBuilder.scala#L159-L187

As the code listed above, duplicated `AnalyzeTablesCommand` in authz seems to be an issue, it won't be processed more than one time.

<img width="991" alt="lQLPJwxXbrAm0aDNATLNB76wsMmYIhDggCME7Tui64DSAA_1982_306" src="https://github.com/apache/kyuubi/assets/46485123/ffdfe780-f862-49ab-88b7-f1ea671b6570">

additionally, the extractor is incorrect.
 https://github.com/apache/kyuubi/blob/1a69772356f9eccc25d31aa51d4c9b7c6adafe44/extensions/spark/kyuubi-spark-authz/src/main/resources/table_command_spec.json#L912-L921

```
case class AnalyzeTablesCommand(
    databaseName: Option[String],
    noScan: Boolean) extends LeafRunnableCommand {
  ...
}
```

### Affects Version(s)

master

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
quoted from https://github.com/apache/kyuubi/pull/5270#issuecomment-1713260566

> It seems that they are applied to the same plan of analyzing tables in db, extracting privilege objects for both Databases and Tables.

it looks like it's by design the `AnalyzeTablesCommand` should be present in both `database_command_list.json` and `table_command_list.json`, we should not simply remove it from `table_command_list.json`.

**Comment by pan3793** [comment]
When taking a look deeply into the code, the execution of `AnalyzeTablesCommand` actually triggers the read privilege checking of each table, thus, even `AnalyzeTablesCommand ` listed in `table_command_spec.json` does not take effects, table privilege still to be checked, this is somewhat of a coincidence.

`AnalyzeTablesCommand#run` => `CommandUtils.analyzeTable` => `sparkSession.table(tableIdentWithDB).count()`

**Comment by pan3793** [comment]
Currently, `Analyze*Command` defined `isIntput=true`, which means only read privilege is required, but actually, those commands will update the table properties, I suppose they should be treated as `isInput=false`.

With the above assumption, `AnalyzeTablesCommand` should also manually check the user has both the write and read privileges of each table under the databases.

**Comment by pan3793** [comment]
@yaooqinn @bowenliang123 @zhouyifan279 WDYT?

**Comment by bowenliang123** [comment]
> Currently, `Analyze*Command` defined `isIntput=true`, which means only read privilege is required, but actually, those commands will update the table properties, I suppose they should be treated as `isInput=false`.
> 
> With the above assumption, `AnalyzeTablesCommand` should also manually check the user has both the write and read privileges of each table under the databases, instead of just removing it from `table_command_spec.json`

SGTM. Agree with your suggestions of 1 and 2 based on the discussions.
