### ISSUE TITLE
[Bug]: Simba Spark ODBC connection failing using http mode

### ISSUE THREAD

**Issue by nilan3** [apache/kyuubi#5278]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

I am trying to connect to Kyuubi via Simba Spark ODBC driver in http mode. I am facing the following error:

org.apache.kyuubi.server.KyuubiTHttpFrontendService: Client protocol version: HIVE_CLI_SERVICE_PROTOCOL_V10
org.apache.kyuubi.server.KyuubiTHttpFrontendService: Error opening session:
java.lang.NullPointerException: null 

### Affects Version(s)

1.7.1

### Additional context

![image](https://github.com/apache/kyuubi/assets/20682761/6e39ea8d-f5e6-40fd-9809-22009f84f180)

### Are you willing to submit PR?

- [x] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
> java.lang.NullPointerException: null

A bare NPE without stacktrace? Sounds unreasonable

**Comment by pan3793** [comment]
Maybe fixed by https://github.com/apache/kyuubi/pull/5204

Kyuubi 1.7.2 is voting, it's worth a try

https://www.mail-archive.com/dev@kyuubi.apache.org/msg02958.html

**Comment by nilan3** [comment]
Yes that fixes the issue, thanks
