### ISSUE TITLE
[Subtask] Support Hoodie Alter Table Command

### ISSUE THREAD

**Issue by AngersZhuuuu** [apache/kyuubi#5284]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Support hoodie sql in  anthz

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by yaooqinn** [comment]
Would you be willing to create an umbrella for it? Let's add command by command or in specific groups, such as xxx table, xxx merge, xxx function?

**Comment by AngersZhuuuu** [comment]
Sure
