### ISSUE TITLE
[Feature] Support use proxy user to kill application on YARN

### ISSUE THREAD

**Issue by zwangsheng** [apache/kyuubi#5295]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

As title,

When user call deleteBatch or just call ApplicationOperation kill application, may face real user(which kyuubi server used for kerberos) have no premission to kill application on yarn. 

### Motivation

As describe

### Describe the solution

Pass proxy user to kill application

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by cxzl25** [comment]
https://github.com/apache/kyuubi/pull/5306
