### ISSUE TITLE
2023 Kyuubi Code Contribution Program

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#5357]
Hi developers, welcome to the Apache Kyuubi community and participate in the **2023 Kyuubi Code Contribution Program**. It lasts two months, from **2023/10/10 18:00 GMT+8** to **2023/12/08 18:00 GMT+8**

Tasks: https://github.com/orgs/apache/projects/296

## Project introduction

[Apache Kyuubi](https://kyuubi.apache.org/) is a distributed and multi-tenant gateway to provide serverless SQL on data warehouses and lakehouses.

Kyuubi builds distributed SQL query engines on top of various kinds of modern computing frameworks, e.g., Apache Spark, Flink, Doris, Hive, and Trino, etc., to query massive datasets distributed over fleets of machines from heterogeneous data sources.

To learn more about Kyuubi, please visit
- [Apache Kyuubi Official Site](https://kyuubi.apache.org/)
- [Apache Kyuubi Online Documentation](https://kyuubi.readthedocs.io/)
- [Apache Kyuubi FAQ](https://github.com/apache/kyuubi/discussions/2481)
- [Who is using Apache Kyuubi?](https://github.com/apache/kyuubi/discussions/925)
- [Who is contributing Apache Kyuubi?](https://github.com/apache/kyuubi/discussions/3383)

## How to contribute?

If you are new to open source projects and not familiar with collaborative development on GitHub, it’s recommended to start with the trivial tasks listed below, which are mostly isolated, do not require full knowledge of the system, and this [guidance](https://github.com/firstcontributions/first-contributions/) may help you to send your first Pull Request.

And don’t forget to link your email used by git commits to your GitHub account, otherwise, your contributions will not be counted by GitHub.

Apache Kyuubi also provides various useful developer tools for linting, building, testing, documents, etc.
- [Apache Kyuubi Code Contribution Guide](https://kyuubi.readthedocs.io/en/master/contributing/code/index.html)
- [Apache Kyuubi Documentation Contribution Guide](https://kyuubi.readthedocs.io/en/master/contributing/doc/index.html)

Feel free to ask questions on [GitHub Discussion](https://github.com/apache/kyuubi/discussions) or [Slack](https://apachekyuubi.slack.com/ssb/redirect) / [WeChat](https://github.com/apache/kyuubi/assets/26535726/6ca8e785-43d1-4bc0-87f8-ea11d7d9b989) about setting up projects, infrastructure, tech stack, tips (anything that other potential contributors might also wonder, or benefit from)

## Task list

All proposed tasks will be listed at [2023 Kyuubi Code Contribution Program Tasks](https://github.com/orgs/apache/projects/296) after approval.

The existing tasks involve many aspects of Kyuubi project improvement, including
- new feature implementation
- performance improvement
- project building infrastructure enhancement
- CI stability improvements
- AIGC integration
- UX improvement
- service stability and observability enhancement
- documentation improvements
- modern version of programming language and computing engine adaptation
- dependency upgrading

The task list is to be extended, and you are very welcome to [propose new tasks](https://github.com/apache/kyuubi/issues/new?assignees=&labels=hacktoberfest&projects=&template=code-contrib-task.yml&title=%5BTASK%5D%5B%3CLEVEL%3E%5D+%3CThe+Task+Title%3E), your brilliant ideas keep Apache Kyuubi evolving.

## How to take a task?

1. Pick an issue you are interested in, and leave a comment with a **reasonable estimated deadline**(e.g. about 3 days) if you would like to take this task. For example,
   > I understand this task and want to have a try, I suppose I can complete it in 3 days.

2. Join the [Slack](https://apachekyuubi.slack.com/ssb/redirect) or [WeChat](https://github.com/apache/kyuubi/assets/26535726/6ca8e785-43d1-4bc0-87f8-ea11d7d9b989) and leave your GitHub ID to communicate with mentor

Note: To enable as many tasks as possible to be solved, the mentors/committers may **REVOKE** the assignment if the contributor has no response/progress in time.

**Comment by yaooqinn** [comment]
Can we update the from-to in the desc?

**Comment by pan3793** [comment]
what does "from-to" mean?

**Comment by yaooqinn** [comment]
start date - end date

**Comment by pan3793** [comment]
updated

**Comment by yaooqinn** [comment]
Can we add this event to https://kyuubi.apache.org/project_history.html

**Comment by cs-lpc** [comment]
WeChat QR has expired.
