### ISSUE TITLE
[TASK][TRIVIAL] Don't use Log4j2's extended throwable conversion pattern in default logging configurations

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#5365]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/296) and found no similar tasks.

### Mentor

- [ ] I have sufficient knowledge and experience of this task, and I volunteer to be the mentor of this task to guide contributors to complete the task.

### Skill requirements

- How to use and configure with log4j2

### Background and Goals

The Apache Spark Community found a performance regression with log4j2. See https://github.com/apache/spark/pull/36747. We can follow it to fix the performance issue on our side.

### Implementation steps

https://github.com/apache/spark/pull/36747 has an implementation that we can refer to.

Add `%ex` pattern to the layout in tests, main code, and templates.

`<PatternLayout pattern="%d{yy/MM/dd HH:mm:ss,SSS} %p [%t] %c{1}: %m%n%ex"/>`

### Additional context

Original reporter is @yaooqinn

**Comment by ITzhangqiang** [comment]
**I understand this task and want to have a try, l suppose l can complete it in 3 days.**
