### ISSUE TITLE
[TASK][MEDIUM] Add submit SQL page in Kyuubi Web UI

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#5366]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/296) and found no similar tasks.

### Mentor

- [ ] I have sufficient knowledge and experience of this task, and I volunteer to be the mentor of this task to guide contributors to complete the task.

### Skill requirements

- Frontend: Vue and TypeScript
- Backend: Scala, Jetty, Jersey, and concept of RESTful API design

### Background and Goals

- Kyuubi Server has RESTful API to submit SQL
- Need add a new page for Kyuubi web UI to submit SQL

### Implementation steps

Add a new page in Kyuubi frontend web page

<img width="1035" alt="image" src="https://github.com/apache/kyuubi/assets/26535726/558124c7-daed-4177-8c68-67a1ad5250ce">

Some corresponding RESTful API is also needed in the backend Jetty server.

You can find some examples in this https://github.com/apache/kyuubi/pull/4460

### Additional context

Original reporter: @zwangsheng

**Comment by zhaohehuhu** [comment]
I understand this task and would like to take a try, I suppose I can complete it on October 30th.
