### ISSUE TITLE
、Authz plugin support path-based table

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#5368]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/296) and found no similar tasks.

### Mentor

- [ ] I have sufficient knowledge and experience of this task, and I volunteer to be the mentor of this task to guide contributors to complete the task.

### Skill requirements

- Knowledge about Spark Catalyst
- Basic Knowledge of SQL authorization model, e.g. Apache Ranger

### Background and Goals

Allow the authz plugin to manage permissions for path-based tables, as the catalog table does.
https://github.com/apache/kyuubi/discussions/5166

### Implementation steps

Refer existing code of [authz module](https://github.com/apache/kyuubi/tree/master/extensions/spark/kyuubi-spark-authz), which is basically a Spark SQL extension, powers the Spark SQL with authorization capabilities by injecting some catalyst rules.

### Additional context

Original report is @yaooqinn

**Comment by Emor-nj** [comment]
Hi @pan3793, can you assign this task to me? I will try to finish it before November 11th. Thanks.

**Comment by pan3793** [comment]
assigned, thanks

**Comment by pan3793** [comment]
@Emor-nj do you have any progress on this task?

**Comment by pan3793** [comment]
revoked the assignment since there has been no response or update for a long time.

**Comment by pan3793** [comment]
@AngersZhuuuu I see this task blocks [your works](https://github.com/apache/kyuubi/issues/5285), would you like to take up this one too?

**Comment by AngersZhuuuu** [comment]
Yea

**Comment by AngersZhuuuu** [comment]
InsertIntoDataSourceCommand
InsertIntoHiveDirCommand
SaveIntoDataSourceCommand

**Comment by AngersZhuuuu** [comment]
CreateDatabaseCommand
DropDatabaseCommand
AlterDatabasePropertiesCommand with path
AlterDatabaseSetLocationCommand


AlterTableSetPropertiesCommand with path
AlterTableAddPartitionCommand
AlterTableDropPartitionCommand
AlterTableSetLocationCommand


AddJarsCommand
AddFilesCommand
AddArchivesCommand
ListFilesCommand
ListJarsCommand
ListArchivesCommand


LoadDataCommand

**Comment by yaooqinn** [comment]
Spark has forbidden alter locs for AlterDatabasePropertiesCommand / AlterTableSetPropertiesCommand, right?

**Comment by AngersZhuuuu** [comment]
> Spark has forbidden alter locs for AlterDatabasePropertiesCommand / AlterTableSetPropertiesCommand, right?

Yea

**Comment by pan3793** [comment]
This task was completed by splitting into several small tasks.
