### ISSUE TITLE
[TASK][MEDIUM] JDBC Engine supports ClickHouse

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#5374]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/296) and found no similar tasks.

### Mentor

- [ ] I have sufficient knowledge and experience of this task, and I volunteer to be the mentor of this task to guide contributors to complete the task.

### Skill requirements

- Basic knowledge of Scala programming language
- Basic knowledge of JDBC concepts
- Basic knowledge of Docker and [Testcontianers](https://java.testcontainers.org/)

### Background and Goals

Currently, Kyuubi supports JDBC engines with limited dialects, e.g. Doris, Phoenix, we can easily extend the dialects to support more databases.

Reference https://www.bilibili.com/video/BV1UT411m7LR

### Implementation steps

- Implement a ClickHouse dialect in the JDBC engine
- Leverage the Testcontainers to add integration tests
- Update document correspondingly

**Comment by pan3793** [comment]
Sure, could please 

> ... leave a comment with a reasonable estimated deadline

**Comment by pan3793** [comment]
Support other popular DB is fine too, feel free to make PRs, all your contribution will be counted :)

**Comment by cekicbaris** [comment]
hey guys, any progress on this ?

**Comment by pan3793** [comment]
@cekicbaris there is a draft PR https://github.com/apache/kyuubi/pull/5644, as the original author has no response, you can take over it if you like
