### ISSUE TITLE
[TASK][EASY] Change default metrics reporter to prometheus

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#5381]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/296) and found no similar tasks.

### Mentor

- [ ] I have sufficient knowledge and experience of this task, and I volunteer to be the mentor of this task to guide contributors to complete the task.

### Skill requirements

- Basic knowledge of Apache Kyuubi and Scala

### Background and Goals

Prometheus becomes de-faco metrics standard these days, it's better to change the default value of `kyuubi.metrics.reporters` from JSON to `PROMETHEUS`

### Implementation steps

- Change the default value of "kyuubi.metrics.reporters" defined in `MetricsConf`
- Regenerate the docs
- Update migration guide to mention the change
- Fix failed UT if any

**Comment by charandeepsinghb** [comment]
Hi I would like to work on this!
Please assign this to me. Thank you!

**Comment by ITzhangqiang** [comment]
Can you assign this issue to me? I plan to complete it by October 25th. @pan3793

**Comment by pan3793** [comment]
@ITzhangqiang this is almost done via https://github.com/apache/kyuubi/pull/5344

**Comment by zhaohehuhu** [comment]
I understand this task and almost make it done.
