### ISSUE TITLE
[TASK][EASY] `kyuubi-spark-connector-hive` supports Spark 3.5

### ISSUE THREAD

**Issue by wForget** [apache/kyuubi#5384]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Currently the `kyuubi-spark-connector-hive` module is not compatible with spark 3.5.

[kyuubi-spark-connector-hive_compatible_with_Spark_3_5.patch](https://github.com/apache/kyuubi/files/12842411/kyuubi-spark-connector-hive_compatible_with_Spark_3_5.patch)

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by ITzhangqiang** [comment]
**Is there anything else that needs to be done with this issue? I see there is already a patch**

**Comment by wForget** [comment]
> **Is there anything else that needs to be done with this issue? I see there is already a patch**

We may need to make changes compatible with spark 3.5 and older versions. The patch in issue description is only a change for spark 3.5 and may not be compatible with older versions.

**Comment by Kwafoor** [comment]
interested.
Please assgin to me, thanks.
