### ISSUE TITLE
[TASK][EASY] Kyuubi Chat engine supports 文心一言

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#5386]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/296) and found no similar tasks.

### Mentor

- [ ] I have sufficient knowledge and experience of this task, and I volunteer to be the mentor of this task to guide contributors to complete the task.

### Skill requirements

- Basic Scala programming language skills
- Basic knowledge of Kyuubi architecture

### Background and Goals

https://github.com/apache/kyuubi/pull/4544 introduced the Kyuubi Chat engine, which allows to use openAI GPT engine as the backend.

We could add more backends like 文心一言 for the Chat engine.

### Implementation steps

Follow the existing code of Chat engine OpenAI GPT backend and documents of 文心一言 to complete such integration

https://developer.baidu.com/article/detail.html?id=1089328

**Comment by phionex0571** [comment]
Hi, I'm insterested in this issue and I think it's resonable for me to finish this feature in a month, can you assign it to me?

**Comment by pan3793** [comment]
@phionex0571 thanks, assigned

**Comment by pan3793** [comment]
@phionex0571 what's the progress of this task?

**Comment by zhaohehuhu** [comment]
Hi @phionex0571 do you need any help?

**Comment by pan3793** [comment]
@phionex0571 revoked due to neither response nor progress

**Comment by zhaohehuhu** [comment]
If so, can I take this task?  I suppose I can finish it on Dec 4th.

**Comment by pan3793** [comment]
@zhaohehuhu thanks, assigned
