### ISSUE TITLE
[TASK][EASY] Pretty print exception for Kyuubi Event

### ISSUE THREAD

**Issue by wForget** [apache/kyuubi#5397]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/296) and found no similar tasks.

### Mentor

- [X] I have sufficient knowledge and experience of this task, and I volunteer to be the mentor of this task to guide contributors to complete the task.

### Skill requirements

- Knowledge of Kyuubi
- Familiar with the open-source ecosystem

### Background and Goals

As discussed in #5390, KyuubiEvent in json format is less readable due to the exception attribute of the event. We can pretty print exception attribute during json serialization.

### Implementation steps

- Add a custom `ThrowableSerializer` for `org.apache.kyuubi.events.JsonProtocol#mapper`.
- Make this behavior configurable

**Comment by fastPassion** [comment]
hello,I am interested in contributing to this project,please give me a chance to complete this task。

**Comment by pan3793** [comment]
@fastPassion thanks, assigned

**Comment by wForget** [comment]
BTW, the `org.apache.kyuubi.Utils#prettyPrint` method is already provided in kyuubi-common and you may need it
