### ISSUE TITLE
[TASK][EASY] JDBC Engine supports StarRocks

### ISSUE THREAD

**Issue by banmoy** [apache/kyuubi#5404]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/296) and found no similar tasks.

### Mentor

- [ ] I have sufficient knowledge and experience of this task, and I volunteer to be the mentor of this task to guide contributors to complete the task.

### Skill requirements

* Basic knowledge of Scala programming language
* Basic knowledge of JDBC concepts
* Basic knowledge of Docker and [Testcontianers](https://java.testcontainers.org/)

### Background and Goals

Currently, Kyuubi supports JDBC engines with limited dialects, and we can extend the dialects to support [StarRocks](https://www.starrocks.io/), which is an open-source and high-performance analytical database.

Reference https://www.bilibili.com/video/BV1UT411m7LR

### Implementation steps

* Implement a StarRocks dialect in the JDBC engine
* Leverage the Testcontainers to add integration tests
* Update document correspondingly

**Comment by banmoy** [comment]
@pan3793 could this issue be added to the task list of Code Contribution Program?

**Comment by pan3793** [comment]
@banmoy thanks, task was added to the list

**Comment by banmoy** [comment]
Thanks a lot :smiley:

**Comment by pan3793** [comment]
@banmoy would you like to complete it by yourself, or leave it to other contributors?

**Comment by phionex0571** [comment]
@pan3793 Hello, I have strong interests on it and during my daily work, Apache Kyuubi and StarRocks are two most useful tools. I think it can be finished in 7 days! please aisgn it to me~thx

**Comment by pan3793** [comment]
@phionex0571 Emm... you have been assigned 2 tasks, do you have sufficient free time to take the third and complete them in parallel?

**Comment by phionex0571** [comment]
> @phionex0571 Emm... you have been assigned 2 tasks, do you have sufficient free time to take the third and complete them in parallel?

@pan3793 Yeeep, in the previous year, I'd finished a StarRocks proxy in Apache Kyuubi 1.4, but that was not elegant and that was imitated like Apache Doris Engine implementation in Apache Kyuubi. And it's applied by 3 applications in production environment of my company. I hold strong belief that I'm able to finish this issue in time.

**Comment by bowenliang123** [comment]
Let's assign this task to both @phionex0571 @banmoy first.
Please raise the subtasks for this task. Small subtasks and improvements are always welcomed.
@phionex0571 please feel free to ask @banmoy about details of StartRocks, since he is from StarRocks team and has professionalism in Spark/Flink connector as well.

Also cc @zhaomin1423, the original contributor of the JDBC engine. They may need some guidance for this task. 

Thanks to all.

**Comment by zhaomin1423** [comment]
> Let's assign this task to both @phionex0571 @banmoy first. Please raise the subtasks for this task. Small subtasks and improvements are always welcomed. @phionex0571 please feel free to ask @banmoy about details of StartRocks, since he is from StarRocks team and has professionalism in Spark/Flink connector as well.
> 
> Also cc @zhaomin1423, the original contributor of the JDBC engine. They may need some guidance for this task.
> 
> Thanks to all.

Thanks you all, Starrocks is excellent ans used widely, look forward.

**Comment by zhaomin1423** [comment]
> Let's assign this task to both @phionex0571 @banmoy first. Please raise the subtasks for this task. Small subtasks and improvements are always welcomed. @phionex0571 please feel free to ask @banmoy about details of StartRocks, since he is from StarRocks team and has professionalism in Spark/Flink connector as well.
> 
> Also cc @zhaomin1423, the original contributor of the JDBC engine. They may need some guidance for this task.
> 
> Thanks to all.

Thanks you all, Starrocks is excellent ans used widely, look forward.

**Comment by phionex0571** [comment]
@bowenliang123 Hi, I've finished almost all the coding work and I have a question about StarRocks version in test cases. There're 
several versions of StarRocks and which one should I choose to design unit tests, is it reasonable to use StarRocks 2.5.13? or 3.x?

**Comment by banmoy** [comment]
@phionex0571 Is it possible to make the unit tests run against the latest several StarRocks versions, such as 2.5, 3.0, and 3.1? So that we can tell users in the doc which version of StarRocks is supported, just like Spark/Flink/Trino? I think test cases should be same among different versions, but just use the specific docker image for each version?

**Comment by bowenliang123** [comment]
@banmoy It's not suggested to tested on multiple versions of StarRocks. As for other engines for Spark/Flink/Trino, we tested on different matrix combinations as Kyuubi use different version of API on these engines and has dedicated engine implementation and adaptations.
But as StarRocks introduced no major FE feature or breaking changes in protocol or dialect between 2.x and 3.x, and the JDBC engine uses the same version of Mysql Driver for connection, it's reasonable to test only on the latest stable version.

**Comment by banmoy** [comment]
@phionex0571 Hi, is there any progress on this task?

**Comment by bowenliang123** [comment]
@banmoy StarRocks support of dialects/connection/tests in the JDBC engine has been introduced in PR 5882 (https://github.com/apache/kyuubi/pull/5882), if you may be concerned. Have check or validation on it.
