### ISSUE TITLE
[TASK][EASY] Support Flink 1.18

### ISSUE THREAD

**Issue by link3280** [apache/kyuubi#5405]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/296) and found no similar tasks.

### Mentor

- [X] I have sufficient knowledge and experience of this task, and I volunteer to be the mentor of this task to guide contributors to complete the task.

### Skill requirements

- Familiar with Flink SQL API

### Background and Goals

- Bump Flink version to 1.18 while maintaining compatibility with Flink 1.16 and 1.17.

### Implementation steps

- Add `flink-1.18` profile
- Fix API compatibility problem
- Add cross-version tests in CI workflow

**Comment by YesOrNo828** [comment]
@link3280  @pan3793  Could you assign this task to me? I want to task a shot at this.

**Comment by pan3793** [comment]
@YesOrNo828 thanks. Flink 1.18 has started the RC process, it's also a good opportunity for us to test at this stage.

https://www.mail-archive.com/dev@flink.apache.org/msg70029.html

**Comment by YesOrNo828** [comment]
@pan3793  Thanks for your reminder. I found out that RC2 was created last day. I'll use this version to test.
https://lists.apache.org/thread/z4rr3w013xw5tr5qhntgfn2spck5sgx1

**Comment by pan3793** [comment]
Based on the [real work](https://github.com/apache/kyuubi/pull/5465) of this task, I changed the task level from medium to easy.
