### ISSUE TITLE
[TASK][TRIVIAL] MetadataManager tries MySQL 8 driver class first

### ISSUE THREAD

**Issue by cxzl25** [apache/kyuubi#5408]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

https://github.com/apache/kyuubi/blob/fd69c6ee1dd40b7c4f496c74a45f574220448bc6/kyuubi-server/src/main/scala/org/apache/kyuubi/server/metadata/jdbc/JDBCMetadataStore.scala#L52

If we use `com.mysql.jdbc.Driver` in the MySQL 8 JDBC driver, we will get an error output. 
If `com.mysql.cj.jdbc.Driver` exists in the classpath, we can use it first.

https://github.com/mysql/mysql-connector-j/blob/7d6b0800528b6b25c68b52dc10d6c1c8429c100c/src/legacy/java/com/mysql/jdbc/Driver.java#L42-L45

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [X] No. I cannot submit a PR at this time.

**Comment by lsm1** [comment]
please assign to me
