### ISSUE TITLE
[Bug] spark-hive-connector can not compile against spark3.2

### ISSUE THREAD

**Issue by lordk911** [apache/kyuubi#5415]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

compile commond: 
`mvn clean install -pl extensions/spark/kyuubi-spark-connector-hive -P spark-3.2`
will got error : 

<img width="1205" alt="image" src="https://github.com/apache/kyuubi/assets/19989300/f28a311b-74c5-45c7-86da-832c5ab9f744">

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
It's by design, KSHC only supports Spark 3.3 and above.

**Comment by pan3793** [comment]
Close since it's not an issue, but you are welcome to contribute to making it support Spark 3.2.

BTW, please paste text instead of screenshot as much as possible, to make the content searchable for future explorers
