### ISSUE TITLE
[Bug] User-specified config about `kyuubi.operation.query.timeout` has no effect.

### ISSUE THREAD

**Issue by FMX** [apache/kyuubi#5419]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

I am using Spark with Kyuubi.
I want the query will be canceled due to timeout according to a user scope config but it has no effect. 
The two configs 
```properties
kyuubi.operation.query.timeout PT60s
___hadoop___.kyuubi.operation.query.timeout PT30s
```
After debugging, I found that the clientQueryTimeout is always 0 in `KyuubiOperationManager` and just uses the global queryTimeout.
<img width="815" alt="截屏2023-10-13 20 05 32" src="https://github.com/apache/kyuubi/assets/4150993/4835219e-0ed2-4c17-94cf-f7c4b7298102">

### Affects Version(s)

1.7.1

### Kyuubi Server Log Output

```logtalk
2023-10-13T19:57:35,006 INFO org.apache.kyuubi.server.KyuubiServer: Service[KyuubiBackendService] is started.
2023-10-13T19:57:35,007 INFO org.apache.zookeeper.ClientCnxn: Session establishment complete on server master-1-1/192.168.13.15:2181, sessionid = 0x1000000b31206fc, negotiated timeout = 60000
2023-10-13T19:57:35,007 INFO org.apache.kyuubi.server.KyuubiTBinaryFrontendService: Starting and exposing JDBC connection at: jdbc:hive2://master-1-1:10009/
```

### Kyuubi Server Configurations

```yaml
kyuubi.operation.query.timeout PT60s
___hadoop___.kyuubi.operation.query.timeout PT30s
```

### Kyuubi Engine Configurations

```yaml
spark.kyuubi.operation.query.timeout	PT30s
```

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [X] No. I cannot submit a PR at this time.

**Comment by yaooqinn** [comment]
For client query timeout， please use `java.sql.Statement#setQueryTimeout` `kyuubi.operation.query.timeout` is a server-level config, not user-level

**Comment by FMX** [comment]
Thanks, I'll try as you have explained.
