### ISSUE TITLE
[TASK][EASY] `kyuubi.zookeeper.embedded.data.log.dir` does not take effect

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#5441]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/296) and found no similar tasks.

### Mentor

- [ ] I have sufficient knowledge and experience of this task, and I volunteer to be the mentor of this task to guide contributors to complete the task.

### Skill requirements

- Basic Scala programming language skill

### Background and Goals

It's a bug, that `kyuubi.zookeeper.embedded.data.log.dir` does not take effect

### Implementation steps

Correct the usage of `kyuubi.zookeeper.embedded.data.log.dir`

**Comment by YetiCuzMountain** [comment]
I am a novice, could  this task be assigned to me for practice？

**Comment by davidyuan1223** [comment]
> I am a novice, could this task be assigned to me for practice？

it look like the code bug, i think this can help you to fix the bug?
![image](https://github.com/apache/kyuubi/assets/51512358/892170f1-48a5-4b49-aa59-09ddf7f2a880)
![image](https://github.com/apache/kyuubi/assets/51512358/e4c250a9-65cb-400a-8088-a57a8c91e3b1)

**Comment by YetiCuzMountain** [comment]
this issue has been fixed in #5440

**Comment by YetiCuzMountain** [comment]
I have fixed this issue in #5440

**Comment by pan3793** [comment]
@biangjuang I opened this task for https://github.com/apache/kyuubi/pull/5440, would you like to leave a comment on this issue so that i can assign this task to you?

**Comment by pan3793** [comment]
@davidyuan1223 thanks for looking this, it's already fixed in https://github.com/apache/kyuubi/pull/5440 before task is opened.

**Comment by biangjuang** [comment]
I have completed this task in #5440
