### ISSUE TITLE
[TASK][TRIVIAL] bump Delta Lake 3.0.0

### ISSUE THREAD

**Issue by cfmcgrady** [apache/kyuubi#5449]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

https://github.com/delta-io/delta/releases/tag/v3.0.0

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by zml1206** [comment]
I understand this task and want to have a try.
