### ISSUE TITLE
[TASK][MEDIUM] JDBC Engine supports MySQL

### ISSUE THREAD

**Issue by cxzl25** [apache/kyuubi#5464]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/296) and found no similar tasks.

### Mentor

- [X] I have sufficient knowledge and experience of this task, and I volunteer to be the mentor of this task to guide contributors to complete the task.

### Skill requirements

- Basic knowledge on Scala Programing Language

### Background and Goals

Now JDBC engine does not support MySQL Dialect (`kyuubi.engine.jdbc.type=mysql`)

Although we can use `kyuubi.engine.jdbc.type=doris` to connect to the MySQL server.

### Implementation steps

externals/kyuubi-jdbc-engine/src/main/scala/org/apache/kyuubi/engine/jdbc/dialect

- Add MySQL dialect

**Comment by Kwafoor** [comment]
hello，can i take this?  I expect to achieve it in two weeks.

**Comment by pan3793** [comment]
@Kwafoor assigned, good luck!

**Comment by Kwafoor** [comment]
> @Kwafoor assigned, good luck!

Thanks, i will try to finish this in two weeks.

**Comment by pan3793** [comment]
Escalate task level from easy to medium due to the complexity of implementation
