### ISSUE TITLE
[TASK][MEDIUM] Integrate Intel Gluten with Spark engine

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#5467]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/296) and found no similar tasks.

### Mentor

- [X] I have sufficient knowledge and experience of this task, and I volunteer to be the mentor of this task to guide contributors to complete the task.

### Skill requirements

- Basic knowledge of Scala programming language, Kyuubi architecture, Apache Spark, Intel Gluten
- Basic English writing skills

### Background and Goals

[Gluten](https://github.com/oap-project/gluten) is a Spark plugin developed by Intel to accelerate Apache Spark with native libraries.

As Kyuubi currently supports using Spark as the computing engine, we can add tests to integrate with Gluten in the Spark engine, and write docs to guide users in setting up Kyuubi with Spark plus Gluten to improve performance.

### Implementation steps

- Add Gluten UTs in spark engine module, which could be conditionally enabled via maven profile and scalatest annotation
- Setup CI for Gluten testing
- Write docs to guide users in setting up Kyuubi with Spark plus Gluten.

**Comment by Kwafoor** [comment]
I am interested in this and I expect to achieve it in a month, can i take this？

**Comment by pan3793** [comment]
Yea, of course, also cc @ulysses-you as he is working on Gluten recently

**Comment by Kwafoor** [comment]
> Yea, of course, also cc @ulysses-you as he is working on Gluten recently

Thanks

**Comment by ulysses-you** [comment]
The first version, I'd like to only Integrate with Gluten main branch. That said, we should build related library by ourself.

**Comment by pan3793** [comment]
@Kwafoor what's the progress of this task?

**Comment by Kwafoor** [comment]
> @Kwafoor what's the progress of this task?

The task has just started, I'm currently researching gluten. Is there a specific time when this task needs to be completed?

**Comment by davidyuan1223** [comment]
i have a question, i also interested in native engins'use,but i remember gluten currently need velox or clickhous's support, the arrow are not supported complete? how can we test gluten in this project? @pan3793

**Comment by ulysses-you** [comment]
@davidyuan1223 it's about integration test. We can add a workflow to test gluten main branch every day.

**Comment by davidyuan1223** [comment]
understand,thanks @ulysses-you

**Comment by ulysses-you** [comment]
@Kwafoor Gluten supports macOS since https://github.com/oap-project/gluten/pull/2691. It would be more easier to use docker to package and test Gluten. We can make our integration test running with `Ubuntu20.04` in docker, some docs https://github.com/oap-project/gluten/blob/main/docs/developers/docker_ubuntu22.04.md

**Comment by pan3793** [comment]
ubuntu 22 or 20 is prefered

**Comment by Kwafoor** [comment]
> @Kwafoor Gluten supports macOS since [oap-project/gluten#2691](https://github.com/oap-project/gluten/pull/2691). It would be more easier to use docker to package and test Gluten. We can make our integration test running with `Ubuntu20.04` in docker, some docs https://github.com/oap-project/gluten/blob/main/docs/developers/docker_ubuntu22.04.md

Thanks a lot, I'll give it a try.

**Comment by Kwafoor** [comment]
> ubuntu 22 or 20 is preferred

I'll try  it.

**Comment by Kwafoor** [comment]
I am preparing to package and test using the gluten method `./dev/buildbundle-veloxbe.sh`. For these tests, I plan to package and execute them daily.

In the initial version, I am only preparing to support testing for versions of spark 3.2, 3.3, 3.4 that are supported by gluten. Velox will be used as the backend. 

Regarding the unit tests, my only idea at the moment is to check for the existence of gluten-related operators in the execution plans. Is there any reference about this?

If there is no further supplement, I expect to submit the initial version by next Monday at the latest.

**Comment by pan3793** [comment]
for testing, Kyuubi provides spark tpc-h/ds connector and queries, would be good cases

**Comment by Kwafoor** [comment]
> for testing, Kyuubi provides spark tpc-h/ds connector and queries, would be good cases

good idea, i will try it!

**Comment by ulysses-you** [comment]
thank you @Kwafoor , I think `dev/builddeps-veloxbe.sh` is good enough as we only run the gluten it nightly. We can add a new job in `nightly.yml` and it doesn't matter if the new job speed is slow.

**Comment by Kwafoor** [comment]
> thank you @Kwafoor , I think `dev/builddeps-veloxbe.sh` is good enough as we only run the gluten it nightly. We can add a new job in `nightly.yml` and it doesn't matter if the new job speed is slow.

OK, thank you

**Comment by Kwafoor** [comment]
> for testing, Kyuubi provides spark tpc-h/ds connector and queries, would be good cases

When I conducted the TPCH tests using Gluten, I identified two issues. Due to these, I am considering segregating Kyuubi Gluten TPC-H/DS into a separate issue. Would this be acceptable? @pan3793 

1. While testing for `tpch.tiny` data, a discrepancy in the query result of q9 gluten+velox+spark3.4 in comparison to spark3.4. Gluten was `[SAUDI ARABIA,1995,62668.73]`, Spark3.4 was `[SAUDI ARABIA,1995,62668.72]`.
2. Gluten+velox+spark3.4 was observed to execute slower than spark3.4. I'd have to further explore to understand the specific reasons behind this. Here are the related logs.

```log
## gluten+velox+spark3.4
03:43:56.634 broadcast-exchange-30 INFO DAGScheduler: Job 73 finished: collect at SparkPlanExecApiImpl.scala:284, took 6.998831 s
03:43:59.349 broadcast-exchange-28 INFO DAGScheduler: Job 74 finished: collect at SparkPlanExecApiImpl.scala:284, took 9.710332 s
03:44:19.072 broadcast-exchange-31 INFO DAGScheduler: Job 75 finished: collect at SparkPlanExecApiImpl.scala:284, took 29.406944 s
```

```log
## spark3.4
09:48:41.929 broadcast-exchange-29 INFO DAGScheduler: Job 71 finished: $anonfun$withThreadLocalCaptured$1 at FutureTask.java:266, took 0.054058 s
09:48:41.946 broadcast-exchange-28 INFO DAGScheduler: Job 72 finished: $anonfun$withThreadLocalCaptured$1 at FutureTask.java:266, took 0.067240 s
09:48:41.974 broadcast-exchange-30 INFO DAGScheduler: Job 73 finished: $anonfun$withThreadLocalCaptured$1 at FutureTask.java:266, took 0.092720 s
09:48:42.013 broadcast-exchange-32 INFO DAGScheduler: Job 75 finished: $anonfun$withThreadLocalCaptured$1 at FutureTask.java:266, took 0.130110 s
09:48:42.019 broadcast-exchange-31 INFO DAGScheduler: Job 74 finished: $anonfun$withThreadLocalCaptured$1 at FutureTask.java:266, took 0.137744 s
```

**Comment by pan3793** [comment]
@Kwafoor we can disable certain test cases and fix them later

**Comment by Kwafoor** [comment]
> @Kwafoor we can disable certain test cases and fix them later

OK
