### ISSUE TITLE
[Bug] Permanent View should pass column when child plan no output

### ISSUE THREAD

**Issue by AngersZhuuuu** [apache/kyuubi#5472]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

For case such as `SELECT COUNT(*) FORM xx`, when xx is table, will extract table's column, is xx is view, only pass view name

```
  test("[KYUUBI #xxx] ") {
    val db1 = defaultDb
    val table1 = "table1"
    val view1 = "view1"
    withSingleCallEnabled {
      withCleanTmpResources(Seq((s"$db1.$table1", "table"), (s"$db1.$view1", "view"))) {
        doAs(admin, sql(s"CREATE TABLE IF NOT EXISTS $db1.$table1 (id int, scope int)"))
        doAs(admin, sql(s"CREATE VIEW $db1.$view1 AS SELECT * FROM $db1.$table1"))
        val e1 = intercept[AccessControlException](
          doAs(someone, sql(s"SELECT count(*) FROM $db1.$table1").show()))
        assert(e1.getMessage.contains(
          s"does not have [select] privilege on [$db1/$table1/id,$db1/$table1/scope]"))

        val e2 = intercept[AccessControlException](
          doAs(someone, sql(s"SELECT count(*) FROM $db1.$view1").show()))
        assert(e2.getMessage.contains(
          s"does not have [select] privilege on [$db1/$view1]"))
      }
    }
  }
```

### Affects Version(s)

master, 1.8.0

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by bowenliang123** [comment]
Nice catch. Thanks for fixing this.
