### ISSUE TITLE
[Umbrella] Support Delta Lake in Authz

### ISSUE THREAD

**Issue by cfmcgrady** [apache/kyuubi#5477]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues) and found no similar issues.

### Describe the proposal

Introduce Delta Lake support in Kyuubi Authz plugin.

### Task list

TODO

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by cfmcgrady** [comment]
cc @zml1206

**Comment by zml1206** [comment]
Thanks @cfmcgrady. I want to have a try.

**Comment by zml1206** [comment]
Regarding Delta lake path authz, should re-create an umbrella task or create a subtask based on this? @cfmcgrady @yaooqinn

**Comment by yaooqinn** [comment]
@zml1206 let's have an new umbrella
