### ISSUE TITLE
Remove legacy Web UI

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#5484]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Kyuubi provides a basic new Web UI which is built on top of Vue3, we can remove the legacy dummy Web UI in 1.8

### How should we improve?

The new UI hosts at `http://<host>:<port>/ui/` and the legacy UI hosts at `http://<host>:<port>/`, we should 

1. Remove the legacy UI routing from Jetty
2. Remove all files related to legacy UI
3. Redirect `http://<host>:<port>/` to `http://<host>:<port>/ui/`

### Are you willing to submit PR?

- [x] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by link3280** [comment]
Big +1. The old UI is incomplete and misleading. 

<img width="1512" alt="截屏2023-10-23 17 01 30_副本" src="https://github.com/apache/kyuubi/assets/13482005/18c0476c-c31e-4ed7-aae1-143b6e1e349c">
