### ISSUE TITLE
[Bug] acknowledge license copyright for swagger-scala-module

### ISSUE THREAD

**Issue by pjfanning** [apache/kyuubi#5491]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

This PR borrows code from swagger-scala-module. https://github.com/apache/kyuubi/pull/2551

This should be acknowledged in your source LICENSE.

https://github.com/swagger-akka-http/swagger-scala-module#license includes:

```
Copyright 2016 SmartBear Software, Inc.
```

### Affects Version(s)

recent

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [X] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
@pjfanning thanks for reporting this issue, I suppose swagger-scala-module will be removed in https://github.com/apache/kyuubi/issues/5484, will take a look soon

**Comment by pjfanning** [comment]
@pan3793 thanks for the response. I looked again at your master branch and it seems like the code that was copied from swagger-scala-module has been removed. I will close this.
