### ISSUE TITLE
[Bug] KyuubiSessionManager timeout checker thread does not work

### ISSUE THREAD

**Issue by turboFei** [apache/kyuubi#5499]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

The kyuubi batch connections always increasing and seems the timeout-checker does not work.

The batch session idle timeout is PT5M, but the batch connections always increasing.
<img width="1402" alt="image" src="https://github.com/apache/kyuubi/assets/6757692/772490e0-deee-4e87-947d-eb0f55c7dec3">

### Affects Version(s)

master

### Kyuubi Server Log Output

[kyuubi_jstack.txt](https://github.com/apache/kyuubi/files/13066403/kyuubi_jstack.txt), see `KyuubiSessionManager-timeout-checker`.

The result of `grep 'that has been idle for more' kyuubi.log` is empty.

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by turboFei** [comment]
only one kyuubi node has this issue. total 6 kyuubi nodes.

**Comment by yaooqinn** [comment]
KyuubiSessionManager-timeout-checker seems in good shape?

**Comment by turboFei** [comment]
> KyuubiSessionManager-timeout-checker seems in good shape?

I plan to log some info for debug.

**Comment by wForget** [comment]
Similar to #2503?

**Comment by wForget** [comment]
I guess this may be due to some exceptions not being caught.

**Comment by turboFei** [comment]
> I guess this may be due to some exceptions not being caught in checkTask.

thanks @wForget let us catch any exception in checkTask https://github.com/apache/kyuubi/pull/5515
