### ISSUE TITLE
[TASK][EASY] Introduce HELP command in Flink engine

### ISSUE THREAD

**Issue by YesOrNo828** [apache/kyuubi#5505]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/296) and found no similar tasks.

### Mentor

- [ ] I have sufficient knowledge and experience of this task, and I volunteer to be the mentor of this task to guide contributors to complete the task.

### Skill requirements

- Familiar with Flink SQL

### Background and Goals

Show available commands when users type 'HELP;' in the beeline.

### Implementation steps

- Using Flink SQL Client Parser(SqlCommandParserImpl) obtain the Command enum
- Return Help message
- Add 'HELP' statement test

**Comment by pan3793** [comment]
@YesOrNo828 have you started working on this task?

**Comment by YesOrNo828** [comment]
> @YesOrNo828 have you started working on this task?

Yes, I found there are some incompatible APIs between Flink 1.16 and 1.17 versions. I'm trying to fix it.

btw, this is a demo of HELP command run in the Flink 1.18 
![image](https://github.com/apache/kyuubi/assets/6017591/e2224177-a561-4d4b-951e-743c4c57ce38)

**Comment by pan3793** [comment]
Looks nice. One more question: do all commands listed below work on the Kyuubi Flink engine?

**Comment by YesOrNo828** [comment]
> Looks nice. One more question: do all commands listed below work on the Kyuubi Flink engine?

I have checked :
QUIT/EXIT commands don't work. beeline needs to use '!exit' or '!quit' to exit the program. 
CLEAR command is invalid.
REMOVE JAR command is not supported in Flink SQL Gateway right now, I have created an [issue](https://issues.apache.org/jira/browse/FLINK-33374) to follow.
Other commands work fine.
