### ISSUE TITLE
[TASK][EASY] Support Initialize SQL in Flink Engine

### ISSUE THREAD

**Issue by link3280** [apache/kyuubi#5507]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/296) and found no similar tasks.

### Mentor

- [X] I have sufficient knowledge and experience of this task, and I volunteer to be the mentor of this task to guide contributors to complete the task.

### Skill requirements

- Basic knowledge of Flink Engine
- Basic knowledge of Flink SQL

### Background and Goals

Support initialize SQL in Flink SQL (e.g. setting up catalogs).

### Implementation steps

- Pass initialize SQL to Flink engine
- Execute the SQLs during engine bootstrap

**Comment by link3280** [comment]
cc @hadoopkandy

**Comment by abhinavs1920** [comment]
Please assign this issue to me

**Comment by link3280** [comment]
@abhinavs1920 Thanks for reaching out! I'm afraid that @hadoopkandy has started the related work, so I'm assigning this to him first and will let you know if a hand is needed. Thanks again!

**Comment by pan3793** [comment]
This task is completed by @hadoopkandy via #5507
