### ISSUE TITLE
[TASK][TRIVIAL] Upgrade download-maven-plugin from 1.6.8 to 1.7.1

### ISSUE THREAD

**Issue by yaooqinn** [apache/kyuubi#5508]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/296) and found no similar tasks.

### Mentor

- [X] I have sufficient knowledge and experience of this task, and I volunteer to be the mentor of this task to guide contributors to complete the task.

### Skill requirements

- Apache Maven

### Background and Goals

Upgrade download-maven-plugin

### Implementation steps

download-maven-plugin version change

**Comment by rojin254** [comment]
hi could I work on this issue?

**Comment by pan3793** [comment]
@rojin254 assigned, thanks

**Comment by pan3793** [comment]
@rojin254 have you started looking at this task? it should a kind of "one line code change" task ~

**Comment by rojin254** [comment]
sorry for the delay, I just updated the version in the pom.xml
