### ISSUE TITLE
Add SQL query service for Impala component

### ISSUE THREAD

**Issue by smileyboy2019** [apache/kyuubi#5509]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

At present, most data warehouses are built through hive+impla for data warehouse construction, and it is also hoped that query services can be provided through the unified entrance of kyuubi, supporting multi tenant

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [X] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
maybe @qian0817 has some idea?

**Comment by adios666** [comment]
I'm working on this, will support use Kyuubi as Impala client to submit SQL at first.

**Comment by pan3793** [comment]
@adios666 awesome!

**Comment by tigrulya-exe** [comment]
@adios666 Hi! If no work has started on this issue yet, I would like to add Impala support by adding the corresponding JDBC dialect to the JDBC engine. @pan3793 What do you think?
