### ISSUE TITLE
[TASK][EASY] Build dist with metastore sql

### ISSUE THREAD

**Issue by cxzl25** [apache/kyuubi#5561]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

copy `kyuubi-server/src/main/resources/sql` to dist tar.

e.g. Hive meta store
https://github.com/apache/hive/blob/40551ff4669325defa08ff2adc0b497296cf46fa/standalone-metastore/metastore-server/src/assembly/bin.xml#L85-L91

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by lsm1** [comment]
I will try it, please assgin to me

**Comment by pan3793** [comment]
thanks, it was reported a few times by users, and this should be included in 1.8.0
