### ISSUE TITLE
[TASK][EASY] Introduce Kyuubi Web UI Engine Page

### ISSUE THREAD

**Issue by zwangsheng** [apache/kyuubi#5572]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/296) and found no similar tasks.

### Mentor

- [X] I have sufficient knowledge and experience of this task, and I volunteer to be the mentor of this task to guide contributors to complete the task.

### Skill requirements

- Familiar with Web UI
- Good English expression ability

### Background and Goals

Introduce about Kyuubi Web UI Engine Page, should with some screenshot about engine page.

### Implementation steps

As goals.

**Comment by zhaohehuhu** [comment]
I understand this task and would like to take a try, I suppose I can finish it on Nov 17th. Plz assign the task to me.

**Comment by zhaohehuhu** [comment]
still doing.
