### ISSUE TITLE
[TASK][EASY] JDBC Engine supports configurable fetchSize

### ISSUE THREAD

**Issue by cxzl25** [apache/kyuubi#5582]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

org.apache.kyuubi.engine.jdbc.dialect.JdbcDialect

https://github.com/apache/kyuubi/blob/591250c8ff47af8e2a665cc4086cb0fa4c29b609/externals/kyuubi-jdbc-engine/src/main/scala/org/apache/kyuubi/engine/jdbc/dialect/JdbcDialect.scala#L31-L38

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by lsm1** [comment]
please assign to me
