### ISSUE TITLE
[Bug] Spark Engine kyuubi.ha.zookeeper.auth.keytab file does not exists when run in cluster mode with k8s

### ISSUE THREAD

**Issue by Z1Wu** [apache/kyuubi#5625]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

When submiting Spark Engine  in cluster mode with k8s, SparkSQLEngine running in k8s pod throws execption as follow( detailed log see Engine Log Section)

```
Caused by: java.lang.RuntimeException: java.io.IOException: kyuubi.ha.zookeeper.auth.keytab: /home/hadoop/keytab/hive.keytab does not exists
```

Zookeeper keytab file is stored in kyuubi server host. When submit spark application, this keytab file will added to spark runtime using `--files`.

https://github.com/apache/kyuubi/blob/fdacd239647a37c3ce993c517575b3c254a33681/kyuubi-server/src/main/scala/org/apache/kyuubi/engine/spark/SparkProcessBuilder.scala#L193-L205

But when creating zookeeper client in SparkSQLEngine, current implementation try to  find zookeeper keytab file from `current work directory`  and `full path`. 
- `Full path` will not work due to that is the path of kyuubi server host, while 
- `Current work directory` will not work either.  In k8s cluster mode, driver pod will run with `SPARK_LOCAL_DIRS` by default setting to a tmp directory and file added by `--files` will be fetched into that direcotory.

https://github.com/apache/kyuubi/blob/fdacd239647a37c3ce993c517575b3c254a33681/kyuubi-ha/src/main/scala/org/apache/kyuubi/ha/client/zookeeper/ZookeeperClientProvider.scala#L146-L151

IMO, `ZookeeperClientProvider` should read files uploaded by spark-submit using `SparkFiles` utils. However this method will introduce spark dependency to `kyuubi-ha` module.

Currently, my work-aournd looks like blow:

``` scala
// rewrite HA_ZK_AUTH_KEYTAB with ture path obtain from `SparkFiles` when running spark with k8s-cluster mode
// org.apache.kyuubi.engine.spark.SparkSQLEngine#createSpark():
val zkKeytabPath = kyuubiConf.get(HA_ZK_AUTH_KEYTAB)
// if submit in cluster mode with k8s master rewrite SparkFile related settings
if (zkKeytabPath.isDefined
  && session.sparkContext.master.contains("k8s")
  && _sparkConf.getBoolean("spark.kubernetes.submitInDriver", defaultValue = false)) {
  info("rewrite zk auth path when in k8s-cluster mode")
  val relativeFileName = new File(zkKeytabPath.get).getName
  val uploadedFilePath = SparkFiles.get(relativeFileName)
  if (new File(uploadedFilePath).exists()) {
    kyuubiConf.set(HA_ZK_AUTH_KEYTAB.key, uploadedFilePath)
  } else {
    error(
      s"unable to get zk_auth_keytab from uploaded files, " +
        s"when setting (${HA_ZK_AUTH_KEYTAB.key} = ${zkKeytabPath})" +
        s"and uploaded file path ${uploadedFilePath}")
  }
}
```

### Affects Version(s)

master

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
Which Spark version you are using? I suppose SPARK-33782 should fix the issue you mentioned

**Comment by Z1Wu** [comment]
Thanks for your response.

I currently use Spark 3.2,  which affected by SPARK-33782. And you are right, that patch can fix my issue.

Small suggestions, it will be great if spark version requirement can be documented in this page.
https://kyuubi.readthedocs.io/en/master/deployment/engine_on_kubernetes.html#deploy-kyuubi-engines-on-kubernetes

**Comment by pan3793** [comment]
@Z1Wu thanks for your feedback and advice, TBH, the Spark on K8s still has lots of functionalities compared to Spark on YARN even it was marked as GA since Spark 3.1, for most cases, we'd like to try our best to work around them on the Kyuubi side, but this only covers limited issues.
BTW, I suggest you choose a higher Spark version(3.4 or above) of your just start evaluating Spark on K8s, but if you must stick on 3.2, better to skim all patches(or even PRs which were not merged) from the master branch before moving to next steps.
