### ISSUE TITLE
[Subtask] URI related privileges shall be READ/WRITE

### ISSUE THREAD

**Issue by yaooqinn** [apache/kyuubi#5638]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues) and found no similar issues.

### Describe the subtask

URI related privileges shall be READ/WRITE

### Parent issue

#5368

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
This task is completed by @AngersZhuuuu
