### ISSUE TITLE
[TASK][EASY] JDBC driver implements `Result#getDate` with `Calendar` parameters

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#5650]
### What's the level of this task?

EASY

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/296) and found no similar tasks.

### Mentor

- [ ] I have sufficient expertise on this task, and I volunteer to be a mentor of this task to guide contributors through the task.

### Skill requirements

- JDBC concepts
- Java

### Background and Goals

https://github.com/apache/kyuubi/discussions/5649

### Implementation steps

Implement the required methods, and test with Tableau

### Additional context

Introduction of [2023 Kyuubi Code Contribution Program](https://github.com/apache/kyuubi/issues/5357)

**Comment by zhaohehuhu** [comment]
I understand this task and would like to take a try, I suppose I can finish it on Nov 17th. Plz assign the task to me. @pan3793

**Comment by pan3793** [comment]
Thanks, assigned

**Comment by zhaohehuhu** [comment]
still doing.
