### ISSUE TITLE
[TASK][EASY] Introduce new config to force rewrite pod name

### ISSUE THREAD

**Issue by zwangsheng** [apache/kyuubi#5654]
### What's the level of this task?

EASY

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/296) and found no similar tasks.

### Mentor

- [X] I have sufficient expertise on this task, and I volunteer to be a mentor of this task to guide contributors through the task.

### Skill requirements

- Scala
- Kyuubi Config Specification

### Background and Goals

Now, Kyuubi respects Spark's behavior to generate the Driver Pod name and Executor Pod name prefix, it works well for standard workloads run on standard K8s. But if some third-party components use the pod name for other purposes, issues may occur on some edge cases, e.g. the very long but legal pod name.

### Implementation steps

1. Add new boolean configs named `kyuubi.kubernetes.spark.forciblyRewriteDriverPodName.enabled` and `kyuubi.kubernetes.spark.forciblyRewriteExecutorPodNamePrefix.enabled`.
2. check this new config in `SparkEngine` file, to help force rewrite non reach MAX_LENGTH executor pod name prefix.

### Additional context

Introduction of [2023 Kyuubi Code Contribution Program](https://github.com/apache/kyuubi/issues/5357)

**Comment by zhaohehuhu** [comment]
@zwangsheng plz assign the task to me. Thanks.
