### ISSUE TITLE
[Umbrella] Support path-based table of Delta Lake in Authz

### ISSUE THREAD

**Issue by zml1206** [apache/kyuubi#5663]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues) and found no similar issues.

### Describe the proposal

Introduce path-based table of Delta Lake support in Kyuubi Authz plugin.

### Task list

TODO

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by yaooqinn** [comment]
Thank you very much @zml1206
