### ISSUE TITLE
[FEATURE] Add PostgreSQL as backend database for kyuubi metadata

### ISSUE THREAD

**Issue by lukeyan2023** [apache/kyuubi#5674]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Add PostgreSQL as Kyuubi's metadata storage database

### Motivation

Currently, Kyuubi supports the use of SQLite and MySQL to store metadata. Although PostgreSQL can be supported through the 'CUSTOM' method, there is a certain usage cost for users. PostgreSQL ，as one of the most widely used databases,  if it can be used out of the box, will further lower the user's usage threshold

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
@lukeyan2023 Great, looking forward your contribution～

**Comment by tigrulya-exe** [comment]
@pan3793 Hi! I've implemented this feature and opened PR #6027. Could you take a look, please?

**Comment by pan3793** [comment]
@tigrulya-exe thanks, I'm looking
