### ISSUE TITLE
[TASK][EASY] Optimize kyuubi spark engine driver pod name generation

### ISSUE THREAD

**Issue by zwangsheng** [apache/kyuubi#5680]
### What's the level of this task?

EASY

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/296) and found no similar tasks.

### Mentor

- [X] I have sufficient expertise on this task, and I volunteer to be a mentor of this task to guide contributors through the task.

### Skill requirements

- Scala
- Spark Config about Spark Driver Pod Name and Spark App Name

### Background and Goals

Background:
In default case, when kyuubi submit spark sql engine on kubernetes, will generate spark driver pod name with `kyuubi--${app_name}-${engine_ref_id}-driver`. And app_name will be `kyuubi_${shareLevel}_${engineType}_${appUser}_${engineRefId}` if not set by user. In result, we may get spark driver pod name with `kyuubi-kyuubi-${shareLevel}-${engineType}-${appUser}-${engineRefId}-${engineRefId}-driver`.

We were hoping for a more concise name, such as `kyuubi-${shareLevel}-${engineType}-${appUser}-${engineRefId}-driver`.

### Implementation steps

1. modify logic in `SparkProcessBuilder#appendPodNameConf` method. 

### Additional context

Introduction of [2023 Kyuubi Code Contribution Program](https://github.com/apache/kyuubi/issues/5357)

**Comment by zhaohehuhu** [comment]
someone is doing this task, right ? @zwangsheng

**Comment by zwangsheng** [comment]
> someone is doing this task, right ? @zwangsheng

Yes, there is PR #5695 to fix this

**Comment by liaoyt** [comment]
does this still in progress?
i'm facing the issue that the pod name is too long, and hoping this issue is fixed. 
<img width="1518" alt="image" src="https://github.com/apache/kyuubi/assets/12195059/605b6346-8f35-497f-bfed-c55c8c0c67b5">
