### ISSUE TITLE
[TASK][EASY] Introduce specified initialized SQL to every engine

### ISSUE THREAD

**Issue by YesOrNo828** [apache/kyuubi#5756]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

As of nowadays,  the configuration key `kyuubi.engine.session.initialize.sql` is used in both Flink and Spark engines.  To specify the initialized SQL for each engine, we need to introduce a separate key.

For example:
`kyuubi.engine.flink.initialize.sql`
`kyuubi.session.engine.flink.initialize.sql`

`kyuubi.engine.spark.initialize.sql`
`kyuubi.session.engine.spark.initialize.sql`

### How should we improve?

Add new ConfigEntries to Flink and Spark engines

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by hadoopkandy** [comment]
I understand this task and want to have a try, l suppose l can complete it in 3 days.
