### ISSUE TITLE
[TASK][EASY] Add a scheduled thread to trigger k8s spark driver pod clean up periodically

### ISSUE THREAD

**Issue by liaoyt** [apache/kyuubi#5795]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

K8S spark driver pod clean up use guava cache as cleanup trigger with time-based eviction, but the eviction will not be triggered until any get/put operation happened. 

In our use case, wu use `Elastic Container Instance`, which are billed on a pay-as-you-go basis, to run spark on k8s. So the driver pod with `Finished` state is supports to be delete immediately.

### How should we improve?

Add a scheduled thread to evict the cache periodically.

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
Do you mean that pods in the completed state will also be billed? Are there docs for that?

**Comment by pan3793** [comment]
BTW, your proposed idea sgtm, @turboFei has a similar idea too.

**Comment by turboFei** [comment]
SGTM, would you like to raise a pr?

**Comment by liaoyt** [comment]
> SGTM, would you like to raise a pr?

yes, i will raise a pr

**Comment by pan3793** [comment]
> after diving into the related doc, i figure out that is will not be billed since container already in terminated state.
> any way, there still may exists other limitation such like namespace pod quota, etc

that's what I supposed. could you paste a docs link here?

**Comment by liaoyt** [comment]
> > after diving into the related doc, i figure out that is will not be billed since container already in terminated state.
> > any way, there still may exists other limitation such like namespace pod quota, etc
> 
> that's what I supposed. could you paste a docs link here?

of cause
https://help.aliyun.com/zh/eci/user-guide/lifecycle-of-an-elastic-container-instance-1?spm=a2c4g.11174283.0.i3
