### ISSUE TITLE
[FEATURE] Support to describe engine and de-register engine with command in current session

### ISSUE THREAD

**Issue by turboFei** [apache/kyuubi#5797]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Support to describe the engine info of current session and de-register the engine.

For example:
```
KYUUBI DESC ENGINE;
KYUUBI DEREGISTER ENGINE;
```

### Motivation

Extensions for kyuubi sql commands.

### Describe the solution

Refer: https://github.com/apache/kyuubi/issues/3926

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by Kwafoor** [comment]
some trouble in `KYUUBI DEREGISTER ENGINE;`, still working on it.

**Comment by wForget** [comment]
In what scenarios do we need to `register/de-register` the engine of current session?

**Comment by turboFei** [comment]
> In what scenarios do we need to register/de-register the engine of current session?

For USER share level, the static spark parameters(likes memory) can not take affects if the engine already existing with different static parameters.

The user might want to de-register the old one and register a new one.

**Comment by wForget** [comment]
> For USER share level, the static spark parameters(likes memory) can not take affects if the engine already existing with different static parameters.

For this case, do we need a `restart` command instead of executing `deregister` and then `register`?

If we only execute `deregister engine`, can we continue to submit subsequent operation?

**Comment by turboFei** [comment]
> > For USER share level, the static spark parameters(likes memory) can not take affects if the engine already existing with different static parameters.
> 
> 
> 
> For this case, do we need a `restart` command instead of executing `deregister` and then `register`?
> 
> 
> 
> If we only execute `deregister engine`, can we continue to submit subsequent operation?
> 
> 
> 
> 
> 
> 

restart SGTM

**Comment by Kwafoor** [comment]
> > > For USER share level, the static spark parameters(likes memory) can not take affects if the engine already existing with different static parameters.
> > 
> > 
> > For this case, do we need a `restart` command instead of executing `deregister` and then `register`?
> > If we only execute `deregister engine`, can we continue to submit subsequent operation?
> 
> restart SGTM

OK, i will use `restart ` command instead of `deregister/register`.

**Comment by Kwafoor** [comment]
issue name better change to `Support to describe engine and restart engine with command in current session`.
@turboFei

**Comment by pan3793** [comment]
@Kwafoor I narrow the scope of this ticket to "describe engine", please open a new ticket for "de-register engine"

**Comment by Kwafoor** [comment]
> @Kwafoor I narrow the scope of this ticket to "describe engine", please open a new ticket for "de-register engine"

OK
