### ISSUE TITLE
[Bug] Close KyuubiSession when OperationLog not initialized may lead log file leak

### ISSUE THREAD

**Issue by Flyangz** [apache/kyuubi#5832]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

I added some debug logs and got the below pictures.
![截屏2023-12-08 11 09 01](https://github.com/apache/kyuubi/assets/39462475/7fee96dd-c8aa-43e1-a340-3a15fa919bd7)
We can see kyuubi received a close session request and closed corresponding operation logs. Let say thread A done this work. One log was closed before initialized, so the the `OperationLog#close` call did not close writer. 
https://github.com/apache/kyuubi/blob/1d6e65356e6eab6656be6245de89a02e910304ec/kyuubi-common/src/main/scala/org/apache/kyuubi/operation/log/OperationLog.scala#L234-L235
After that, `OperationLog#write` was called by other thread B. Finally, the thread A called `SessionManager#deleteOperationLogSessionDir` and cause log file leak.
![截屏2023-12-08 11 15 04](https://github.com/apache/kyuubi/assets/39462475/ec7deb07-1961-4909-a6c6-89bdd08f6047)

### Affects Version(s)

1.7.1 with #5211 patch

### Additional context

Maybe we can delete `if (!initialized) return` to fix it?

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
Seems solved by https://github.com/apache/kyuubi/pull/5211

**Comment by Flyangz** [comment]
> Seems solved by #5211

Sorry that I have not mentioned the #5211 had been patched. We applied it when we first discovered the leak, but it didn't work.
