### ISSUE TITLE
Bump Spark 3.4.2

### ISSUE THREAD

**Issue by zml1206** [apache/kyuubi#5856]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

https://spark.apache.org/releases/spark-release-3-4-2.html

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by sunny-fffff** [comment]
Team, does it mean Kyuubi 1.8.1 only supports Spark 3.4.2?

**Comment by pan3793** [comment]
No. [Release Notes - 1.8.0](https://kyuubi.apache.org/release/1.8.0.html)

> Fully verified with Spark 3.1, 3.2, 3.3, and 3.4, initial support Spark 3.5
