### ISSUE TITLE
[Bug] When the engine is specified as HIVE_SQL in Kyuubi , the desensitization policy configured in ranger in hive does not take effect

### ISSUE THREAD

**Issue by wardlican** [apache/kyuubi#5878]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

When the engine is specified as HIVE_SQL in Kyuubi version 1.6.0, the desensitization policy configured in ranger in hive does not take effect.

kyuubi login information is as follows
beeline -u "jdbc:hive2://xxx.xxx.xxx.xxx:10009/;principal=hadoop/xxx.xxx.xxx@xxx;#kyuubi.engine.share.level=CONNECTION;kyuubi.engine.type=HIVE_SQL;"

<img width="1477" alt="image" src="https://github.com/apache/kyuubi/assets/95597038/a4b82ccd-53d6-4d9d-a0d9-4ae0bed7dfd4">

When using hive's beeline to connect with the same user, the ranger desensitization strategy is normal.
<img width="803" alt="image" src="https://github.com/apache/kyuubi/assets/95597038/b8e517cc-60f3-4ed4-8a23-22d0782e3133">

hive version is:3.1.3
kyuubi and hive server2 use same hive config

### Affects Version(s)

1.6.0

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [X] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
cc @Yikf

**Comment by Yikf** [comment]
Thanks @wardlican for reporting the issue.
Could you please provide a startup command for the kyuubi hive engine? (you can check it in the kyuubi server/beeline openSession log).

Also, you can check whether the HiveServer2 home directory is the same as the kyuubi hive engine home directory.

If they are the same, you can copy the configuration items of hiveserver2-site.xml to hive-site.xml. If after that step it workaround the problem. It may have hit my next guess, that is kyuubi uses `new HiveConf()` to initialize hive configuration, but this method does not load `hiveserver2-site.xml`. Some configurations of the ranger hive plugin exist in `hiveserver2-site.xml`. That say, the hive plugin may not be enabled under the kyuubi hive engine.

**Comment by wardlican** [comment]
> erver
here is  the startup command of the kyuubi hive engine
KyuubiSessionManager-exec-pool: Thread-201 org.apache.kyuubi.engine.EngineRef: Launching engine:
/usr/local/jdk/bin/java
-Xmx1g
-cp
/data/ward/kyuubi/externals/engines/hive/kyuubi-hive-sql-engine_2.12-1.6.0.jar:/usr/local/service/hive/conf:/usr/local/service/hadoop/etc/hadoop:/usr/local/service/hive/lib/*:/usr/local/service/hive/lib/*:/usr/local/service/hive/spark/jars/*:/usr/local/service/tez/*:/usr/local/service/tez/lib/*:/usr/local/service/hive/lib/ranger-hive-plugin-impl/*
org.apache.kyuubi.engine.hive.HiveSQLEngine
--conf
kyuubi.session.user=hadoop
--conf
kyuubi.engine.id=bd8e2fdf-1455-475a-8fab-b58726b3ca5b
--conf
hive.engine.name=kyuubi_CONNECTION_HIVE_SQL_hadoop_bd8e2fdf-1455-475a-8fab-b58726b3ca5b
--conf
hive.metastore.uris=thrift://172.16.0.21:7004
--conf
hive.server2.thrift.resultset.default.fetch.size=1000
--conf
kyuubi.authentication.ldap.base.dn=ou=People,dc=emr,dc=cloud,dc=tencent,dc=com
--conf
kyuubi.client.ipAddress=172.16.0.21
--conf
kyuubi.engine.credentials=SERUUwACFGhhLWhkZnM6SERGUzc4MDAwMDAyQgAGaGFkb29wBmhhZG9vcCBoYWRvb3AvMTcyLjE2
LjAuNDFAVEJEUy05OTdIWFNCSIoBjIu2h66KAYyvwwuujgQ+FhTJ1mqcjnlG0Ys7FRMWKE1w4HIQ
qRVIREZTX0RFTEVHQVRJT05fVE9LRU4UaGEtaGRmczpIREZTNzgwMDAwMDIzdGhyaWZ0Oi8vMTcy
LjE2LjAuNDE6NzAwNCx0aHJpZnQ6Ly8xNzIuMTYuMC4yMTo3MDA0QAAGaGFkb29wBmhhZG9vcCBo
YWRvb3AvMTcyLjE2LjAuNDFAVEJEUy05OTdIWFNCSIoBjIu2h7aKAYyvwwu2DwEUrQDw1ICpe6fq
Q6+faOMKH9MrHAYVSElWRV9ERUxFR0FUSU9OX1RPS0VOAAA=
--conf
kyuubi.engine.share.level=CONNECTION
--conf
kyuubi.engine.submit.time=1703152850048
--conf
kyuubi.engine.type=HIVE_SQL
--conf
kyuubi.frontend.protocols=THRIFT_BINARY,REST
--conf
kyuubi.frontend.thrift.binary.ssl.enabled=true
--conf
kyuubi.ha.engine.ref.id=bd8e2fdf-1455-475a-8fab-b58726b3ca5b
--conf
kyuubi.ha.namespace=/kyuubi_1.6.0_CONNECTION_HIVE_SQL/hadoop/bd8e2fdf-1455-475a-8fab-b58726b3ca5b
--conf
kyuubi.ha.zookeeper.acl.enabled=false
--conf
kyuubi.ha.zookeeper.quorum=172.16.0.32:2181,172.16.0.29:2181,172.16.0.25:2181
--conf
kyuubi.metadata.cleaner.interval=PT30M
--conf
kyuubi.metadata.max.age=PT72H
--conf
kyuubi.metrics.enabled=true
--conf
kyuubi.metrics.json.interval=PT5S
--conf
kyuubi.metrics.json.location=metrics
--conf
kyuubi.metrics.prometheus.path=/metrics
--conf
kyuubi.metrics.prometheus.port=10019
--conf
kyuubi.metrics.reporters=JSON,JMX,PROMETHEUS
--conf
kyuubi.server.ipAddress=172.16.0.41
--conf
kyuubi.session.connection.url=172.16.0.41:10009
--conf
kyuubi.session.engine.trino.connection.catalog=hive
--conf
kyuubi.session.engine.trino.connection.url=http://172.16.0.21:9000
--conf
kyuubi.session.real.user=hadoop
--conf
spark.master=yarn

and i tryed copy the property to hive-site.xml ,the result is same.

**Comment by Yikf** [comment]
@wardlican Does basic authentication take effect?

**Comment by Yikf** [comment]
Hi @wardlican , the distribution runable I compiled from [branch 1.6](https://github.com/apache/kyuubi/tree/branch-1.6) and copy `hiveserver2-site.xml` config items to `hive-site.xml` does not reproduce your problem.

user `yikaifei2` has MASKING policy
```
0: jdbc:hive2://xxx:1> select * from default.t2;
2023-12-21 21:10:48.322 INFO org.apache.kyuubi.operation.ExecuteStatement: Processing yikaifei2's query[a0d00946-761a-4c8a-89fd-554df75df175]: PENDING_STATE -> RUNNING_STATE, statement:
select * from default.t2
2023-12-21 21:10:48.323 INFO org.apache.kyuubi.operation.ExecuteStatement: Query[a0d00946-761a-4c8a-89fd-554df75df175] in FINISHED_STATE
2023-12-21 21:10:48.324 INFO org.apache.kyuubi.operation.ExecuteStatement: Processing yikaifei2's query[a0d00946-761a-4c8a-89fd-554df75df175]: RUNNING_STATE -> FINISHED_STATE, time taken: 0.002 seconds
+----------------------------------------------------+
|                      t2.name                       |
+----------------------------------------------------+
| c2ad66ef155d00ff0d8f1163f04c24148d93e07d2c78200672f416bb3a183c52 |
+----------------------------------------------------+
1 row selected (0.134 seconds)
0: jdbc:hive2://xxx:1> select current_user();
2023-12-21 21:11:29.665 INFO org.apache.kyuubi.operation.ExecuteStatement: Processing yikaifei2's query[aab12815-413d-4ccd-85aa-f71ff0e30de2]: PENDING_STATE -> RUNNING_STATE, statement:
select current_user()
2023-12-21 21:11:29.667 INFO org.apache.kyuubi.operation.ExecuteStatement: Query[aab12815-413d-4ccd-85aa-f71ff0e30de2] in FINISHED_STATE
2023-12-21 21:11:29.667 INFO org.apache.kyuubi.operation.ExecuteStatement: Processing yikaifei2's query[aab12815-413d-4ccd-85aa-f71ff0e30de2]: RUNNING_STATE -> FINISHED_STATE, time taken: 0.001 seconds
+------------+
|    _c0     |
+------------+
| yikaifei2  |
+------------+
1 row selected (0.092 seconds)
0: jdbc:hive2://yq01-rdw-dev.yq01.baidu.com:1>
```

user `yikaifei` has no MASKING policy
```
0: jdbc:hive2://xxx:1> select current_user();
2023-12-21 21:11:48.081 INFO org.apache.kyuubi.operation.ExecuteStatement: Processing yikaifei's query[56e71aa0-57ba-43e4-baf1-834177d62085]: PENDING_STATE -> RUNNING_STATE, statement:
select current_user()
2023-12-21 21:11:48.082 INFO org.apache.kyuubi.operation.ExecuteStatement: Query[56e71aa0-57ba-43e4-baf1-834177d62085] in FINISHED_STATE
2023-12-21 21:11:48.083 INFO org.apache.kyuubi.operation.ExecuteStatement: Processing yikaifei's query[56e71aa0-57ba-43e4-baf1-834177d62085]: RUNNING_STATE -> FINISHED_STATE, time taken: 0.002 seconds
+-----------+
|    _c0    |
+-----------+
| yikaifei  |
+-----------+
1 row selected (0.175 seconds)
0: jdbc:hive2://xxx:1> select * from default.t2;
2023-12-21 21:11:49.906 INFO org.apache.kyuubi.operation.ExecuteStatement: Processing yikaifei's query[369aae55-d4fe-4912-9120-658d8963f2e6]: PENDING_STATE -> RUNNING_STATE, statement:
select * from default.t2
2023-12-21 21:11:49.908 INFO org.apache.kyuubi.operation.ExecuteStatement: Query[369aae55-d4fe-4912-9120-658d8963f2e6] in FINISHED_STATE
2023-12-21 21:11:49.908 INFO org.apache.kyuubi.operation.ExecuteStatement: Processing yikaifei's query[369aae55-d4fe-4912-9120-658d8963f2e6]: RUNNING_STATE -> FINISHED_STATE, time taken: 0.001 seconds
+-----------------+
|     t2.name     |
+-----------------+
| heiheihahadasd  |
+-----------------+
1 row selected (0.078 seconds)
0: jdbc:hive2://xxx:1>
```

for user `yikaifei2`,  the value of `t2.name` is hashed.

![image](https://github.com/apache/kyuubi/assets/51110188/2b27e760-5b34-470c-ab33-5bc2a63f3b02)


I think that you should check the plugin wether was been enabled. you can view the ranger ui plugin status page or the local policy cache directory.
