### ISSUE TITLE
[FEATURE] Support to delete the engine node from ha namespace if failed to connect to engine host:port

### ISSUE THREAD

**Issue by turboFei** [apache/kyuubi#5900]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Support to delete the engine node from ha namespace if failed to connect to engine host:port

Now if this situation happen(for example, hive client initialization failed because of issue), we have to delete the engine manually.

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
The feature is useful in certain cases, but specific to the case you list, should be resolved by https://github.com/apache/kyuubi/issues/5331

> hive client initialization failed because of issue

**Comment by turboFei** [comment]
The hive client init succeeded when stating the engine, and it connected to old hivemetastore server.

Then we made some migration and shutdown the old hivemetastore server. and then the hive client can be initialized for new connections.
