### ISSUE TITLE
[Bug] Kyuubi BeeLine should check the relocated TTransportException

### ISSUE THREAD

**Issue by hadoopkandy** [apache/kyuubi#5918]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

When Kyuubi beeline executes incorrect SQL,it will exit with exception:
java.lang.NoClassDefFoundError: org/apache/thrift/transport/TTransportException

### Affects Version(s)

1.8.0

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by cxzl25** [comment]
Affects Version maybe `master` ?  `1.8.0` should not have this problem.
