### ISSUE TITLE
[Bug] Gluten-it doesn't seem to be executing as expected

### ISSUE THREAD

**Issue by ulysses-you** [apache/kyuubi#5939]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Gluten project has upgraded the version to 1.2.0-snapshot, but the gluten-it CI still pass. See the log :
https://github.com/apache/kyuubi/actions/runs/7393303592/job/20114021946

We should make sure the tpcds/tpch query plan is transformed.

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by ulysses-you** [comment]
cc @Kwafoor do you have time to take a look ?

**Comment by Kwafoor** [comment]
> cc @Kwafoor do you have time to take a look ?

OK, i will fix it.

**Comment by Kwafoor** [comment]
https://github.com/apache/kyuubi/actions/runs/7393303592/job/20113027850

![image](https://github.com/apache/kyuubi/assets/25627922/615d1603-cb80-4099-b446-c962d6996e39)

maybe reason is this.

![image](https://github.com/apache/kyuubi/assets/25627922/e0c8665e-61e7-410a-bb0c-9193b271eea8)

**Comment by Kwafoor** [comment]
> maybe reason is this, sorry for my mistake, i will fix it soon.
> 
> ![image](https://private-user-images.githubusercontent.com/25627922/293880667-e0c8665e-61e7-410a-bb0c-9193b271eea8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzODIxOTQsIm5iZiI6MTcwNDM4MTg5NCwicGF0aCI6Ii8yNTYyNzkyMi8yOTM4ODA2NjctZTBjODY2NWUtNjFlNy00MTBhLWJiMGMtOTE5M2IyNzFlZWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDE1MjQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1YTRmOGU0M2M5MmM5MzAyOTg1ODg5YWJhYmJkYWMxMjNjNjY1NTBkNTQyMzY5NWE5YTk5MGUxZTA5YzVlOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QRiKO5IeHK3l2yCpoQVFMQEkGSKcy1XgiG3lcAm_eGE)

https://github.com/Kwafoor/incubator-kyuubi/actions/runs/7408085340

**Comment by Kwafoor** [comment]
> > maybe reason is this, sorry for my mistake, i will fix it soon.
> > ![image](https://private-user-images.githubusercontent.com/25627922/293880667-e0c8665e-61e7-410a-bb0c-9193b271eea8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzODIxOTQsIm5iZiI6MTcwNDM4MTg5NCwicGF0aCI6Ii8yNTYyNzkyMi8yOTM4ODA2NjctZTBjODY2NWUtNjFlNy00MTBhLWJiMGMtOTE5M2IyNzFlZWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDE1MjQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1YTRmOGU0M2M5MmM5MzAyOTg1ODg5YWJhYmJkYWMxMjNjNjY1NTBkNTQyMzY5NWE5YTk5MGUxZTA5YzVlOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QRiKO5IeHK3l2yCpoQVFMQEkGSKcy1XgiG3lcAm_eGE)
> 
> expected CI fail https://github.com/Kwafoor/incubator-kyuubi/actions/runs/7408085340

![image](https://github.com/apache/kyuubi/assets/25627922/4c862f32-d144-47c8-b077-991121c94306)


gluten version upgrade `1.2.0-SNAPSHOT` CI https://github.com/Kwafoor/incubator-kyuubi/actions/runs/7411523117
