### ISSUE TITLE
[Bug] Error occurs on clicking on the Spark UI Kyuubi Query Engine tab

### ISSUE THREAD

**Issue by Emor-nj** [apache/kyuubi#5966]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

When I compile and package the source code downloaded from the Kyuubi official website instead of using the code from the GitHub repository, Clicking on the Kyuubi Query Engine tab results in an error: "HTTP ERROR 500 java.lang.StringIndexOutOfBoundsException: String index out of range: 7"。
![image](https://github.com/apache/kyuubi/assets/97283774/13897e87-cc5f-4ada-a1b0-10348f96dca6).
The reason is that the variables branch, revision, revisionTime, and repoUrl in package.scala are empty strings (""). This leads to an array index out of bounds error when accessing REVISION.substring(0, 7).

### Affects Version(s)

master/1.8.0

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
I see, the downloaded source code does not has git history, thus the revision related properties are ""
