### ISSUE TITLE
[TASK][EASY] Kyuubi Server HA&ZK get server from serverHosts support more strategy

### ISSUE THREAD

**Issue by davidyuan1223** [apache/kyuubi#6034]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

The current Kyuubi HA mode, which retrieves servers from ZooKeeper, only supports the random strategy. This may lead to an overload on certain nodes. Therefore, in order to address the overload issue, it is necessary to support more strategies.

### How should we improve?

Update Kyuubi Hive JDBC to support ZooKeeperClientHelper to support more strategies, currently, there are two strategy:
1. Random
2. Polling

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by davidyuan1223** [comment]
@wForget @pan3793

**Comment by pan3793** [comment]
SGTM, and it's better to extract an Interface to allow user to implement their custom strategy

**Comment by davidyuan1223** [comment]
> SGTM, and it's better to extract an Interface to allow user to implement their custom strategy

hello, want ask a question, kyuubi-hive-jdbc is only a driver engine, which cannot read configuration from the kyuubiConf, so if we set a strategy configEntry in HA, the kyuubi-hive-jdbc also cannot read the config, the only way i think is to add in connection params, but if add in connection params, we cannot custom our strategy, what do you think?

**Comment by sunnyzhuzhu** [comment]
@davidyuan1223 hello, May I ask what strategy will you implement?

**Comment by davidyuan1223** [comment]
> @davidyuan1223 hello, May I ask what strategy will you implement?

sorry, forget response, curruntly, i implemented poll and random, because hive-jdbc module is a single module, we can not use kyuubi-ha module, so, if we want implemented more strategies, we only can add strategy in connection params, like '&zkStartegy=poll/random', if you have more useful starategy, you can give me some advice

**Comment by davidyuan1223** [comment]
> @davidyuan1223 hello, May I ask what strategy will you implement?

hello, this is the demo command 
`bin/beeline -u 'jdbc:hive2://xxx:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=kyuubi;zooKeeperStrategy=poll?spark.app.name=testspark;spark.shuffle.useOldFetchProtocol=true' -n hadoop --verbose=true --showNestedErrs=true`
currently it can use poll strategy to choose the right server, but there are some bugs, so i'm not commit a pr.

**Comment by davidyuan1223** [comment]
> > @davidyuan1223 hello, May I ask what strategy will you implement?
> 
> hello, this is the demo command `bin/beeline -u 'jdbc:hive2://xxx:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=kyuubi;zooKeeperStrategy=poll?spark.app.name=testspark;spark.shuffle.useOldFetchProtocol=true' -n hadoop --verbose=true --showNestedErrs=true` currently it can use poll strategy to choose the right server, but there are some bugs, so i'm not commit a pr.

i plan the user could implemented a interface named org.apache.kyuubi.jdbc.hive.strategy.ChooseServerStrategy, then use zooKeeperStrategy=xxx.xxx.xxx, so user can use themselves implement plan, of course, if you have more effective plan, you can offered me, and i will try to implement them
