### ISSUE TITLE
[Improvement] Performance Improvement for converting spark rows to thrift rows

### ISSUE THREAD

**Issue by yaooqinn** [apache/kyuubi#6070]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

https://issues.apache.org/jira/browse/SPARK-47085 reported an issue, scala Seq.apply has O(n) complexity so that we shall avoid it

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [X] No. I cannot submit a PR at this time.

**Comment by Kwafoor** [comment]
Please assgin to me, thanks.

**Comment by yaooqinn** [comment]
thank you @Kwafoor

**Comment by hh-cn** [comment]
@pan3793 hi, can we reopen this issue, as we have discussed in [,](https://github.com/apache/kyuubi/pull/6077) this problem has not been fully solved, the TColumnGenerator.getColumnToList was missed
