### ISSUE TITLE
[Improvement] [MINOR] Add .java-version into git ignore

### ISSUE THREAD

**Issue by yanghua** [apache/kyuubi#6071]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

git ignore file

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by yanghua** [comment]
`.jave-version` is generated by `jenv`. `jenv` is a popular Java environment management tool.

**Comment by pan3793** [comment]
SGTM
