### ISSUE TITLE
[TASK][MEDIUM]  Web UI support Basic authN 

### ISSUE THREAD

**Issue by beryllw** [apache/kyuubi#6079]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

https://github.com/apache/kyuubi/pull/6042#issuecomment-1959437519

### How should we improve?

Support Basic authN for Web UI - that means, when SASL/Plain(LDAP/JDBC/CUSTOM) auth method is configured, pop something like below to allow user login via username and password 

![image](https://github.com/apache/kyuubi/assets/26535726/0dfcad64-6c50-42d4-98b1-496c43d6c03c)

### Are you willing to submit PR?

- [x] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by zwangsheng** [comment]
Hi @Kwafoor, any progress here?

**Comment by Kwafoor** [comment]
> Hi @Kwafoor, any progress here?

Still in progress.It may take a week.

**Comment by pan3793** [comment]
Promoted this to a contribution program task, classify it to EASY level temporarily, and we can re-evaluate the level after completing.

@beryllw please let me know if you still want to take this task

**Comment by beryllw** [comment]
> @beryllw please let me know if you still want to take this task

yes, i will do it soon.

**Comment by pan3793** [comment]
The task takes more effort than I thought initially, escalating the task level from easy to medium.
