### ISSUE TITLE
Upgrade Spark from 3.5.0 to 3.5.1

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#6094]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Why do we need to upgrade this artifact?

Regular Updates

### Artifact Name

https://mvnrepository.com/search?q=spark-core

### Target Version

3.5.1

### Notable Changes

Spark 3.5.1 is available now, the official release notes are on the way. 

- Vote Result: https://lists.apache.org/thread/hpkrbdwfrzq3r19z89zn4wd9gt0dhwvo
- Documentation: https://spark.apache.org/docs/3.5.1/
- Binary: https://downloads.apache.org/spark/spark-3.5.1/
- PySpark: https://pypi.org/project/pyspark/3.5.1/
- Maven Central: https://repo1.maven.org/maven2/org/apache/spark/spark-core_2.13/3.5.1/

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by GGHWS** [comment]
please assgin to me, thanks

**Comment by pan3793** [comment]
@GGHWS thanks, assigned
