### ISSUE TITLE
Upgrade Jackson from 2.15.0 to 2.15.4

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#6101]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Why do we need to upgrade this artifact?

Regular Updates

### Artifact Name

https://mvnrepository.com/search?q=jackson

### Target Version

2.15.4

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by Emor-nj** [comment]
please assgin to me, thanks

**Comment by Deepali1211** [comment]
Can you please assign to me?
