### ISSUE TITLE
[TASK][EASY] Web SQL Editor supports run SQL snippets

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#6248]
### What's the level of this task?

EASY

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/343) and found no similar tasks.

### Mentor

- [X] I have sufficient expertise on this task, and I volunteer to be a mentor of this task to guide contributors through the task.

### Skill requirements

- Knowledge of how to run Kyuubi server
- Basic knowledge of Vue and front-end stacks

### Background and Goals

Currently, when you click the "Run" button on Kyuubi Web SQL Editor, all content in the text box will be sent to the backend service to execute.

The expected behavior is,

- when no text is selected, send all content
- when some text is selected, only send the selected text.

<img width="1161" alt="image" src="https://github.com/apache/kyuubi/assets/26535726/c50e8193-c594-4bc1-990e-681afd32d1c0">

### Implementation steps

Change code under `kyuubi/server/web-ui`, and do test.

### Additional context

Introduction of [2024H1 Kyuubi Code Contribution Program](https://github.com/apache/kyuubi/issues/6232)

**Comment by silentxingtian** [comment]
Please assign this task to me, I will implement it

**Comment by pan3793** [comment]
@silentxingtian thanks, assigned

**Comment by pan3793** [comment]
After offline discussion, revoke the assignment and leave it to other contributors.

**Comment by dupen01** [comment]
plz assign to me

**Comment by pan3793** [comment]
@dupen01 thanks, assgined
