### ISSUE TITLE
[TASK][EASY] Drop support for Flink 1.16

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#6249]
### What's the level of this task?

EASY

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/343) and found no similar tasks.

### Mentor

- [X] I have sufficient expertise on this task, and I volunteer to be a mentor of this task to guide contributors through the task.

### Skill requirements

- Basic knowledge of Scala, Flink, GitHub Actions

### Background and Goals

We have already deprecated the support for Flink 1.16 in 1.9.0(https://github.com/apache/kyuubi/pull/6142), now, we'd like to drop the support for Flink 1.16 and obliterate the related code.

### Implementation steps

- Update code of `kyuubi-flink-sql-engine`
- Update CI(GHA workflow)
- Update docs (quick start, migration guide, etc.)

### Additional context

Introduction of [2024H1 Kyuubi Code Contribution Program](https://github.com/apache/kyuubi/issues/6232)

**Comment by slfan1989** [comment]
@pan3793 Can I assign this issue?

**Comment by pan3793** [comment]
@slfan1989 thanks, assigned
