### ISSUE TITLE
[TASK][EASY] Drop support for Spark 3.1

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#6250]
### What's the level of this task?

EASY

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/343) and found no similar tasks.

### Mentor

- [X] I have sufficient expertise on this task, and I volunteer to be a mentor of this task to guide contributors through the task.

### Skill requirements

- Basic knowledge of Scala, Spark, GitHub Actions

### Background and Goals

We have already deprecated the support for Spark 3.1 in 1.9.0(https://github.com/apache/kyuubi/pull/6091), now, we'd like to drop the support for Spark 3.1 and obliterate the related code.

### Implementation steps

- Update code of `kyuubi-spark-sql-engine`
- Update CI(GHA workflow)
- Update docs (quick start, migration guide, etc.)

### Additional context

Introduction of [2024H1 Kyuubi Code Contribution Program](https://github.com/apache/kyuubi/issues/6232)

**Comment by liuxiaocs7** [comment]
Hi, @pan3793, i want to have a try, plz assign to me if possible.

**Comment by pan3793** [comment]
@liuxiaocs7 thanks, assigned.

**Comment by pan3793** [comment]
@liuxiaocs7 Do you have any progress on this task? An easy task typically costs a few hours to complete.

**Comment by liuxiaocs7** [comment]
> @liuxiaocs7 Do you have any progress on this task? An easy task typically costs a few hours to complete.

Hi, @pan3793, sorry for late, on the way.
