### ISSUE TITLE
[TASK][EASY] Upgrade hive-service-rpc 4.0.0

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#6252]
### What's the level of this task?

EASY

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/343) and found no similar tasks.

### Mentor

- [X] I have sufficient expertise on this task, and I volunteer to be a mentor of this task to guide contributors through the task.

### Skill requirements

- Knowledge of Thrift, Apache Release process, class Shading and Relocation

### Background and Goals

Apache Hive released 4.0.0 on 29 March 2024
https://hive.apache.org/general/downloads/

Upgrading `hive-service-rpc` from 3.1.3 to 4.0.0, brings 3 changes.

- https://issues.apache.org/jira/browse/HIVE-14388
- https://issues.apache.org/jira/browse/HIVE-24230
- https://issues.apache.org/jira/browse/HIVE-24893

Kyuubi uses a shaded hive-service-rpc 3.1.3 as the internal RPC protocol
https://github.com/apache/kyuubi-shaded/tree/master/kyuubi-relocated-hive-service-rpc

### Implementation steps

- Bump `hive-service-rpc` 4.0.0 in https://github.com/apache/kyuubi-shaded
- Release `kyuubi-shaded` 0.4.0 (A Committer will help to complete this step)
- Consume `kyuubi-shaded` 0.4.0 and tune code in Kyuubi code
- Investigate and implement the new interface (may be completed in independent tasks)

### Additional context

Introduction of [2024H1 Kyuubi Code Contribution Program](https://github.com/apache/kyuubi/issues/6232)

**Comment by zhaohehuhu** [comment]
Please assign this task to me

**Comment by pan3793** [comment]
@zhaohehuhu thanks, assigned
