### ISSUE TITLE
[TASK][MEDIUM] Support running JDBC engine on YARN AM

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#6253]
### What's the level of this task?

MEDIUM

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/343) and found no similar tasks.

### Mentor

- [X] I have sufficient expertise on this task, and I volunteer to be a mentor of this task to guide contributors through the task.

### Skill requirements

- Knowledge of Scala, Kyuubi architecture, Apache YARN
- Kerberos and Hadoop Security (optional)

### Background and Goals

Kyuubi supports running the Hive engine on YARN AM (Application Master) since 1.9.0, see https://github.com/apache/kyuubi/pull/5868 and https://github.com/apache/kyuubi/pull/6199, it removes the requirement of running engine process on Kyuubi Server's machine but moves to YARN cluster, just like Spark on YARN cluster mode and Flink YARN application mode.

We'd like to see similar functionalities for the JDBC engine.

### Implementation steps

Refer to the Hive engine implementation to complete the code, test, CI, etc.

### Additional context

Introduction of [2024H1 Kyuubi Code Contribution Program](https://github.com/apache/kyuubi/issues/6232)

This may help for testing https://github.com/awesome-kyuubi/hadoop-testing

**Comment by lsm1** [comment]
i want to have a try, plz assign to me if possible.

**Comment by pan3793** [comment]
@lsm1 thanks
