### ISSUE TITLE
[TASK][EASY] Kyuubi BeeLine supports JSON output format

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#6266]
### What's the level of this task?

EASY

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/343) and found no similar tasks.

### Mentor

- [ ] I have sufficient expertise on this task, and I volunteer to be a mentor of this task to guide contributors through the task.

### Skill requirements

Knowledge of Java, Beeline, JSON

### Background and Goals

Similar to HIVE-20447, we'd like to have JSON output format support in Kyuubi BeeLine.

### Implementation steps

Refer to HIVE-20447

### Additional context

Introduction of [2024H1 Kyuubi Code Contribution Program](https://github.com/apache/kyuubi/issues/6232)

**Comment by slfan1989** [comment]
@pan3793 Can I assign this issue? This seems to be a Hive related task.

**Comment by pan3793** [comment]
@slfan1989 thanks, assigned. Actually, we forked BeeLine from Apache Hive 3.1.3 https://github.com/apache/kyuubi/pull/6109 to gain the flexibility of feature extending and get rid of Hive dependency hell ...
