### ISSUE TITLE
[TASK][EASY] Update DB state when the query fallback to yarn and the batch app is terminal

### ISSUE THREAD

**Issue by yanghua** [apache/kyuubi#6278]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

In scenarios with high concurrency for submitting batch sessions and querying status concurrently, especially when there are a large number of short-period batch session submissions, if some Kyuubi servers crash, it will impose significant pressure on the remaining Kyuubi servers. This is because at this time, they are unable to query the information of some batch sessions in their memory. Therefore, we should try to stack the pressure of this scenario onto YARN as much as possible. 

### How should we improve?

Therefore, I suggest that if a job reaches its final state, we should update the database as soon as possible to avoid further degradation of performance as much as possible.

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
cc @turboFei
