### ISSUE TITLE
[TASK][MEDIUM] Setup GitHub Actions for Kyuubi Python client (former PyHive)

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#6281]
### What's the level of this task?

MEDIUM

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/343) and found no similar tasks.

### Mentor

- [ ] I have sufficient expertise on this task, and I volunteer to be a mentor of this task to guide contributors through the task.

### Skill requirements

- GitHub Actions
- Python/Shell scripts
- Hadoop components deployment

### Background and Goals

PyHive has been donated to Apache Kyuubi, the codebase was imported into main repo under `./python`, previously, it used Travis for CI, now, we should migrate the workflow to GitHub Actions.

https://incubator.apache.org/ip-clearance/kyuubi-pyhive.html

### Implementation steps

- Migrate existing CI workflow to GitHub Actions
- Add Spark Thrift Server / Kyuubi to CI workflow

### Additional context

Introduction of [2024H1 Kyuubi Code Contribution Program](https://github.com/apache/kyuubi/issues/6232)

**Comment by sudohainguyen** [comment]
I can help, please assign this PR to me

**Comment by pan3793** [comment]
@sudohainguyen thanks, assigned. And you are welcome to improve this new Python module～

**Comment by pan3793** [comment]
@sudohainguyen hi, do you have any progress on this task?

**Comment by sudohainguyen** [comment]
working on it @pan3793 
will have a PR this weekend

**Comment by sudohainguyen** [comment]
update: since most of the tasks were running on outdated python versions, think we should implement entirely different ones
targeting primarily on python 3.9 and 3.10, will extend afterwards

**Comment by pan3793** [comment]
@sudohainguyen thanks for updating, starting from Python 3.9 and 3.10 SGTM
