### ISSUE TITLE
[TASK][TRIVIAL] Improve message of distribution built without enabling web ui

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#6283]
### What's the level of this task?

TRIVIAL

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/343) and found no similar tasks.

### Mentor

- [ ] I have sufficient expertise on this task, and I volunteer to be a mentor of this task to guide contributors through the task.

### Skill requirements

- How to build and run Kyuubi
- Basic HTML and English writing skills

### Background and Goals

The building of Web UI is optional, user must enable `--web-ui` on creating distributions when using `build/dist` tool to create binary distributions, e.g. 
```
./build/dist --tgz --web-ui --spark-provided --flink-provided --hive-provided
``` 

Otherwise, if you access the web ui, only the following dummy page shows.

<img width="851" alt="image" src="https://github.com/apache/kyuubi/assets/26535726/bdb8fcc8-793e-4ded-8317-3dc2b7fffb78">

### Implementation steps

Enhance `kyuubi-server/src/main/resources/dist/index.html` to improve the message.

### Additional context

Introduction of [2024H1 Kyuubi Code Contribution Program](https://github.com/apache/kyuubi/issues/6232)

**Comment by dupen01** [comment]
What do you want this page to display? Please describe in detail.
