### ISSUE TITLE
[TASK][EASY] Upgrade Arrow from 12.0.0 to 15.0.2

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#6293]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Why do we need to upgrade this artifact?

Usage of New Features

### Artifact Name

https://mvnrepository.com/search?q=arrow

### Target Version

15.0.2

### Notable Changes

Two main reasons

- Arrow 14.0.0 supports Java 21 https://github.com/apache/arrow/issues/36994
- Arrow 15.0.0 supports Netty 4.1.103 and above https://github.com/apache/arrow/issues/39265

Also some bug fixes

Note: After changing the corresponding dependency version and before submitting your pull request, it is necessary to execute `build/dependency.sh --replace` locally to update `dev/dependencyList`, if some dependencies are added or removed, the corresponding LICENSE/NOTICE should also be updated for legal purposes. For some dependencies packaged into shaded jars, shading and relocation rules should be updated too.

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by dupen01** [comment]
Hi, please assign it to me, I will submit a PR later today.
