### ISSUE TITLE
[TASK][EASY] Simplify Netty and gRPC dependency management

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#6294]
### What's the level of this task?

EASY

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/343) and found no similar tasks.

### Mentor

- [ ] I have sufficient expertise on this task, and I volunteer to be a mentor of this task to guide contributors through the task.

### Skill requirements

- Familiar with Maven, and Java dependency management.

### Background and Goals

`netty-all` pulls all(maybe?) Netty jars, some are not used by Kyuubi, we should analyze and prune those jars.

### Implementation steps

Find and remove unused jars(not limited to netty), and make CI happy.

### Additional context

Introduction of [2024H1 Kyuubi Code Contribution Program](https://github.com/apache/kyuubi/issues/6232)

**Comment by PorterZhang2021** [comment]
Hello, Mr.Pan, I would like to give it a try, but I may not be sure how to clean up these dependencies, so I search some infomation in web, then I learn that I can use `mvn dependency:analyze` to find unused declared dependencies.

The following are the steps I want to take:
1. Use the `mvn depndency:analyze` command to find all unused declared dependencies
2. Go to different `pom. XML` to clear these dependencies
3. Re package and verify to see if it can be successfully packaged

If you think there is no problem with my thinking, you can assign this task to me. Thanks.

**Comment by pan3793** [comment]
your steps should work, but step 2 could be narrowed to root `pom.xml` because Kyuubi manages all dependency version and exclusions in root `pom.xml`(except for some corner cases). and step 3 could be simplified by `dev/dependency.sh`

**Comment by PorterZhang2021** [comment]
> your steps should work, but step 2 could be narrowed to root `pom.xml` because Kyuubi manages all dependency version and exclusions in root `pom.xml`(except for some corner cases). and step 3 could be simplified by `dev/dependency.sh`

Ok, thanks, Mr.Pan. I will try it, please assign this task to me.

**Comment by pan3793** [comment]
@PorterZhang2021 thanks, assigned
