### ISSUE TITLE
[TASK][EASY][HELM] ServiceMonitor not able to discover kyuubi service

### ISSUE THREAD

**Issue by sudohainguyen** [apache/kyuubi#6298]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

After deploying kyuubi using helm chart in the repo, my prometheus can not retrieve metrics from kyuubi server.
Found out that ServiceMonitor matchlabels only have `app: {{ .Release.name }}` and it doesn't match any of headless service labels.

Solution: include template kyuubi.selectorLabels instead

### Affects Version(s)

master

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
thanks for reporting this issue, looking forward your PR~
