### ISSUE TITLE
[TASK][EASY] Support disabling Web UI

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#6299]
### What's the level of this task?

EASY

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/343) and found no similar tasks.

### Mentor

- [ ] I have sufficient expertise on this task, and I volunteer to be a mentor of this task to guide contributors through the task.

### Skill requirements

Scala programming language, Jetty.

### Background and Goals

Kyuubi has enabled RESTful protocol by default since 1.8, the UI is auto-enabled when RESTful protocol is enabled, for some reasons, user may want to disable UI while enabling RESTful protocol.

### Implementation steps

Make enabling Web UI configurable

### Additional context

Introduction of [2024H1 Kyuubi Code Contribution Program](https://github.com/apache/kyuubi/issues/6232)

**Comment by lsm1** [comment]
please assign to me.
