### ISSUE TITLE
[Bug] Kyuubi return query status (FINISH_STATE) quickly, but job still executing.

### ISSUE THREAD

**Issue by DA1OOO** [apache/kyuubi#6302]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

When I submit query by kyuubi to Spark, kyuubi return query status (FINISH_STATE) quickly, but spark job still executing.
<img width="1690" alt="image" src="https://github.com/apache/kyuubi/assets/56857867/217681b5-c560-47e5-95b6-88f0ea7ce41d">

<img width="1434" alt="image" src="https://github.com/apache/kyuubi/assets/56857867/65b5d06a-51cc-444d-9c29-13182c509d19">
<img width="1328" alt="image" src="https://github.com/apache/kyuubi/assets/56857867/83da7ebc-8ad5-4a6a-b76d-adc3deee4704">

Then I find similar bug description in issue. @XorSum https://github.com/apache/kyuubi/issues/5232, in this issue, said this fix has been merged into 1.8.0, but I try both 1.8.0, 1.8.1, 1.9.0, this problem will always arise, Is there any configuration that needs to be modified？

I find my SQL is also `(empty table) left join (big table)`.

my SQL is as follow:
`select
  *
from
  (
      select
      uid
    from
      db.table1
    where
      d_s = 20240408
      and abtest_id like 'sadjjfljlajf'
  ) t1
  left join (
    select
          vendor_id
    FROM
      db.table2
    LATERAL VIEW explode (json_object_keys (countdata)) t1 AS kv 
    WHERE
      d_s = 20240408
  ) t2 on t2.vendor_id = t1.uid
limit
  5;`

in this SQL, the left sub query result is empty (0 rows).
`select
      count(1)
    from
      db.table1
    where
      d_s = 20240408
      and abtest_id like 'sadjjfljlajf'`
![image](https://github.com/apache/kyuubi/assets/56857867/8222b6f1-4882-4b6b-a608-5452fab122c6)

right sub-query result is relative big (4432411935 rows).
`select
          count(1)
    FROM
      db.table2
    LATERAL VIEW explode (json_object_keys (countdata)) t1 AS kv 
    WHERE
      d_s = 20240408`
![image](https://github.com/apache/kyuubi/assets/56857867/a3139b57-6750-46e3-96d7-207952c493d1)

### Affects Version(s)

kyuubi 1.8.0 / 1.8.1/1.9.0    | Spark 3.4.2

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [X] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
cc @cxzl25 and @ulysses-you

**Comment by XorSum** [comment]
Could you provide more information to help me reproduce this bug?
For example, Spark version, the execution plan, and sql code to create `db.table1` and `db.table2`.

**Comment by DA1OOO** [comment]
Spark 3.4.2
**SQL:**
```
 CREATE EXTERNAL TABLE `ios_test_behavior`(                                                          
   `other_column` string,                                                              
   `statusdata` string,                                                                
   `vendor_id` string,                                                                  
   `dt` string,                                                                        
   `countdata` string,                                                                 
   `time` string,                                                                      
   `device` string,                                                                       
   `app_version` string,                                                                 
   `system_version` string,                                                             
   `is_kb` string,                                                              
   `userid` string,                                                                
   `web_id` string,                                                                                    
   `is_test` string)                                                           
 PARTITIONED BY (                                                                                      
   `d_s` string)                                                                                       
 ROW FORMAT SERDE                                                                                      
   'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'                                       
 STORED AS INPUTFORMAT                                                                                 
   'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'                                     
 OUTPUTFORMAT                                                                                          
   'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat';




CREATE EXTERNAL TABLE `ods_test_abtest_uid_daily`(                                                          
   `other_column` string,                                                                                      
   `product` string,                                                                                           
   `abtest_id` string,                                                                                         
   `uid` string,                                                                                               
   `item_type` string)                                                                                         
 PARTITIONED BY (                                                                                              
   `d_s` string)                                                                                               
 ROW FORMAT SERDE                                                                                              
   'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'                                                        
 STORED AS INPUTFORMAT                                                                                         
   'org.apache.hadoop.mapred.TextInputFormat'                                                                  
 OUTPUTFORMAT                                                                                                  
   'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat';


select *
from (
    select vendor_id
    FROM test.ios_test_behavior
      -- 不explode的话 只有1000w数据，无法复现
    LATERAL VIEW explode (json_object_keys (countdata)) t1 AS kv 
    WHERE  d_s = 20240408
  ) t1
  join (
    select uid
    from test.ods_test_abtest_uid_daily
    where d_s = 20240408
      and abtest_id like 'sadjjfljlajf'
  ) t2 on t1.vendor_id = t2.uid
limit 5;


``` 
in table ios_test_behavior, column countdata are json string.
**Physical Plan:**
```
== Physical Plan ==
AdaptiveSparkPlan isFinalPlan=false
+- CollectLimit 5
   +- SortMergeJoin [vendor_id#3676], [uid#3690], Inner
      :- Sort [vendor_id#3676 ASC NULLS FIRST], false, 0
      :  +- Exchange hashpartitioning(vendor_id#3676, 200), ENSURE_REQUIREMENTS, [plan_id=3927]
      :     +- Project [vendor_id#3676]
      :        +- Generate explode(json_object_keys(countdata#3678)), [vendor_id#3676], false, [kv#3693]
      :           +- Project [vendor_id#3676, countdata#3678]
      :              +- Filter isnotnull(vendor_id#3676)
      :                 +- FileScan parquet spark_catalog.test.ios_test_behavior[vendor_id#3676,countdata#3678,d_s#3686] Batched: true, DataFilters: [isnotnull(vendor_id#3676)], Format: Parquet, Location: InMemoryFileIndex(1 paths)[hdfs://user-cn01/user/hive/warehouse/sim..., PartitionFilters: [isnotnull(d_s#3686), (cast(d_s#3686 as int) = 20240408)], PushedFilters: [IsNotNull(vendor_id)], ReadSchema: struct<vendor_id:string,countdata:string>
      +- Sort [uid#3690 ASC NULLS FIRST], false, 0
         +- Exchange hashpartitioning(uid#3690, 200), ENSURE_REQUIREMENTS, [plan_id=3928]
            +- Project [uid#3690]
               +- Filter ((isnotnull(abtest_id#3689) AND (abtest_id#3689 = sadjjfljlajf)) AND isnotnull(uid#3690))
                  +- Scan hive spark_catalog.test.ods_test_abtest_uid_daily [abtest_id#3689, uid#3690], HiveTableRelation [`spark_catalog`.`test`.`ods_test_abtest_uid_daily`, org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe, Data Cols: [other_column#3687, product#3688, abtest_id#3689, uid#3690, item_type#3691], Partition Cols: [d_s#3692], Pruned Partitions: [(d_s=20240408)]], [isnotnull(d_s#3692), (cast(d_s#3692 as int) = 20240408)]

```

**Comment by DA1OOO** [comment]
@XorSum is above information enough to reproduce this case?

**Comment by XorSum** [comment]
@DA1OOO  I tried running the code below on Kyuubi 1.9 and Spark 3.4.2, but I couldn't reproduce your bug. In other words, I can see the `Asked to cancel job group` log.  
Does the number of data rows affect reproducibility? If so, could you explain how to create a test dataset?

```
CREATE TABLE test.ios_test_behavior
(
    `vendor_id` string,
    `countdata` string
) PARTITIONED BY (`d_s` string);
CREATE TABLE test.ods_test_abtest_uid_daily
(
    `abtest_id` string,
    `uid` string
) PARTITIONED BY (`d_s` string);

insert into test.ods_test_abtest_uid_daily partition (d_s ='20240408')
values ('abcde', 1);
insert into test.ios_test_behavior partition (d_s ='20240408')
values (1, '{}');

select *
from (select vendor_id
      FROM test.ios_test_behavior LATERAL VIEW explode (json_object_keys (countdata)) t1 AS kv
      WHERE d_s = 20240408) t1
         join (select uid
               from test.ods_test_abtest_uid_daily
               where d_s = 20240408
                 and abtest_id like 'sadjjfljlajf') t2 on t1.vendor_id = t2.uid
limit 5;
```
<img width="1005"  src="https://github.com/apache/kyuubi/assets/23011702/b5e689da-21d6-4878-93a3-7b3ac9e4014c">

<img width="699"  src="https://github.com/apache/kyuubi/assets/23011702/bf02f6cc-d236-403c-85f6-9f6d78857a91">

**Comment by DA1OOO** [comment]
I think it maybe relative to the number of data rows, because when i not use explode in subquery. it will not be reproduced. i dont have any test dataset, we meet this case in our production environment.

**Comment by XorSum** [comment]
We don't need real datasets in the production environment.   
You just need to create a fake dataset with random data that is large enough to reproduce the bug.

**Comment by DA1OOO** [comment]
ok, I will try to reproduce this case using some test dataset later.

**Comment by DA1OOO** [comment]
I have used [hive test bench](https://github.com/hortonworks/hive-testbench) to reproduce this case.

after build this project `./tpcds-build.sh`, I generate about 5GB data on my HDFS cluster`./tpcds-setup.sh 5 /extwarehouse/tpcds`, and use table **store_sales** to reproduce it.

the follow is the sql which could be used to reproduced this bug.
`select
  *
from
  (
    select
      sum(ss_net_profit) as sum_net_pro,
      sum(ss_net_paid_inc_tax),
      sum(ss_net_paid),
      sum(ss_coupon_amt),
      sum(ss_ext_tax),
      sum(ss_ext_list_price),
      sum(ss_ext_wholesale_cost),
      avg(ss_ext_sales_price),
      sum(ss_ext_discount_amt),
      avg(ss_sales_price),
      sum(ss_list_price),
      avg(ss_wholesale_cost)
    from
      test.store_sales
    group by
      ss_sold_date_sk,
      ss_sold_time_sk,
      ss_item_sk,
      ss_customer_sk,
      ss_cdemo_sk,
      ss_hdemo_sk
  ) t1
  join (
    select
      ss_sold_date_sk,
      ss_sold_time_sk,
      ss_item_sk
    from
      test.store_sales
    where
      ss_net_paid = 101930291
      and ss_ext_discount_amt = 1
  ) t2 on t1.sum_net_pro = t2.ss_item_sk`

this is my kyuubi version information and query's start time and finish time.
![image](https://github.com/apache/kyuubi/assets/56857867/22a10679-cf01-46fb-8962-aa732dd5aede)

this is actual the spark job information.
![image](https://github.com/apache/kyuubi/assets/56857867/c77bea68-dfbe-41ab-804e-b77c14548797)

you can see, before the **job 310** finished, query's state has been change to **FINISHED**.

spark plan:
<img width="683" alt="image" src="https://github.com/apache/kyuubi/assets/56857867/1eadada3-c765-4876-b781-387239bb956a">


relative log:
> grep "932ff7cb-3b52-4abe-bd1e-5851bb77cfcc" _driver.log*
_driver.log:2024-05-13 14:50:17 INFO  OperationLog:64 - Creating operation log file /home/work/linzhaosheng/apache-kyuubi-1.9.0-bin/work/engine_operation_logs/0e5d19a7-1f46-4601-9c77-108ca4016f1d/932ff7cb-3b52-4abe-bd1e-5851bb77cfcc
_driver.log:2024-05-13 14:50:17 INFO  ExecuteStatement:64 - Processing work's query[932ff7cb-3b52-4abe-bd1e-5851bb77cfcc]: PENDING_STATE -> RUNNING_STATE, statement:
_driver.log:2024-05-13 14:50:17 INFO  SQLOperationListener:64 - Query [932ff7cb-3b52-4abe-bd1e-5851bb77cfcc]: Job 310 started with 1 stages, 1 active jobs running
_driver.log:2024-05-13 14:50:17 INFO  SQLOperationListener:64 - Query [932ff7cb-3b52-4abe-bd1e-5851bb77cfcc]: Stage 325.0 started with 10 tasks, 1 active stages running
_driver.log:2024-05-13 14:50:17 INFO  SQLOperationListener:64 - Query [932ff7cb-3b52-4abe-bd1e-5851bb77cfcc]: Job 311 started with 1 stages, 2 active jobs running
_driver.log:2024-05-13 14:50:17 INFO  SQLOperationListener:64 - Query [932ff7cb-3b52-4abe-bd1e-5851bb77cfcc]: Stage 326.0 started with 10 tasks, 2 active stages running
_driver.log:2024-05-13 14:50:24 INFO  SQLOperationListener:64 - Query [932ff7cb-3b52-4abe-bd1e-5851bb77cfcc]: Job 311 succeeded, 1 active jobs running
_driver.log:2024-05-13 14:50:24 INFO  SQLOperationListener:64 - Query [932ff7cb-3b52-4abe-bd1e-5851bb77cfcc]: Job 312 started with 1 stages, 2 active jobs running
_driver.log:2024-05-13 14:50:24 INFO  SQLOperationListener:64 - Query [932ff7cb-3b52-4abe-bd1e-5851bb77cfcc]: Stage 327.0 started with 1 tasks, 2 active stages running
_driver.log:2024-05-13 14:50:24 INFO  SQLOperationListener:64 - Query [932ff7cb-3b52-4abe-bd1e-5851bb77cfcc]: Job 312 succeeded, 1 active jobs running
_driver.log:2024-05-13 14:50:25 INFO  ExecuteStatement:64 - Processing work's query[932ff7cb-3b52-4abe-bd1e-5851bb77cfcc]: RUNNING_STATE -> FINISHED_STATE, time taken: 7.885 seconds
_driver.log:2024-05-13 14:50:25 INFO  ExecuteStatement:64 - statementId=932ff7cb-3b52-4abe-bd1e-5851bb77cfcc, operationRunTime=25 s, operationCpuTime=23 s

> grep "Job 310" _driver.log*
_driver.log:2024-05-13 14:50:17 INFO  SQLOperationListener:64 - Query [932ff7cb-3b52-4abe-bd1e-5851bb77cfcc]: Job 310 started with 1 stages, 1 active jobs running
_driver.log:2024-05-13 14:50:35 INFO  SparkSQLEngineListener:64 - Job end. Job 310 state is JobSucceeded

**Comment by XorSum** [comment]
Thank you for providing the reproduction code.
Unfortunately, I am still unable to reproduce this bug using your tpcds query.

<img width="1565" src="https://github.com/apache/kyuubi/assets/23011702/d56aad9f-5390-448b-a54c-787ed412eb37">
<img width="1560"  src="https://github.com/apache/kyuubi/assets/23011702/8db2c3f0-4498-4c11-a293-1b9c7ec61f87">
<img width="1132"  src="https://github.com/apache/kyuubi/assets/23011702/e5a71db0-8af3-4811-a797-0b8ec136986a">

**Comment by DA1OOO** [comment]
Could this be related to the different configuration of the Spark application?

**Comment by XorSum** [comment]
You can try this script: https://gist.github.com/XorSum/ce9d3d7a6f1ecf7e0cdda7c2cc06c84d

**Comment by DA1OOO** [comment]
Thanks, I will try it soon.

**Comment by wForget** [comment]
Did you make any changes to Kyuubi Spark Engine? Why always use `create table if not exists result.XXX`?

![image](https://github.com/apache/kyuubi/assets/17894939/1048f90f-fd00-4f00-ae80-56d81411ca7e)

**Comment by XorSum** [comment]
> Did you make any changes to Kyuubi Spark Engine? Why always use `create table if not exists result.XXX`?
> 
> ![image](https://private-user-images.githubusercontent.com/17894939/338397696-1048f90f-fd00-4f00-ae80-56d81411ca7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNzA5MDYsIm5iZiI6MTcxODA3MDYwNiwicGF0aCI6Ii8xNzg5NDkzOS8zMzgzOTc2OTYtMTA0OGY5MGYtZmQwMC00ZjAwLWFlODAtNTZkODE0MTFjYTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDAxNTAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NGZmZTczZGUxNWUzOWE5OTdkZDFlZGE1MjVmNzdjNmY3MzI0ZDFhOWM1NTk4Y2EzYjdhMDI4OGZjZTAyMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kzad5346PBthZH14VK1KXGWYkEIqVpufztq_XUblVlc)

No, I did not modify the Spark Engine. I am using the official edition of Spark 3.5.1, which is downloaded from  https://dlcdn.apache.org/spark/spark-3.5.1/spark-3.5.1-bin-hadoop3.tgz

![Screenshot 2024-06-11 at 09-56-40 kyuubi_USER_SPARK_SQL_anonymous_default_70083553-](https://github.com/apache/kyuubi/assets/23011702/de058e2b-79b1-4c41-8c5e-339f19c0ecd1)

**Comment by DA1OOO** [comment]
No any changes too. the reason for `create table` is I need to persist result in hive on hdfs.

**Comment by wForget** [comment]
@DA1OOO Do you enable incremental collection?

**Comment by DA1OOO** [comment]
this `kyuubi.operation.incremental.collect` parameter in kyuubi? I don't open it.

**Comment by ulysses-you** [comment]
@DA1OOO The `FINISH_STATE` query status is expected. The sql query has already finished since one join side is empty (Spark AQE optimzie it). The running job/stage is the other join side shuffle stage which has no meaning. BTW, if your Spark version is less than 3.4, the Spark sql execution status may be wrong, see [SPARK-40834](https://issues.apache.org/jira/browse/SPARK-40834).

**Comment by DA1OOO** [comment]
@ulysses-you My Spark version is 3.4.2. `FINISH_STATE` query status return quickly is expected, but if in the correct situation, when query has already finished because of one emtpy join side, the other not empty join side should be immediately cancelled, instead of occupying cluster resources and running continuously?

**Comment by DA1OOO** [comment]
By the way, after I got `FINISH_STATE` from kyuubi, I don't close corresponding operation, when I try to close operation manually, the other not empty join side will be cancelled correctly.

**Comment by ulysses-you** [comment]
@DA1OOO there are some stories about the behavior you see.

> when query has already finished because of one emtpy join side, the other not empty join side should be immediately cancelled, instead of occupying cluster resources and running continuously

The idea is reasonable. In fact, I have an [attempt](https://github.com/apache/spark/pull/41536) before, however there are some issues if we cancel the running stage in aqe. So it is a kind of known Spark issue.

> when I try to close operation manually, the other not empty join side will be cancelled correctly.

When call close operation, Kyuubi will cancel all jobs for the target statement, so the legacy job/stages are cancelled.

**Comment by DA1OOO** [comment]
> You can try this script: https://gist.github.com/XorSum/ce9d3d7a6f1ecf7e0cdda7c2cc06c84d

@XorSum I've tried your script, it seems to have cancelled job group correctly.

![image](https://github.com/apache/kyuubi/assets/56857867/812a59d0-acc8-47a0-b1ac-419a43ac6135)

![image](https://github.com/apache/kyuubi/assets/56857867/e26ad36e-b9a1-4999-a5ca-cf3d8181fb19)

@ulysses-you Do you means only if i enabled spark AQE, the legacy jobs wouldn't be cancelled immediately?

**Comment by DA1OOO** [comment]
@XorSum I find when I submit SQL to my yarn cluster by beeline, the legacy job will be cancelled correctly. But when I submit SQL by Kyuubi Rest Api (the same kyuubi path with BEELINE), the legacy job will not be cancelled.  
![image](https://github.com/apache/kyuubi/assets/56857867/349f57b6-9613-4b64-a3bf-a8f2b879aaec)

BEELINE log:
![image](https://github.com/apache/kyuubi/assets/56857867/c6ee36a7-80e0-476b-bddc-592c20b95f2d)

REST API log:
![image](https://github.com/apache/kyuubi/assets/56857867/b657b214-45d7-47bd-a541-9f48dd5787d1)

**Comment by XorSum** [comment]
The reason of the bug is that Rest Api session doesn't call  `SparkOperation#close`, `SparkOperation#cleanup` and  `sparkContext.cancelJobGroup`,  so the legacy job submitted by Rest Api will not be canceled.
To address this issue, I have submitted a pull request (https://github.com/apache/kyuubi/pull/6473) that resolves the bug by calling `cancelJobGroup` in `ExecuteStatement#executeStatement`.

However, the root cause is that the REST API session does not call the `SparkOperation#close` method. This might lead to other potential problems.

**Comment by DA1OOO** [comment]
Thanks. would this issue be merged to which version?
 We have manually closed the operation after receiving the `FINISHED` status from Kyuubi in our project.
