### ISSUE TITLE
[BUG] Unable to use SET kyuubi.operation.language=scala;

### ISSUE THREAD

**Issue by WilliamTan778** [apache/kyuubi#6303]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

![image](https://github.com/apache/kyuubi/assets/41814775/ba3c28d4-abf1-4763-acd7-a51f5e0bde3a)

### Affects Version(s)

1.9.0

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
The beeline says: "Connected to: Apache Hive (version 2.3.9)", obviously, Hive does not support Scala
