### ISSUE TITLE
[FEATURE] Respect `hive.server2.thrift.resultset.default.fetch.size` configuration in kyuubi server

### ISSUE THREAD

**Issue by wForget** [apache/kyuubi#6338]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Respect `hive.server2.thrift.resultset.default.fetch.size` configuration in kyuubi server

### Motivation

After [HIVE-23005](https://issues.apache.org/jira/browse/HIVE-23005), hive driver requires that openSession response from server must contain `hive.server2.thrift.resultset.default.fetch.size` configuration.

When we use hive driver 4.0+ to connect to kyuubi, we get the following error::

```
Server returned a null default fetch size. Check that hive.server2.thrift.resultset.default.fetch.size is configured correctly.
```

### Are you willing to submit PR?

- [x] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by scpcy** [comment]
Still the problem persist using the Hive jdbc driver 4.0

**Comment by pan3793** [comment]
@scpcy any additional information except for "does not work"?

**Comment by scpcy** [comment]
"erver returned a null default fetch size. Check that hive.server2.thrift.resultset.default.fetch.size is configured correctly."

this is the error I get using kyuubi 1.9.2 using thrift server http protocol

**Comment by pan3793** [comment]
> ... using thrift server http protocol

it requires https://github.com/apache/kyuubi/pull/6648, let me backport it to branch-1.9, and start to discuss 1.9.3 release
