### ISSUE TITLE
[Improvement] kyuubi-server/web-ui should not to set a timeout for axios requests

### ISSUE THREAD

**Issue by zRains** [apache/kyuubi#6428]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

When executing complex queries in the SQL Editor, axios may prematurely terminate the request while Spark is still processing the task. We should remove this limitation.

https://github.com/apache/kyuubi/blob/1e08064123e5ae0200a733b1d490769ed6da4281/kyuubi-server/web-ui/src/utils/request.ts#L22-L26

![image](https://github.com/apache/kyuubi/assets/16508606/17a672a1-7be4-4e09-a316-c30f35661eba)

![image](https://github.com/apache/kyuubi/assets/16508606/3dd61860-51a0-4324-8f87-069d434e9f65)

### How should we improve?

Remove axios request timeout limitation.

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by JiaLiangC** [comment]
I met Same problem, I believe the web request timeout should be controlled by configurations in the backend Kyuubi server. If the timeout is set in the web code, it will be difficult for users to configure it.
