### ISSUE TITLE
[Improvement] Propose to use `hive-pure-sasl` instead of `hive_pure_sasl`

### ISSUE THREAD

**Issue by camper42** [apache/kyuubi#6445]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

We have a python package depends on `pyhive[hive_pure_sasl]`, and we use poetry to manage packaging.

```toml
# our package's pyproject.toml
[tool.poetry.dependencies]
PyHive = { extras = ["hive_pure_sasl"], version = "^0.7.0" }
```

user install our package, get a `WARNING: pyhive 0.7.0 does not provide the extra 'hive-pure-sasl'` and only installed `pyhive` without `hive_pure_sasl` extra, `pure-sasl`, `thrift` and `thrift_sasl` are missing.

after some investigations, I found this https://github.com/python-poetry/poetry/issues/6819.

according to [PEP 503](https://peps.python.org/pep-0503/#normalized-names) and [PEP 685](https://peps.python.org/pep-0685/#specification), I think we should use `hive-pure-sasl` instead of `hive_pure_sasl` to declear extra requires to avoid this problem.

### How should we improve?

change to `'hive-pure-sasl': ['pure-sasl>=0.6.2', 'thrift>=0.10.0', 'thrift_sasl>=0.1.0'],`
and release 0.7.1

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
@camper42 I respect your professionalism in the Python area, please go ahead, and looking forward to your further contributions to the Python module :)

**Comment by camper42** [comment]
I will verify on our internal pypi that the behavior is as expected first. 
happy to contribute to the Python module
