### ISSUE TITLE
[TASK][EASY] Add tests for Spark saveToFile function

### ISSUE THREAD

**Issue by cxzl25** [apache/kyuubi#6446]
### What's the level of this task?

EASY

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/343) and found no similar tasks.

### Mentor

- [X] I have sufficient expertise on this task, and I volunteer to be a mentor of this task to guide contributors through the task.

### Skill requirements

Familiar with Kyuubi and Spark.

### Background and Goals

Currently the Spark saveToFile feature enabled via `kyuubi.operation.result.saveToFile.enabled` lacks testing, and modifying this related feature can easily lead to regressions.

### Implementation steps

Add test

### Additional context

Introduction of [2024H1 Kyuubi Code Contribution Program](https://github.com/apache/kyuubi/issues/6232)

**Comment by lsm1** [comment]
please assign to me
