### ISSUE TITLE
Please include Flink engine support for data lineage

### ISSUE THREAD

**Issue by smileyboy2019** [apache/kyuubi#6462]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

At present, Kyuubi supports Spark lineage, but other components do not support it yet. There is an open source Flink lineage support project that I hope to join.

### Describe the solution

Please refer to the following address content:
https://blog.csdn.net/qq_15138049/article/details/131210544#comments_32027985
https://github.com/gyfora/atlas/tree/flink-bridge/addons/flink-bridge-shim

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
This feature is likely to happen upstream, see [FLIP-314](https://cwiki.apache.org/confluence/display/FLINK/FLIP-314%3A+Support+Customized+Job+Lineage+Listener) for more details.
