### ISSUE TITLE
[Improvement] Kyuubi simulates Hive's proxy submission mode

### ISSUE THREAD

**Issue by chenfengbin2009** [apache/kyuubi#6474]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

simulates Hive's commit method in Spark JDBC, which can avoid the need to apply for additional HDFS permissions when applying for permissions.

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
Close as duplicated with #6472
