### ISSUE TITLE
[TASK][EASY] DeRegisterWatcher should re-watch when any event is received

### ISSUE THREAD

**Issue by cxzl25** [apache/kyuubi#6477]
### What's the level of this task?

EASY

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/343) and found no similar tasks.

### Mentor

- [X] I have sufficient expertise on this task, and I volunteer to be a mentor of this task to guide contributors through the task.

### Skill requirements

- Basic knowledge on Scala programming language

### Background and Goals

The `NodeDataChanged` event listener is implemented at https://github.com/apache/kyuubi/pull/3543, but there is still a small chance that the watch event will be lost.

In the internal version of the fix, we receive any event that implements rewatch.

The following log shows that it received `Watcher.Event.EventType#None`.
```
24/06/17 07:33:14,909 [main-EventThread] WARN ZookeeperDiscoveryClient: This Kyuubi instance xxx (znode null) receives None
24/06/17 07:33:17,201 [main-EventThread] INFO ConnectionStateManager: State change: SUSPENDED
24/06/17 07:33:17,202 [main-EventThread] WARN ZookeeperDiscoveryClient: This Kyuubi instance xxx:xx (znode null) receives None
```

### Implementation steps

DeRegisterWatcher should re-watch when any event is received

### Additional context

Introduction of [2024H1 Kyuubi Code Contribution Program](https://github.com/apache/kyuubi/issues/6232)

**Comment by CavemanIV** [comment]
Let me take care of this issue please

**Comment by cxzl25** [comment]
https://github.com/apache/zookeeper/blob/837f86cc713a5e4ce56e1f75eeb335093ca18821/zookeeper-server/src/main/java/org/apache/zookeeper/ZKWatchManager.java#L353-L376
