### ISSUE TITLE
Port ZOOKEEPER-4377 to Kyuubi shaded ZooKeeper 3.4 and 3.6

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#6496]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Port ZOOKEEPER-4377 (https://github.com/apache/zookeeper/pull/1764) to https://github.com/apache/kyuubi-shaded/tree/master/kyuubi-relocated-zookeeper-parent/kyuubi-relocated-zookeeper-34 and https://github.com/apache/kyuubi-shaded/tree/master/kyuubi-relocated-zookeeper-parent/kyuubi-relocated-zookeeper-36

### How should we improve?

By default, Kyuubi uses the shaded ZooKeeper 3.4 client to gain compatibility, while it may cause NPE when accessing a higher version of the ZooKeeper server, for example, https://github.com/apache/kyuubi/issues/1894, we should backport ZOOKEEPER-4377 to gain a clear error message.

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by Madhukar98** [comment]
Hi @pan3793, I would like to take this up. But I might need some more clarity. Are we supposed to make these changes in zookeeper repo? Because I can't see the KeeperException file in kyuubi-relocated-zookeeper.

**Comment by pan3793** [comment]
@Madhukar98 you can refer to https://github.com/apache/kyuubi-shaded/pull/28 and https://github.com/apache/kyuubi-shaded/pull/29

**Comment by pan3793** [comment]
@Madhukar98 thanks for taking this, I'm going to start voting for `kyuubi-shaded` 0.4.1 to deliver this change.
