### ISSUE TITLE
[Bug] Kyuubi 1.19.1 Spark engine small file not merged issue

### ISSUE THREAD

**Issue by zapjone** [apache/kyuubi#6502]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Kyuubi 1.19.1 Spark engine cannot automatically merge small files. Do you need to add any parameters? I didn't see the extensions directory either
Spark version is 3.4.3;
Spark configuration:
spark.dynamicAllocation.enabled true
spark.dynamicAllocation.minExecutors 1
spark.dynamicAllocation.maxExecutors 200
spark.dynamicAllocation.shuffleTracking.enabled true
spark.sql.adaptive.enabled true
spark.sql.adaptive.merge.output.small.files.enabled true
spark.sql.adaptive.shuffle.targetPostShuffleInputSize 268435456
spark.sql.adaptive.coalescePartitions.enabled true
spark.sql.adaptive.coalescePartitions.minPartitionNum 1
spark.sql.adaptive.coalescePartitions.initialPartitionNum 1500
spark.sql.adaptive.advisoryPartitionSizeInBytes 268435456
spark.sql.adaptive.advisoryOutputFileSizeInBytes 268435456
spark.sql.optimizer.insertRepartitionBeforeWrite.enabled true

### Affects Version(s)

1.19.1

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
This is duplicated with https://github.com/apache/kyuubi/discussions/6501, do NOT create spam issues.
