### ISSUE TITLE
[FEATURE] `kyuubi-beeline` supports `--conf`

### ISSUE THREAD

**Issue by BruceWong96** [apache/kyuubi#6506]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Hi ,
I propose that we support the use of `--conf` in kyuubi-beeline, like this:

```
kyuubi-beeline -u 'jdbc:kyuubi://kyuubi:10009/' \
    --conf kyuubi.operation.result.format=arrow \
    --conf kyuubi.operation.incremental.collect=true \
    --conf spark.app.name=xxx \
    large_result_query.sql
```

### Motivation

When I use kyuubi-beeline, I need to specify some configuration, so I need to use the following command.
```
kyuubi-beeline -u 'jdbc:kyuubi://kyuubi:10009/' \
    --hiveconf kyuubi.operation.result.format=arrow \
    --hiveconf kyuubi.operation.incremental.collect=true \
    --hivevar spark.app.name=xxx \
    large_result_query.sql
```
I suggest that we keep the above usage and add the following usage as well.

```
kyuubi-beeline -u 'jdbc:kyuubi://kyuubi:10009/' \
    --conf kyuubi.operation.result.format=arrow \
    --conf kyuubi.operation.incremental.collect=true \
    --conf spark.app.name=xxx \
    large_result_query.sql
```

And this is a convenience for Spark users, because we often use `--conf` like this :
```
spark-submit \
    --conf spark.app.name=xxx \
    --conf spark.driver.memory=1g
    ...
```

### Describe the solution

Add a `--conf` alias to the `--hiveconf`.
Do the same for the configuration items that follow them.

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
Nice proposal, looking forward to your contribution.
