### ISSUE TITLE
[AUTHZ] Check previleges for Paimon

### ISSUE THREAD

**Issue by promising-forever** [apache/kyuubi#6541]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Before this PR, If Spark-ranger is enabled, the Paimon query will be rejected, because the corresponding dbname cannot be obtained when the plan is parsed.
when the **select xx from pamion.db.table** commond is executed.
The DataSourceV2Relation#table in org.apache.paimon.spark.SparkTable, The 'database' value could not be obtained, ranger need this parameter during verification.
![image](https://github.com/user-attachments/assets/aaecc768-14fd-43dd-8c79-30218f2e9683)

### Affects Version(s)

1.9.1

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
Seems there is nothing we can do on the Kyuubi side.

**Comment by promising-forever** [comment]
> Seems there is nothing we can do on the Kyuubi side.

We can get database from DataSourceV2Relation#identifier to make up for this. Otherwise, if a user wants to access paimon, AUTHZ needs to be removed, but AUTHZ is needed in the case of multiple catalogs.

**Comment by pan3793** [comment]
Please go ahead to make a PR
