### ISSUE TITLE
[Improvement]  When EngineRef.exitValue returns a non-0 status. Hopefully, can print an error message

### ISSUE THREAD

**Issue by Toms5578** [apache/kyuubi#6573]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

When EngineRef.exitValue returns a non-0 status. Hopefully,  can print an error message

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by Toms5578** [comment]
eg :

**Comment by Toms5578** [comment]
eg:
        BufferedReader reader = new BufferedReader(new InputStreamReader(start.getErrorStream()));
        String line;
        while ((line = reader.readLine()) != null) {
            System.out.println(line);
        }

**Comment by Toms5578** [comment]
eg：    BufferedReader reader = new BufferedReader(new InputStreamReader(process.getErrorStream()));
        String line;
        while ((line = reader.readLine()) != null) {
            System.out.println(line);
        }

**Comment by pan3793** [comment]
what's the current behavior you observed? I think you should see error messages when something goes wrong on engine launching.

**Comment by Toms5578** [comment]
> 您观察到的当前行为是什么？我认为当引擎启动时出现问题时您应该会看到错误消息。

The client reports an error as ：Failed to detect the root cause, please check /data/kyuubi/logs/work/****/kyuubi-spark-sql-engine.log.62 at server side if necessary. The last 10 line(s) of log are:
But the size of this file is 0

**Comment by Toms5578** [comment]
the retry succeeds, fault locating is affected

**Comment by Toms5578** [comment]
I suppose ：this error occurred when executing the spark script.     bin/spark-class

**Comment by pan3793** [comment]
what's your version? does it include https://github.com/apache/kyuubi/pull/6422(fixed in 1.9.1/1.8.3)?

**Comment by Toms5578** [comment]
> 你的版本是什么？它包含#6422吗（已在 1.9.1/1.8.3 中修复）？

1.6.0  Thank you.
