### ISSUE TITLE
Upgrade flip-tables from 1.0.2 to 1.1.1

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#6584]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Why do we need to upgrade this artifact?

Usage of New Features

### Artifact Name

https://mvnrepository.com/search?q=flip-tables

### Target Version

1.1.1

### Notable Changes

https://github.com/JakeWharton/flip-tables/blob/1.1.1/CHANGELOG.md

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by Madhukar525722** [comment]
Hi @pan3793 , I would like to work on this
