### ISSUE TITLE
[Improvement] Support `bin/kyuubi kill` command

### ISSUE THREAD

**Issue by yaooqinn** [apache/kyuubi#6593]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

We have `bin/kyuubi stop` command to stop kyuubi server gracefully, this new command bypasses the grace period and send SIGKILL directly.

This is useful for terminating hanged servers

### How should we improve?

This is a simple case 

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [X] No. I cannot submit a PR at this time.

**Comment by BruceWong96** [comment]
Hi,
I can finish it. Could you assign it to me ?
Thanks.

**Comment by yaooqinn** [comment]
@BruceWong96 assigned
