### ISSUE TITLE
[Improvement] Improve the display of sql editor and query result

### ISSUE THREAD

**Issue by wangzhigang1999** [apache/kyuubi#6660]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

![image](https://github.com/user-attachments/assets/2a98eb47-ac28-4157-9a57-2ae63707d854)
The image shows a SQL Editor that has **only a few lines of code displayed, despite having ample space available**. This underutilization of screen real estate can lead to inefficiencies in workflow, as users might find themselves scrolling or switching between multiple screens to manage their SQL queries effectively.

Additionally, the limited display area might make it challenging for users to work on more complex SQL statements or compare multiple lines of code at once. This could negatively impact productivity and make the overall experience less intuitive and user-friendly.

### How should we improve?

![image](https://github.com/user-attachments/assets/33958fb0-9d59-4e9b-94a9-eebfe3fc8c5f)

My solution consists of two key changes: first, I recommend expanding the SQL Editor to take up the entire screen, which will give users more room to write and edit their code without constantly needing to scroll or switch between screens. This modification will result in a cleaner and less cluttered environment for SQL coding.

Secondly, I propose incorporating a drawer feature to display query results. In this context, the drawer will reveal the outcomes of executed SQL queries, enabling users to review their results without losing sight of their code or leaving the SQL Editor.

I've implemented a simple version, and the effect is shown in the image above. If possible, I would be happy to submit a PR. Additionally, if the community has other better solutions, I would be open to considering those as well.

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by wangzhigang1999** [comment]
add new example
![image](https://github.com/user-attachments/assets/93b09575-6973-4cfc-ae68-264f19d4c4f9)

**Comment by pan3793** [comment]
Thanks for your idea, how about?
```
---------------------------------------
|                                     |
|                                     |
|              SQL Editor             |
|                                     |
|                                     |
--------------------------------------- Draggable Border
|                                     | Also buttons to allow minimize/maximize the Result/Log pannel
|              Result/Log             |
|                                     |
---------------------------------------
```

**Comment by wangzhigang1999** [comment]
> Thanks for your idea, how about?
> 
> ```
> ---------------------------------------
> |                                     |
> |                                     |
> |              SQL Editor             |
> |                                     |
> |                                     |
> --------------------------------------- Draggable Border
> |                                  v ^| Also buttons to allow minimize/maximize the Result/Log pannel
> |              Result/Log             |
> |                                     |
> ---------------------------------------
> ```

Good idea! 🫡
