### ISSUE TITLE
[Bug] How to use GROUP Share Level without Hadoop

### ISSUE THREAD

**Issue by A-little-bit-of-data** [apache/kyuubi#6683]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

I started the kyuubi pod in a k8s environment and used spark SQL to query S3 data. There is no Hadoop environment at all. However, according to the documentation, the kyuubi.session.group.provider configuration seems to only have hadoop. Does that mean that GROUP Share Level can only be used in an environment with hadoop?

### Affects Version(s)

1.9.1

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [X] No. I cannot submit a PR at this time.

**Comment by wangzhigang1999** [comment]
From the code, it appears that Hadoop is currently the only built-in implementation. 

However, according to **org.apache.kyuubi.plugin.PluginLoader#loadGroupProvider**, you can implement the **GroupProvider** interface to create your own plugin.
