### ISSUE TITLE
[Bug] Error 405 when accessing kyuubi webui service

### ISSUE THREAD

**Issue by SGITLOGIN** [apache/kyuubi#6749]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug
Kyuubi configuration
kyuubi.authentication                    LDAP,KERBEROS

The links corresponding to the following two buttons require administrator privileges and cannot be accessed by other users
http://ali-odp-test-01:10099/api/v1/admin/operations
http://ali-odp-test-01:10099/api/v1/admin/sessions

<img width="1679" alt="image" src="https://github.com/user-attachments/assets/a603a0a8-8ce5-488a-96a8-cd3096d175b4">

<img width="1678" alt="image" src="https://github.com/user-attachments/assets/55fcd27e-178e-4fa4-9847-1d892f68879e">

<img width="1337" alt="image" src="https://github.com/user-attachments/assets/73fec2e8-d923-40a9-98c4-b854a55e2648">

### Affects Version(s)

kyuubi 1.9.2

### Kyuubi Server Configurations

kyuubi.authentication                    LDAP,KERBEROS
kyuubi.kinit.principal hive/_HOST@HUAN.TV
kyuubi.kinit.keytab /etc/security/keytabs/hive.service.keytab
kyuubi.authentication.ldap.baseDN=dc=hadoop,dc=com
kyuubi.authentication.ldap.url=ldap://......:389/
kyuubi.authentication.ldap.userDNPattern UID=%s,OU=People,DC=hadoop,DC=com

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
it's a by design behavior
