### ISSUE TITLE
[FEATURE]  HiveStatement.getQueryLog return spark stage progress information

### ISSUE THREAD

**Issue by melin** [apache/kyuubi#6788]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

HiveStatement.getQueryLog return spark stage progress information

ref:  https://github.com/apache/hive/blob/branch-3.1/ql/src/java/org/apache/hadoop/hive/ql/exec/spark/status/impl/RemoteSparkJobStatus.java

![image](https://github.com/user-attachments/assets/c58f6700-03fc-4a4c-ae2a-37677512ab49)

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
we have already provided aggregated stage status https://github.com/apache/kyuubi/pull/2529

**Comment by pan3793** [comment]
close because it has no valuable motivation
