### ISSUE TITLE
[Bug] upgrade zookeeper version to fix ZOOKEEPER-4377

### ISSUE THREAD

**Issue by melin** [apache/kyuubi#6794]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

https://issues.apache.org/jira/browse/ZOOKEEPER-4377
![image](https://github.com/user-attachments/assets/dc010d19-e8d9-4e4d-a412-eda36e27d61a)

### Affects Version(s)

1.9.2

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
do search before asking https://github.com/apache/kyuubi/issues/6496
