### ISSUE TITLE
[FEATURE] Support User Impersonation for Kyuubi

### ISSUE THREAD

**Issue by nqvuong1998** [apache/kyuubi#6801]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

This feature controls the ability of a user to impersonate another user. In some environments it is desirable for an administrator (or managed system) to run queries on behalf of other users. In these cases, the administrator authenticates using their credentials, and then submits a query as a different user. When the user context is changed, Trino verifies that the administrator is authorized to run queries as the target user.

### Motivation

Using BI tools like HUE and Superset, set up a connection URL with admin credentials. Then, enable impersonation so that the login user operates with their own permissions.

### Describe the solution

Trino Impersonation rules: https://trino.io/docs/current/security/file-system-access-control.html#impersonation-rules

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [X] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
This could not be fully implemented without hacking Spark, we recommend using the USER/CONNECTION share level on Kerberized Hadoop cluster to achieve the goal.
